### ISSUE TITLE
FreeBSD very slow on CI

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/build#1006]
Seems like FreeBSD 10 is running very slow currently (e.g. https://ci.nodejs.org/job/node-test-commit-freebsd/13488/). Is there any chance to improve that? The CI needs more than 3 hours to complete because of that.

**Comment by rvagg** [comment]
If you go into the build executions you'll see that both 10 and 11 only take 16 minutes, it's the parent job that's taking 3 hours. The console of that parent job shows:

> Configuration node-test-commit-freebsd » freebsd10-64 is still in the queue: Waiting for next available executor on freebsd10-64

So I think it's just a queue thing. If you see it persisting then perhaps there's something to investigate but my guess is that it was only temporary and maybe because we had some long-running jobs in the queue (citgm).

**Comment by BridgeAR** [comment]
Thanks a lot for the note! I missed that. Seems like it is working fine again.

**Comment by refack** [comment]
So the actual problem has that 1 of the two workers was stuck on a job for 6 days
https://ci.nodejs.org/job/node-test-commit-freebsd/nodes=freebsd10-64/13313/
effectively choking the queue.

**Comment by rvagg** [comment]
also worth noting that I'm regularly logging in to the freebsd10 machines to restart the jenkins service. it's not got monit or anything similar so if it dies it stays dead until someone notices. If someone wants a quick TODO then you could add monit or similar to the ansible setup for freebsd10 (and above? I think they all still using initd don't they?)
