### ISSUE TITLE
infra: both mach freebsd11 machines are offline

### ISSUE THREAD

**Issue by refack** [nodejs/build#1036]
As reported by @Trott http://logs.libuv.org/node-build/2017-12-09#13:06:36.888

Both [`test-digitalocean-freebsd11-x64-1`](https://ci.nodejs.org/computer/test-digitalocean-freebsd11-x64-1/) and [`test-digitalocean-freebsd11-x64-2`](https://ci.nodejs.org/computer/test-digitalocean-freebsd11-x64-2/) are non repsonsive to SSH, no. 2 doesn't respond to pings either.
Seems like since https://ci.nodejs.org/job/node-test-commit-freebsd/nodes=freebsd11-x64/13928/

As a mitigation measure I removed the `freebsd11-x64` label from [`node-test-commit-freebsd`](https://ci.nodejs.org/job/node-test-commit-freebsd/)

/PING infra team (@gibfahn @jbergstroem @joaocgreis @mhdawson @rvagg)

**Comment by refack** [comment]
Also had to remove from [`libuv-test-commit-freebsd`](https://ci.nodejs.org/job/libuv-test-commit-freebsd).
P.S. Jenkins goes crazy is the situation jobs are queued on a starved platform.

**Comment by joaocgreis** [comment]
Power cycled the machines, added back to the jobs. Had to clean the workspace on `-2`. Should be working again. Tests: [node on 1](https://ci.nodejs.org/job/node-test-commit-freebsd/13987/nodes=freebsd11-x64/), [node on 2](https://ci.nodejs.org/job/node-test-commit-freebsd/13988/nodes=freebsd11-x64/), [libuv](https://ci.nodejs.org/job/libuv-test-commit-freebsd/602/nodes=freebsd11-x64/).

I suspect some of the Jenkins failures we have not been able to explain are because the machines run out of memory while testing. I've seen one Node-ChakraCore test reliably crashing Jenkins, on a machine that had enough memory (2Gb) to test Node-V8 but not ChakraCore and no swap. I don't know if this could have cause the failure here by killing some process that brought the machines to this state, but it may justify some of the other failures we see from time to time.

**Comment by refack** [comment]
I'd call this issue solved.
Ping @nodejs/platform-freebsd for tips on memory management?
