### ISSUE TITLE
arm fanned is no longer building

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#1039]
https://ci.nodejs.org/job/node-test-commit-arm-fanned/

**Comment by rvagg** [comment]
@joaocgreis I can't find the ip/login details of these Azure hosts in our repos and I also can't see azure admin logins in our admin_logins.md. I thought I had record of the hosts at least but I'm not sure where they are. Could you put this all somewhere, either in ansible/inventory.yml or secrets/build/*?

**Comment by joaocgreis** [comment]
Cleaned the workspace, the worker is back online, should be fixed.

The root filesystem was full, so I moved the Jenkins workspace to a temporary storage area to avoid this problem in the future.

@rvagg https://github.com/nodejs/build/pull/244 landed recently, so now the info about that machine lives in [`setup/cross-compiler/`](https://github.com/nodejs/build/tree/master/setup/cross-compiler). It uses the node test key. It should probably be added to the new ansible inventory, but I'm not sure it supports DNS addresses instead of direct IP addresses as is the case for all Azure hosts. A full refactor to the new Ansible would take some effort.
