### ISSUE TITLE
Updating admin lists

### ISSUE THREAD

**Issue by maclover7** [nodejs/build#1107]
I was working on some stuff with Jenkins earlier, and noticed that I did not have access to create jobs. My impression is that `nodejs/jenkins-admins` are the only people, based on [this document](https://github.com/nodejs/build/blob/master/doc/access.md), that have this kind of permissions. I am wondering if there is a process listed anywhere about how to "move up" in access level, as for me, these functions are important. Same goes for infra team, doesn't look like there is anything formalized for that (could help with getting #1070, #962, etc. resolved fast). @trott, not sure if you have run into any of these issues, but I definitely have.

cc @nodejs/build @nodejs/jenkins-admins

**Comment by gibfahn** [comment]
Accesses are documented here: https://github.com/nodejs/build/blob/master/doc/access.md

We don't currently have docs for how to get additional accesses, but such docs would go in access.md if required.

In my experience existing team members propose new people privately. The bar for jenkins-admins is a fair bit higher than for build, but I agree we definitely need to increase the list of members.

**Comment by maclover7** [comment]
ping @gibfahn @rvagg @mhdawson, this came up again today when I was trying to get http2 benchmarks working, since I do not have job edit or create permissions. Having elevated permissions would be very useful

**Comment by rvagg** [comment]
One of the problems we have is how to establish trust. It's not very fair, but it's significantly easier to establish trust with someone who is an employee of a major corporate entity. Especially if they are contributing on behalf of that entity. So IBM, NodeSource and James Systems on behalf of Microsoft employees are easy to establish a trust relationship with. These people have contracts with their employers and we can hold people and companies responsible. With member companies it's even more straightforward since they have a direct interest and relationship with the foundation. 
As we move beyond these companies, particularly to individuals without an affiliation with a major corporate entity.

The main area where this responsibility matters is release infrastructure since (I think) the most important thing we do here is ensure the safe and secure delivery of bianries to Node users.

jenkins-admins has basically been used as an infra group for the purpose of accessing Jenkins. It gives you access to ci-release as well as ci. So, what I'd like to propose is the creation of a jenkins-release-admins to separate the two concerns and therefore make it easier to elevate people through the test infra permissions scale rather than having basically two levels. 

It doesn't entirely solve our problems, I still think the infra team is too small, it could do with a couple more active people I think. But that's not something we can rush for the above reasons.

**Comment by mhdawson** [comment]
+1 from me.
