### ISSUE TITLE
arm cross compile is down

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#1113]
Has been failing since Feb 10, 2018 7:47 PM

https://ci.nodejs.org/job/node-cross-compile/

Single passing run since then was on v4.x

Looks like something with the internal compiler / libc

```
/task-queue.o ../deps/v8/src/libplatform/task-queue.cc
make[2]: *** [/mnt/workspace/node-cross-compile/out/Release/obj.host/v8_libplatform/deps/v8/src/libplatform/default-platform.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /usr/include/c++/4.9/deque:60:0,
                 from /usr/include/c++/4.9/queue:60,
                 from ../deps/v8/src/libplatform/task-queue.h:8,
                 from ../deps/v8/src/libplatform/task-queue.cc:5:
/usr/include/c++/4.9/bits/stl_algobase.h:59:28: fatal error: bits/c++config.h: No such file or directory
 #include <bits/c++config.h>
                            ^
compilation terminated.
```

**Comment by rvagg** [comment]
@joaocgreis I'm going to have to defer to you on this one. I've been in there and can't work it out. My best guess is that an update on the host messed up the cross-compile configuration, something to do with gcc. It's using 4.9 but the config suggests it's supposed to be using 4.8 on the host and not going anywhere near /usr/include/c++/4.9/ which is where these errors are coming from.

For now I've removed arm-fanned from node-test-commit because it's just going to keep on failing.

**Comment by joaocgreis** [comment]
This happened right after https://github.com/nodejs/build/pull/1110, which updated the native compiler without installing the multilib packages. I've changed the `cc-*` scripts to explicitly use gcc-4.8, testing now: https://ci.nodejs.org/job/node-cross-compile/14314 (might take a while if ccache does not realize it's the same compiler).

**Comment by joaocgreis** [comment]
Test looks good, added arm-fanned back to test-commit. Please reopen if the problem persists.
