### ISSUE TITLE
conventional-changelog compromised

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#1120]
https://github.com/conventional-changelog/conventional-changelog/issues/282

we may want to check if `/tmp/.debug` exists and make sure our test CI environments are not mining crypto

**Comment by rvagg** [comment]
Thanks for the heads-up @MylesBorins 
I've done a quick `test -e /tmp/.debug` on our non-windows machines @ https://ci.nodejs.org/view/All/job/run-script-on-all/1/ and the ones that can currently respond are all giving a false, so that's positive. I think this might need deeper investigation, however, and I'm trying to think of how we might do that across all our machines in a way that isn't simply testing for the existence of a file.

**Comment by MylesBorins** [comment]
@rvagg to be honest I would really like to see if it would be possible to containerize a bunch of our infra so that we can spin down instances after running and minimize the possibility of rogue code causing lasting issues.

If this is something build is interested in I could see if there are any googlers who might have spare cycles to volunteer and help.

**Comment by rvagg** [comment]
We've had discussions around this in the past and there are a few issues, mainly:

1. Containerized environments are even more artificial than working inside VMs and it becomes difficult to separate out errors caused by running in a container vs errors caused by running in the arch/os you're actually trying to test (see the recent Alpine 3.4 test failure being debated because it can't be reproduced locally even in a container, sorry I don't have the link at hand).
2. Our current infra providers don't have good solutions for us to run such environments (afaik) so we'd have to do even more orchestration on our end which is just more overhead. Joyent is the only one that does, but they are pretty artificial environments because they don't run on top of Linux like you'd expect so we get a ton of weird failures of our tests when we've tried to run tests inside their containers (see also point 1).

We've discussed doing this with VM images, I think our major infra providers have ways for us to do this. The idea would be that we create base images and spin them up and down as needed and we get to start from scratch whenever we start them. There's setup and maintenance overhead there as well as the overhead of hooking all of the pieces together with Jenkins and having enough people understand how it all works so that _when_ it breaks it can be fixed (there's a lot to be said for simplicity!).

Having said all of that, however, we're already running into problems that are going to be easily solved by containers, namely the availability of older distros. CentOS 5 is a good example—it's critical to Node 4 support but none of our providers offer them anymore (for good reason) so we're holding on to our existing infra and crossing out fingers that they don't become borked and need reprovisioning. There may be a day soon that we have to run CentOS 5 in a container just to continue support.

We're already running some containers in our infra, https://ci.nodejs.org/job/node-test-commit-linux-containered/ has some. All of the Alpine images are in the same setup as is some generic Ubuntu 16.04 for Jenkins experimentation as required and I also threw in an Ubuntu 18.04 so we can start testing the newest Ubuntu LTS that's around the corner because it's going to be important that we have solid support there (another good use-case for containers because our infra providers are not the quickest at adopting new distro versions).

Happy to have more discussion about this, I don't want to sound like I'm putting up barriers but currently it really is much easier to focus on having solid Ansible scripts so we can re-image and/or re-provision machines and get them spun up with minimal manual intervention.

**Comment by MylesBorins** [comment]
@rvagg maybe we should spin up another issue to discuss.

I'd be more than happy to see if we can get SRE resources to help us figure out an architecture for this that is manageable, and also can look into getting free gcp resources if our infrastructure can help support this.

We have about 30 spin up for VMs, that can be spun from base images... so perhaps that is an option

**Comment by rvagg** [comment]
👍 open a new issue and pull in any folks you have access to over there that may be able to propose how such resources could be integrated with what we have and we can pull in other build folks as required

**Comment by MylesBorins** [comment]
The 30 was referring to spin up time for VMs

30 seconds

Opening another issue tomorrow 😃
