### ISSUE TITLE
No nightly builds?

### ISSUE THREAD

**Issue by kfarnung** [nodejs/build#1141]
It looks like the nightly builds stopped releasing after the 2/17 build:

https://nodejs.org/download/nightly/

Looking at the node-chakracore nightly job it seems like all legs are stuck in the `(pending—Waiting for next available executor on vs2017-x64)` state.

/cc @joaocgreis

**Comment by joaocgreis** [comment]
This was all because the Jenkins queue was blocked. I removed the `pi1` job that was blocking the queue. The `node-chakracore` job that was started a few hours ago resumed immediately, and I started a rebuild of the last node nightly.

There was a release `pi1` job (3017) that was running for 4 days without any progress, the parent `iojs+release` job was aborted (automatically?) but the subjob still showed as running. Also, there was a pending `pi1` job on the main `Build Queue`, when I aborted it other items in the queue started running. I don't know exactly what causes this bug in Jenkins, but I've seen this pattern at least another time: running subjobs belonging to a parent job that was aborted, and entries on the bottom of the queue (actually first position?) blocking it, that show as having been there for more than 24h.

I don't know if there's anything we can do to fix this in Jenkins and the nightlies are fixed, so I'll close this. But it's probably worth opening a issue if anyone has an idea of how to go forward to make this not happen again.

**Comment by kfarnung** [comment]
Thanks @joaocgreis!

**Comment by joaocgreis** [comment]
@mhdawson looks like the new build is going the same way, just blocked at the beginning. It is running on the Pi that you host, can you take a look? (Adding it to the inventory would be great, if you find the time, I know it's not straightforward because of the jump host.)

@rvagg the one that is hosted by you has been red for a few builds (Jenkins error, might be memory full - but not blocking). I couldn't find anything wrong with it, perhaps the SD card when it's under stress? The swap file is in the SD card, I guess it might not help.

**Comment by rvagg** [comment]
I was just talking about this on IRC, here it is:

> rvagg: mylesborins: I've started a second release build https://ci-release.nodejs.org/job/iojs+release/3033/ and cancelled most of the builders leaving the pi1. Your build picked the mhdawson Pi which has been successfully building for some time, it just hangs. I've marked it offline for now and the 3033 build should spit out a binary for you (eventually).
> rvagg: ok, so it turns out the current version of iojs+build is ignoring $JOBS in many of the cases ... that's annoying cause I've tried to force JOBS=1 for the Pi's to stop overload but they've been running at a fixed JOBS=2
> rvagg: so I've fixed it all up to respect JOBS and if JOBS isn't set then use 2
> rvagg: could explain some of the release Pi instability I've been so frustrated about
