### ISSUE TITLE
better reporting for jenkins pipelines

### ISSUE THREAD

**Issue by mcollina** [nodejs/build#1166]
We are using pipelines for readable-stream and string-decoder, however their reporting is not great, specifically in case of failures it's very hard to know what has failed and with which variables.
Having a report on the # on test runs for machines would also be ok, because I had some cases where no test were run due to some misconfiguration.

Let me know if it's something I can set up myself and in that case let me know how.

**Comment by rvagg** [comment]
Being actively discussed in https://github.com/nodejs/build/pull/1156#issuecomment-369113512

I'm the Jenkins pipelines scold of the team it seems, everyone else seems to be enthusiastic about them. While I like the idea that we can get our Jenkins logic into GitHub, and being able to lay out the logic in Groovy certainly is a lot of fun, they are atrocious for end users. To me it seems that they are widely liked by Jenkins administrators but are a huge step backward for consumers of Jenkins, and in our case that matters a lot since our user base is quite wide and varied. Perhaps this is because the majority use of Jenkins is by Jenkins administrators who usually don't need to expose the full gore of Jenkins to an organisation like we are doing.

I'm still waiting to be convinced that pipelines _aren't_ going to make our lives more difficult when considering the burden on the user. I've been hoping for someone around here to put together an epic pipeline job that makes it all _click_.

**Comment by gibfahn** [comment]
So I totally agree that there's a big problem with the graphical output of pipelines for end users, but if you want details you're already looking at the console log, so at that point we can definitely do better (pipelines are just groovy scripts, so there's no reason we can't have clear error messages and validate args).

@mcollina if you could post some links to specific issues you hit I can take a look.

**Comment by mcollina** [comment]
Providing clickable links and visual feedbacks for broken builds would help. To check a specific build, one has to click on the build, open the output, look for "failure", click on the the https://ci.nodejs.org/job/string_decoder-continuous-integration job, and then open up the specific run. This is very tedious to do for all the supported environment/node versions.
Providing links to the actual runs would be extremely handy.
