### ISSUE TITLE
release-devrus_mhdawson-debian7-arm_pi1p-1

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1176]
@rvagg I just see this comment:

Disconnected by rvagg : doesn't build

any more info as to what was failing so I can take a look at what was wrong ? 

If not I guess I'll restart and run a job to see.

**Comment by rvagg** [comment]
Yeah, there was a period of a few days where the history showed stalled jobs. It would try and start and just hang at the initial step and stay there for hours and days, messing up Jenkins in the process and of course not giving us releases. No idea what the problem is. I pinged you on IRC about it but I guess you were on vacation.

**Comment by mhdawson** [comment]
I'll see if its the nfs mount, which I think has been one of the issues in the past

**Comment by mhdawson** [comment]
Yes nfs mount was out, rebooting now.

**Comment by mhdawson** [comment]
Seems to be building ok now
