### ISSUE TITLE
Release infrastructure post mortem

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#1212]
We have had to do two separate re-releases in the last week due to infrastructure issues. I would like us to conduct a blameless port-mortem and create action items that can help us avoid this happening again.

**Comment by MylesBorins** [comment]
Here is a link to the MSI job which still completed green even though scp failed

https://ci-release.nodejs.org/job/iojs+release/3276/nodes=vs2015-x64/console

**Comment by MylesBorins** [comment]
Adding context from @rvagg in https://github.com/nodejs/build/issues/1211#issuecomment-378813556

>the logs don't show it unfortunately but I'm assuming that ssh node-www touch .../node-v9.11.0-x64.msi.done was performed after the scp failed. Not what I would have expected.
>
>I think we're going to need a @nodejs/platform-windows expert to have a look at https://github.com/nodejs/node/blob/master/vcbuild.bat#L371 and come up with a strategy to make the batch file fail if one of these commands fail, the whole point of the .done is to signal that the file upload is complete.

**Comment by rvagg** [comment]
I've been pondering what kind of post-staging / pre-promotion checks we could build, I think it's clear that we need _something_. The main problem is that these assets vary so much and may not even be possible to properly inspect on a single platform (i.e. Linux). Here's some options:

1. Come up with a way to inspect all assets on Linux and just do it on the staging server, perhaps it's possible to use Linux tools to pull apart a .msi, .pkg, and others and do some basic sanity checking. Maybe we can come up with a way to assert that (a) the files are unpackable, (b) contain what looks like a roughly good set of files and (c) has some important files in the right form, perhaps even going so far as to inspect signing of Windows and macOS binaries?
2. Build a job on ci-release that does this all for us since we have the hardware available there and they all have access to the files. Perhaps a job that takes a version number that's in staging, each node pulls its relevant files and does some local checks on them (like in 1), could even go so far as to install them (may not be a good idea).
3. Build it right in to the iojs+release process itself. I don't really relish the thought of having to bulk up Makefile and vcbuild.bat even more to make them do this so perhaps it's something we script in nodejs/build. After pushing the assets to staging, the same nodes then pull them back down again and assert that what was pulled down is intact and contains what they should do (doing the kinds of checks as in 1)

**Comment by refack** [comment]
The least we could do in order to prevent _this_ exact scenario from rehappening is patch vcbuild - https://github.com/nodejs/node/pull/19833

* In the wider `vcbuild` context, QAing it is very hard, and the release-only code in it has been proportionally much less field tested. I had an idea a while ago to create a mock environment to run `vcbuild` in (where all external tools are null tools), and just check it's output, but time, and energy etc...

* As for @rvagg's suggestions: for MSI files `7z` on linux can be used to check validity, so that could be done in a dedicated CI machine:
```
> refael@refaelux:/mnt/d/refael/Downloads$ 7z t node-v9.10.1-x64.msi

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,4 CPUs)

Processing archive: node-v9.10.1-x64.msi

Testing     fil0004B9A1EE9558DFB883B33869725A95
.
.
.
Testing     filFFDD02AC536A2E91C35D4EF78E31005E
Testing     node.exe
Testing     node_etw_provider.man
Testing     node_perfctr_provider_man
Testing     nodevars.bat
Testing     npm.rc

Everything is Ok

Files: 4960
Size:       44177061
Compressed: 16572416
```

**Comment by refack** [comment]
P.P.P.S. we already have a `validate-downloads` job - https://ci.nodejs.org/job/validate-downloads/
that runs https://github.com/nodejs/build/blob/master/jenkins/download-test.sh

/CC @gdams
