### ISSUE TITLE
State of Ansible

### ISSUE THREAD

**Issue by maclover7** [nodejs/build#1277]
As noted in https://github.com/nodejs/build/issues/1272#issuecomment-390502218, would be ideal to get a current sense of a) the transition from `setup` to `ansible`, b) usability of the new scripts and how people feel about running them as well as making changes

**Comment by maclover7** [comment]
Here's what I've been able to gather and summarize from current/past happenings:

**No work:**
`aix61`
`armv7-wheezy`
`centos5`
`centos6`
`debian-wheezy-gcc`
`osx`
`raspberry-pi`
`windows`
`www`

**PR Open:**
`github-bot`
`ubuntu14.04`

**Completed:**
`centos7`
`containers`
`cross-compiler`
`debian8`
`fedora20`
`fedora21`
`fedora22`
`freebsd`
`linter`
`rhel72-linuxonecc`
`smartos`
`ubuntu12.04`
`ubuntu1604`

**Comment by gdams** [comment]
@maclover7 macOS playbooks were created in https://github.com/nodejs/build/pull/971

**Comment by maclover7** [comment]
@gdams Yep, but looks like `setup/osx` wasn't removed -- is that safe to do now?

**Comment by gdams** [comment]
I think so, I've pulled all of the useful stuff out of that playbook already

**Comment by maclover7** [comment]
@gdams Ok -- can you run the new playbook on all OSX machines, confirm everything looks okay, and then remove `setup/osx` if everything works good?

**Comment by rvagg** [comment]
* centos5: I think we can retire it all, Node 4's demise takes out our remaining need for it and it was getting crazy complicated keeping it alive (see non-ansible-configuration-notes.md details on git in centos5 for example)
* debian-wheezy-gcc: can disappear, not used and not useful anymore
* www: too big a job to migrate and I'm not convinced there's utility in migrating it since it's really just a reflection of reality and preparation for emergencies. If it needs to be relocated to clean out "setup" then that's fine by me.
* armv7-wheezy: _"new scripts do not work due to awk error here; can old scripts be removed?"_ what's this referring to @maclover7? it can be removed anyway, the armv7 machines this references are running Ubuntu 16.04 and doing everything in Docker now.
* osx: we have scripts? it's just docs and a few helpers isn't it? they're redundant now with the new osx work.
* windows: I'm pretty sure is out of date but I don't believe we have anything better so it's important for documentation purposes at a minimum

As I look in setup/ all I see that I care about retaining now are _windows_ and _www_. I'm not confident about _aix61_ and _github-bot_ but you've covered them here. The rest can go IMO, even the ansible-* stuff and other top-level files.

**Comment by jbergstroem** [comment]
Regarding the `www` transfer: I have a 1 year old local branch that started addressing it. I ran into something and will have to revisit what that was.

**Comment by joaocgreis** [comment]
`setup/windows` should work, provided https://github.com/nodejs/build/blob/master/doc/non-ansible-configuration-notes.md is followed first. However, it has proven to be brittle in the past (https://github.com/nodejs/build/pull/907), so I wouldn't be surprised if some small updates are needed because of changes in Ansible.

One notable thing missing is a script for Visual Studio 2017, I have a draft for that that needs some testing and I'll try to get it done soon.

I also plan to move the scripts to `ansible/`, probably will start by crating a new section in `create.yml` and then try to merge where possible. If someone else is working on this please let me know so we avoid duplicating the work. I'm also happy to help if there are questions.

**Comment by joaocgreis** [comment]
PR moving `setup/windows/` to `ansible/`: https://github.com/nodejs/build/pull/1383

**Comment by refack** [comment]
Seems like all that should be done has been done.
Thank you Jon for coordinating this.
Thanks to all for the effort.
