### ISSUE TITLE
Including Node.js Docker Image Builds in the Node.js Metrics Microsite

### ISSUE THREAD

**Issue by bnb** [nodejs/build#1289]
I was just looking at the [Metrics site](https://nodejs.org/metrics/) and I see it exclusively has the metrics for the downloads from the Node.js site itself.

I was _hoping_ y'all would be open to also including the metrics from the Docker WG, which currently boasts an incredible `277,697,169` image pulls. I'm not sure what it'd be like to interface with the Docker metrics, but it would be a very nice way to add even more value to the already incredible metrics site and also continue to recognize the work that the @nodejs/docker team does 🙌

**Comment by maclover7** [comment]
cc @rvagg

**Comment by SimenB** [comment]
Possibly blocked by https://github.com/docker/hub-feedback/issues/1047? Not sure if "total, ever" is super useful. Although I guess we could start fetching and storing the data on Node's side and pretend the current number is 0?

**Comment by sam-github** [comment]
Unless anyone has any objections (I don't), the real blocker here is need of someone to volunteer to PR support for this.

A bit of grepping makes it look like the tooling is ansible/www-standalone, specifically, ansible/www-standalone/tools/metrics

Are any of the posters above interested in doing the work?

**Comment by rvagg** [comment]
Some discussion of metrics also going on @ https://github.com/nodejs/TSC/issues/794, and some of the stalled work here: https://github.com/nodejs/build/pull/2025. For now the plan is to get the metrics generation happening off the main server and just publish them there, so we can treat it as its own thing for permissions purposes. That server could be used to collect metrics from elsewhere and integrate them, it just needs someone to do the work. If someone's particularly keen to get involved in this then let me know because I'm about to start getting @AshCripps up to speed on how it all works.
