### ISSUE TITLE
Requesting access to test-linuxonecc-rhel72-s390x-1

### ISSUE THREAD

**Issue by apapirovski** [nodejs/build#1291]
Hi there,

I would like to request access to one of the LinuxONE machines (`test-packetnet-ubuntu1604-x64-1` or similar), so that I can debug https://github.com/nodejs/node/issues/20907

Thanks and let me know what would be needed on my end. Also, my email is in the profile.

**Comment by refack** [comment]
You probably meen one of https://ci.nodejs.org/label/rhel72-s390x/ (test-packetnet-ubuntu1604-x64-1 is just a jenkins workspace that triggers the actual work)

Anyway +1 from me

**Comment by refack** [comment]
FYI you can spin your own up, for free during a trial period - https://developer.ibm.com/linuxone/

**Comment by maclover7** [comment]
LGTM

Would take care of this myself, but don't know how to... would be interested in learning how to do this from one of the infra admins

**Comment by apapirovski** [comment]
@refack thanks for the correction!

**Comment by gdams** [comment]
@apapirovski I would agree with @refack! Try and spin up a machine on https://developer.ibm.com/linuxone/ first and if you still need access to one of the CI machines then let us know

**Comment by Trott** [comment]
+1 

> Would take care of this myself, but don't know how to...

@maclover7 I pretty sure I know how to grant access (grab the user's public keys, in this case from https://github.com/apapirovski.keys, and put them in the `.ssh/authorized_keys` file for the user that we log in as via SSH on the machine), but the part I don't know is where to document that change so that we remember to undo it. Maybe we just leave this issue open and remove the keys when the issue is closed? Not sure what we've done in the past.

**Comment by refack** [comment]
> Maybe we just leave this issue open and remove the keys when the issue is closed?

Yep. Also move the ticket along in https://github.com/nodejs/build/projects/2#card-10173847

@apapirovski can you send me your public ssh key?

**Comment by apapirovski** [comment]
@Trott, @addaleax and I are handling this at the summit. Thanks for the help!
