### ISSUE TITLE
Request for elevated permissions

### ISSUE THREAD

**Issue by maclover7** [nodejs/build#1337]
(opening this now, so I don't forget, to continue discussion with @jbergstroem and @mhdawson from the last wg meeting)

Lately I have been one of the more active participants in the WG, and one of the only people keeping an eye on the `node-build` IRC channel. As a result of this, I am doing more and more of the WG's core tasks, however I often do not have sufficient permissions to actually perform them. Some recent situations I have personally encountered are:

- Getting ci.nodejs.org to successfully build and test security releases
- The web server has not rebuilt the site many times recently, and I have had to guide TSC members through the GitHub UI on how to get the site to update
- Release team members assume access to `ci-release.nodejs.org`, and need me to perform certain admin tasks
- Simplifying and extracting Jenkins job scripts

The WG projects I have been working on include trying to bring the Ansible refactor to a conclusion, triaging the issue tracker, Docker usage in test CI, and just generally keeping the wheels turning.

I'd like to request higher permissions, to complement the increased responsibility I have been taking on for the WG's business over the past several weeks/months.

**Comment by refack** [comment]
I would like to join this request.

As I see it there are several access points that _could_ be considered independently:
1. access to `www` infra
2. access to `github-bot` infra
3. access to `ci.nodejs.org` infra
4. access to `ci-release.nodejs.org` infra
5. access to `release` machines
6. admin access to `nodejs/node` and `nodejs/nodejs.org` GitHub Repos

Also /CC @nodejs/security

**Comment by joyeecheung** [comment]
If I understand correctly, the requests translate to:

1. Adding your public keys to `github-bot`, `release` and `infra` secrets folder
2. Giving you to admin access to `nodejs/node` and `nodejs/nodejs.org`

For 1 I think we'll need consensus from @nodejs/build and for 2 we will need consensus from @nodejs/tsc 

I am +1 to the requests FWIW, but it would good if the procedures can be documented as much as possible to make sure they can be passed on.

**Comment by phillipj** [comment]
+1 FWIW

More people knowing the github-bot with access to its server would be valuable. It usually means being an infra member, I'm just an exception that has been provided access to that server explicitly.

**Comment by maclover7** [comment]
@joyeecheung 

> If I understand correctly, the requests translate to:

For release, it would be running `dotgpg add` in the `build/release` directory of `nodejs-private/secrets` and adding me to the `nodejs/jenkins-release-admins team`

For infra, it would be again running `dotgpg add` in the `build/` and `build/infra` directories of `nodejs-private/secrets`, and then creating individual accounts (I'd have to be added to the Node.js "group") for each of the hosting providers

> consensus from @nodejs/tsc

Probably too late for today's TSC meeting, but I'm happy to attend next week's as an observer, or to answer questions about my request

**Comment by mcollina** [comment]
+1

**Comment by mhdawson** [comment]
Thanks for opening and starting the discussion with examples.  I like @refack's list of what could be considered independently.  @refack @maclover7 do you believe you need access to all of those or a subset?

**Comment by refack** [comment]
I believe that we need more active collaborators with access to all these point for the benefit the org. All of those points needed attention in the last couple of months.

If any item is considered "too risky" then the decision on that item can be deferred, this way we don't have an all or nothing situation.

**Comment by mhdawson** [comment]
+1 to greater coverage across the board.

**Comment by maclover7** [comment]
@mhdawson 

> do you believe you need access to all of those or a subset?

Part of the issue is that all of the machines within the various access groups (ex: test, release, infra) all use the same SSH key within that group. Without reconfiguring a lot of our existing stuff, this would make it hard to give out access in small bits, and also make it hard to keep track of who has access to what services.

The issues I have encountered seem to point to being added to the `infra` and `release` access groups, in order to be able to resolve them in the future.

> +1 to greater coverage across the board.

I've been trying to get the Ansible playbooks in the best state possible, and adding new docs about our Jenkins test cluster as much as I can. My hope is that this will lead to a less stress when trying to deal with issues.

**Comment by Trott** [comment]
I don't know exactly what's involved, but I am +100 to upgrading @maclover7 and @refack to more trusted levels of access in Build WG if it helps them be more effective. Both of them have been more active than anyone as far as I know in Build WG lately. No disrespect to awesome folks like @joaocgreis, @jbergstroem, @rvagg, and @mhdawson (and others--not a comprehensive list) but @maclover7 especially and @refack too probably pay more attention and do more than everyone else combined every single day to keep stuff from grinding to a halt. I cannot overstate how important their Build WG work is to the project.

In the past, I know one question asked before elevating privileges was "Does the person have an employer such that there will be consequences if they misbehave?" I wonder if recent experiences suggest that we might want to reconsider that criteria. I understand the motivation. But it's also true that Build WG hasn't been able to scale up with the rest of the project and it's causing problems for both the project at large and the Build WG membership in particular. I don't have a good counter-proposal, but I welcome thoughts/suggestions. I do think that @maclover7 and @refack have earned sufficient trust that this should be a no-brainer.

**Comment by mhdawson** [comment]
Adding @rvagg @joaocgreis and @gibfahn as well.

**Comment by jbergstroem** [comment]
I agree to adding more people to infra (and release; they were designed to be different for similar reasons, being able to help with releases versus core infra. Perhaps a side track could be to revisit what architecture/software should live where?) and after going through the commit, issue and pr logs I can only chime in with what others seem to agree on here.

While doing so it would also be great if we could get some kind of outlines going in terms of how we evaluate this criteria. As it was said in the last build meeting: "There _are_ people watching who has access to release machines".

**Comment by rvagg** [comment]
I want to make sure that while we're discussing this that we're clear on some of the challenges we have in opening up this stuff to a broader group and why there's friction in doing so.

We're talking about critical infrastructure that impacts on all aspects of security of our build pipeline and impacts on the relationships that we have carefully managed with infrastructure donors. We've always focused discussions about this on "trust" and "accountability". The unfortunate fact is that it's much easier to establish these two things with employees of companies that have things to loose, particularly the big guys. IBM makes that easy, as does Microsoft (and by proxy through Janea Systems). Individuals who work for those companies also have their employer to answer to and have legal contracts in place that hold them accountable so it's much more difficult to imagine a scenario where we have sever leakage or malicious action where there's isn't some kind of serious legal ramifications. So that covers Michael, Gibson (now at Apple so just as easy), and Joao.

I have NodeSource, although we're a smaller company, but I also basically started this whole infra thing (it was the key deliverable out of the node-forward effort and pre-dates even io.js and talk of a Foundation) and have built a large majority of what we have now and have been maintaining a lot of the relationships we have with sponsors. Johan is unaffiliated but also has a very long history here and a significant investment in doing the actual work.

So, when adding new people, we have to look very seriously at mitigating the risk of sharing core secrets (certs, etc.) of the technical project and also the relationships with sponsors that tend to need special care, or walking within not very well defined boundaries. I think we would very much like to add both @refack and @maclover7 and it's crystal clear that they are both dedicated to our infra and are technically very capable. But they're also unaffiliated and have no chain of accountability that would provide assurance for the project against malicious action beyond trust gained through action--not that that trust isn't significant. The connection of the trust placed in you by the project with your very employment serves as a very important piece of the puzzle. If I screw up, if I have some kind of flip-out and take down our infra or inject some malicious code into releases (trivially possible to do transparently with the kind of access we're talking about here, even with all our other checks in place and not even with _full_ access to key resources), then I suffer, not just from project blow-back but because it'd fall on my employer so I'd probably be out of a job and also be in for some legal action due to reputational damage.

So, please don't think we're dragging our heels on this because we want to protect some kind of special inner sanctum (it's not that glamorous and also kind of annoying having a small group with the knowledge & access), there's critical questions to be answered here that impact us all and those questions can't be simply answered by the kind of feels that we use across the rest of the project.

There may be a role here for the Foundation to help provide us with legal help in establishing a formal trust relationship, perhaps something we can sign. But given our history with being able to extract any legal help from the Foundation (for even trivial things like _can we leave a date off our copyright notices???_) I'm not really hopeful that they're going to be useful here in the slightest.

**Comment by refack** [comment]
> So, please don't think we're dragging our heels on this because we want to protect some kind of special inner sanctum...

I think that is clear, and I tried to reiterate that during the last WG meeting.  
An added point is that access to the release machines will add new members' identities to the audit trail of the node binaries.

> There may be a role here for the Foundation to help provide us with legal help in establishing a formal trust relationship, perhaps something we can sign.

IMHO that's a great idea 👍

**Comment by bnb** [comment]
cc @MylesBorins - I think you'd be interested in the last bit of @rvagg's comment above, RE: Foundation work.

**Comment by maclover7** [comment]
> But they're also unaffiliated and have no chain of accountability that would provide assurance for the project against malicious action beyond trust gained through action--not that that trust isn't significant.

I agree. As you mentioned with Foundation legal resources, I am happy to assist and try to setup mechanisms that create more accountability that helps to protect Node as a project. The ultimate issue we're dealing with is how to expand access to the essential assets of the project -- nodejs.org, release servers -- in a responsible way that properly safeguards them.

**Comment by maclover7** [comment]
This is squeezing us currently, there's an issue with the github-bot (in the "infra" machine group) that requires SSH access

**Comment by joyeecheung** [comment]
I am tagging the issue tsc-agenda to discuss at the next TSC meeting.

**Comment by mhdawson** [comment]
Based on the discussion I'll post the list from above:

**Comment by maclover7** [comment]
The two main things holding me back right now are access to the www server when website pushes aren't working and being a Jenkins admin on `ci-release.nodejs.org`

**Comment by refack** [comment]
IMHO this could be pushed to a week when @rvagg is available to present the reasoning behind the status quo.

**Comment by mhdawson** [comment]
@maclover7 are there issues for the work related to ci-release.nodejs.org?  I think I understand the www side just want to better understand where you've been pulled in on the ci-release.nodejs.org side.

**Comment by maclover7** [comment]
> @maclover7 are there issues for the work related to ci-release.nodejs.org?

@mhdawson During the security release issues, Refael was the only one around on IRC that is part of nodejs/jenkins-release-admins, so would be good to have more coverage there. Also, I'd like to work on a new job in the release CI that can let people retrigger deploys to nodejs.org, so doesn't have to escalate to pinging build folks.

**Comment by joyeecheung** [comment]
I opened https://github.com/nodejs/build/issues/1373 with a doodle and an agenda

**Comment by rvagg** [comment]
www is kind of the crown jewels, I'm hesitant support more relaxation on that one but I get that there are concerns about www deployment. I think there's an easy fix though, we can just expose the log of the webhook execution, nodejs.org/github-webhook.log or something, I don't believe there's anything protected there and that's all that's needed in order to fix any of the problems we've had in the past year or so with website updating.

**Comment by rvagg** [comment]
https://github.com/nodejs/build/pull/1376 should sort out primary www concerns, not sure why we didn't do this earlier

**Comment by MylesBorins** [comment]
@rvagg does the log make it easy to relaunch?

It sees like there is likely a script that could run the resets git to master and runs build would maybe be sufficient?

**Comment by rvagg** [comment]
@MylesBorins no, but a push to master will relaunch, we've never had a problem with that. The process is essentially a fresh clone of master, npm install and build then copy build assets into place. So we have a trigger to do a fresh build, we just don't have insight into what the build is doing. We've got a PaaS for the website but it's an entirely black box.

Of the hangups we've had with the website "not deploying", the two most recent were:

1. Disk full, logs made that obvious but nobody knew until someone hopped onto the server to figure out what was up. It obviously needed more expert action on the server when we figured it out.
2. Change in package.json build script (included `rsync` when that wasn't available in the Docker container). This was only fixable in the nodejs/nodejs.org repo and just required a new push to master (there were attempts of re-pushing to master in the hopes of making it work but it ran into the same problem and there was no insight until someone with server access looked at the logs).

**Comment by MylesBorins** [comment]
@rvagg great points Thank for explaining

**Comment by refack** [comment]
I would like to freeze this discussion until we figure out some policy regarding the __existing__ permission structure.

**Comment by mhdawson** [comment]
@maclover7 did we have issues with the release ci during the last security release?  I have access and was around syncing with Evan.  The main issue that I'm aware of was the issue with one of the new tests in the test CI which I helped investigate/resolved.  Either myself or Rod  are around for security releases to sync on the security announcement and are in nodejs/jenkins-release-admins.  Not that more coverage would not be good, just not sure if we have seen issues on that front.

**Comment by maclover7** [comment]
@mhdawson Trying to remember what the issue was with release CI, but can't off the top of my head (I _think_ something with the Pi docker machines, but IRC logs are probably helpful with this)

**Comment by Trott** [comment]
@maclover7 Is this being addressed in your opinion (via talks with @rvagg and activity in the Build WG) or should I set up a separate meeting specifically about this? (Hit me up offline on IRC or elsewhere if you'd rather not discuss in a public venue right now.)

**Comment by refack** [comment]
This issue was discussed yesterday at Build WG meeting (https://youtu.be/rzyqeVzHCCg?t=877). We tried to figure out how to improve the process while the current permission status is discussed.

AFAICT this could be removed from TSC agenda until the build WG (namly @rvagg) has some new recommendations.

**Comment by maclover7** [comment]
> @maclover7 Is this being addressed in your opinion (via talks with @rvagg and activity in the Build WG) or should I set up a separate meeting specifically about this?

@Trott From my perspective, this is slowly being addressed. Between all of the different Build/TSC tickets flying around, I think awareness of this particular issue (elevating Build WG member to be a maintainer for critical infrastructure) has certainly been raised, as well as other items facing the Build WG. To keep this short, I'd say that in the short term this issue is being resolved by people with access being more available, so it is probably okay to put this ticket to the side, at least for now.

However, in the medium-to-long term, we do need to re-evaluate who _has_ (and how that contrasts to who _should have/needs_) access to these systems, and that is probably worth having a separate meeting over, to discuss live with each other.

**Comment by sam-github** [comment]
Why is this on the build WG agenda still? It looks like @refack labelled it in June 2018, can we take it off, or figure out what needs discussion?
