### ISSUE TITLE
provision macos test runner with case sensitive filesystem

### ISSUE THREAD

**Issue by devsnek** [nodejs/build#1403]
its not unheard of for people to use case sensitive, and its getting more popular with the new apfs

motivation: https://github.com/nodejs/node/pull/20954

**Comment by devsnek** [comment]
@maclover7 i just know that case sensitivity is an option when formatting drives to APFS (and HFS+) which is presented in disk utility and during os upgrades in the UI. i don't know how that would plug into the build infra

**Comment by mhdawson** [comment]
@gdams, can you figure out what would need to change in our ansible template to enable Case Sensitivity?  We might want a variant that we can use to install 1 or more Case Sensitive instances.

**Comment by gibfahn** [comment]
@gdams while I agree it's not really something we want to manage with Ansible (and should be done on OS install instead), I guess it should technically be possible to reformat the disk, probably by partitioning the current disk, reformatting the partition, then copying everything over. It sounds a bit painful though.

I assume reformatting the disk you're currently running on sounds a bit dicey.

**Comment by devsnek** [comment]
you could just create one of those dynamically growing volumes formatted to case sensitive

**Comment by mhdawson** [comment]
I don't think we want to stand on our head to do it with ansible if it does not make sense. I like the idea from @devsnek where we create a new volume that is formatted appropriately, but if that is too hard through ansible then just creating instructions for the initial OS install probably makes sense.

**Comment by sam-github** [comment]
Closing as part of an OS X issue cleanup.

1. There has been no progress on this for 1.5 years
2. The motivating issue https://github.com/nodejs/node/pull/20954 appears to be a one-off, there have not been followon issues, either because the code is robust to case-sensitivity on OS X, or because so few are using those OS X install options that no one cares.
3. Running an entire set of 3 new test machines on our strained OS X architecture, especially ones that require custom FS formatting, strikes me as not worthwhile for such a fringe (and unrepeated) problem.

Closing for now, but if I'm wrong and someone is keen to try to provision a set of machines to address this, it can be reopened.

ATM, we don't have sufficient hardware resources to do this, though, not AFAICT.
