### ISSUE TITLE
job status: `node-test-commit-custom-suites` doesn't report success

### ISSUE THREAD

**Issue by refack** [nodejs/build#1408]
The new job that was added to the matrix did not report success to github.
1. There was no PSA that that `node-test-commit` was changed.
2. No collaborator reported the "no completion" issue. I see that as a bad sign of low trust in CI stability.

I [disabled status reporting for that job](https://ci.nodejs.org/job/node-test-commit-custom-suites/jobConfigHistory/showDiffFiles?timestamp1=2018-07-19_14-58-42&timestamp2=2018-07-22_10-51-42) since failure will anyway be reported through `node-test-commit`.

**Comment by maclover7** [comment]
> There was no PSA that that node-test-commit was changed.

Adding worker tests to `node-test-commit` was all discussed in the open on a build repo ticket, https://github.com/nodejs/build/issues/1318

> No collaborator reported the "no completion" issue. I see that as a bad sign of low trust in CI stability

There have been a lot of issues with github-bot in the last few days due to lingering bugs from upgrading a big dependency. A bunch of automation things have only been working intermittently, so I think that is also playing a role here (many nodejs/node PRs haven't had labels auto-applied, etc.)
