### ISSUE TITLE
incident: test-rackspace-freebsd10-x64-1 clogged with processes in D state

### ISSUE THREAD

**Issue by refack** [nodejs/build#1412]
https://ci.nodejs.org/computer/test-rackspace-freebsd10-x64-1/
```
USER    PID  %CPU %MEM     VSZ    RSS TT  STAT STARTED        TIME COMMAND           UID  PPID CPU PRI NI MWCHAN
iojs  53048   0.0  3.0  725408  61484  -  D    Sun11AM     0:04.10 npm (node)       1002 52992   0  52  0 zfs
```
Which in turn causes the linter job to never finish e.g. https://ci.nodejs.org/job/node-linter/314/ run for 1day 11hours until I aborted it.

My suggestion is to provision a new machine for the linter pool.
If anyone from @nodejs/platform-freebsd can help, PTAL.

**Comment by rvagg** [comment]
@nodejs/build I think we're going to have to let go of this machine and reduce our FreeBSD 10 footprint. I've been on this one trying to clean things up but processes hang. I thought maybe I'd rebuild from image but then discovered Rackspace has severely trimmed their base images, including dropping FreeBSD. Joyent have decreased their support for FreeBSD too, although we could still get VMs there. DigitalOcean is an option too. However, tbh, I find FreeBSD far too flaky to be using for linting and we really need to switch to Linux.

I started playing with doing this a while back but got stuck because Makefile's lint-ci is configured to assume FreeBSD (grr) and fixing it required changing all release lines and waiting for updates. https://github.com/nodejs/node/commit/c5928ab6314bb128fb709ace83e478a733e6795f got landed to do this, I haven't checked if there are backports to all lines yet but it needs to be (maybe I backported it!). But here's my proposal:

 * Bite the bullet and switch to using Ubuntu 16.04 for all Linting
 * Scale up out 16.04 presence so we don't make a bottleneck, probably just a couple more machines required
 * Scale back our FreeBSD to just 2 machines for both of 10 and 11
 * Ditch Rackspace FreeBSD

**Comment by refack** [comment]
👍 
As for the Makefile's shortcomings, as a stop gap we probably could reimplement that logic in the job's script.
As for more Ubuntu 16.04s, that's seems very appropriate as there has also been a slight increase in its usage by some specialized jobs (the worker test suite, the internet test suite, and v8-update suite)

**Comment by rvagg** [comment]
also, we could use this to expand our Docker footprint, we have plenty of ubuntu 16.04 based images already

**Comment by maclover7** [comment]
+1 to switching, only thing to note is that linter machines require `node` and `npm` to be installed globally, so that could complicate using them for other jobs

**Comment by mmarchini** [comment]
> +1 to switching, only thing to note is that linter machines require node and npm to be installed globally, so that could complicate using them for other jobs

Sounds like a good use case for Docker then :D

**Comment by rvagg** [comment]
`PATH=/home/iojs/linter-bin/ make lint-ci`

**Comment by refack** [comment]
Both our public freeBSD10s are offline, I temporarily removed that label from the matrix:
https://ci.nodejs.org/job/node-test-commit-freebsd/jobConfigHistory/showDiffFiles?timestamp1=2018-06-23_10-03-39&timestamp2=2018-08-01_12-04-59

**Comment by rvagg** [comment]
See #1441.

**Comment by refack** [comment]
Rebuilt. Ref https://github.com/nodejs/build/issues/1441#issuecomment-412328364
