### ISSUE TITLE
Wrong time on arm64 release machine?

### ISSUE THREAD

**Issue by targos** [nodejs/build#1414]
See https://nodejs.org/download/v8-canary/v11.0.0-v8-canary201807247c08774a29/

All files have a time around 13:xx except the linux-arm64 ones that have 21:52 and 21:54.

**Comment by refack** [comment]
/CC @nodejs/build-infra 

BTW, why do we use `scp -p`? I'd assume the time the file lands on the dist server should be the authoritative time...

**Comment by rvagg** [comment]
@refack the `-p` is/was for retaining group-writable permissions. This is important because they are uploaded as user `staging` but user `dist` is used for promotion. We use group perms to do the transfer. See the `chmod 664` in Makefile the line above.

Perhaps we could just extend the `touch` in Makefile and touch the file being uploaded as well as the .done. Then we'd be using the web server system time and not having to worry about build server times.
