### ISSUE TITLE
Auto resume failed builds once

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/build#1427]
What do you all think about auto resuming a broken build once? It would likely reduce the amount of manual work for the collaborators even further. Since it is only about specific broken build it should not increase the load significantly.

**Comment by maclover7** [comment]
I'm +1 in theory, only caveat is that when you resume a build it gets a new `node-test-pull-request` URL, so that would need to be communicated to the PR author somehow. I'm happy to review PRs to `github-bot` to make this happen

**Comment by refack** [comment]
There is (was) a plugin for that - https://github.com/jenkinsci/naginator-plugin
But it seems like it's not available anymore. We might be able to code this with Groovy...

**Comment by BridgeAR** [comment]
Push

**Comment by sam-github** [comment]
@BridgeAR Do you believe this to be possible? I wouldn't know where to start implementing it.

I worry that a lot of pulls fail fast because of linting or other non-infra reasons, so if there wasn't some kind of "resume only if jobs X or Y ran sucesfully, so there is a reasonable reason to assume that the other failed jobs are ephemeral infra failures" filter that re-running everything might cause a lot of CI build load for no gain.
