### ISSUE TITLE
Incident: Jenkins misconfiguration for arm-fanned

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#1432]
Tracked the build failures @MylesBorins was experiencing @ https://github.com/nodejs/node/pull/22184 to a misconfiguration in Jenkins:

<img width="485" alt="tmp_jenkins_env_inherit" src="https://user-images.githubusercontent.com/495647/43816468-5586113e-9b18-11e8-9160-b9d18265950e.png">

There's too much activity in the config history to figure out who is responsible for this. It could be me from the last time I removed arm-fanned from CI due to an extended outage and then perhaps I put it back in again wrong but I think the last time I had to do that was in May? But regardless of who, here's the problem: "Parameters from properties file" is essential because it's the mechanism that's used to make parameters flow all the way down to these sub-jobs. Without these parameters we get the default. So from whenever this was enacted, arm-fanned has been testing `master` for every job submitted to it. Great for ccache, not so great for getting confidence around our tests on ARM!

Fixed now, this is just FYI and FTR.

**Comment by refack** [comment]
1. FYI & FTR, it should be "safer" to use the `Disabled` checkbox to disable a job during an outage. Alternativly, if possible try using the `Restore old config` ![image](https://user-images.githubusercontent.com/96947/43847894-ba8655a8-9aff-11e8-97d8-4572bb9f61d8.png) button.
2. Seems like `node-test-commit-arm` was still disabled (after I disabled it on 2018-07-25 due to a packetnet outage 🤦‍♂️). I just now enabled it and testing that it hasn't rotted.
