### ISSUE TITLE
test-joyent-smartos17-x64-1 failing builds

### ISSUE THREAD

**Issue by joaocgreis** [nodejs/build#1439]
https://ci.nodejs.org/computer/test-joyent-smartos17-x64-1/

I've marked the machine as offline, it has been failing builds for a while: https://ci.nodejs.org/computer/test-joyent-smartos17-x64-1/builds

I have no access to investigate. @rvagg config history points to you as who created the machine, can you check if you can log in and if the test key is there?

**Comment by joyeecheung** [comment]
It seems to have trouble deleting files, e.g. https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos17-64/19379/consoleT

**Comment by rvagg** [comment]
Couldn't get into it with any key so I guess it's completely borked. I figured the best approach was to nuke it and rebuild a new one but even after removing it from our account it's giving me a "quota exceeded". So it seems we've been given a cap lower than our current running instances. @cjihrig do you know the right person to contact over there about this? I'm not sure who's working there any more.

**Comment by cjihrig** [comment]
@rvagg I'm not sure who your prior contact(s) were for this. Can you email me that information and I'll try to get it straightened out.

**Comment by rvagg** [comment]
Got it sorted! See https://github.com/nodejs/build/pull/1447 for PR to clean this up, and we have a test-joyent-smartos17-x64-1 back online.

Here's the summary:

1. Access to the machine was lost _because it was restarted_. As per the doc I've added in #1447, part of the Ansible process removes the connection to the SmartDC setup that allows SmartOS SSH authentication to look up keys in the Joyent database for the coven account. When I set up the SmartOS 17 machines I didn't take this into account and just set them up according to scripts and they've been working. I obviously forgot to add authorized_keys entries because access just worked and I guess I assumed it was all working automatically (doh!).
2. The removal of that config doesn't take effect until sshd restart or reboot. Unfortunately the sshd restart part of our Ansible scripts hasn't been working for SmartOS 17, so it's taken until reboot for it to take effect and for us to notice. I don't know when this particular one was rebooted but the second SmartOS 17 machine was still online so I could get in to it and fix up authorized_keys today so it's 👍.
3. The quota problem has been sorted out thanks to @cjihrig connecting with relevant folks over there. Apparently it was a simple configuration problem where the machine type I tried to deploy wasn't part of our quota descriptor. That's all been fixed up now (thanks Joyent!) and we're in the clear and I have a new machine deployed without problem ... and I've fixed authorized_keys too obviously.
