### ISSUE TITLE
Transfering ownership of the expressjs.com domain

### ISSUE THREAD

**Issue by rubys** [nodejs/build#1472]
See https://github.com/expressjs/discussions/issues/68 for context.  I have gotten the domain to be unlocked and I have the auth code needed to make the transfer happen.  I just need someone to transfer it to.

**Comment by rvagg** [comment]
In progress with the LF technical team, we'll let them handle the registrar end and then we'll deal with the DNS end after transfer (assuming zone file gets transferred intact and there's not a need for emergency reaction).

The goal here is to empower the Express team with management of their own domain and for now it makes sense to handle this via the Node Build WG since we have structures in place to enable this.

**Comment by rubys** [comment]
This is now complete.  Thanks!
