### ISSUE TITLE
Trial NewRelic server monitoring

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#150]
@wraithan suggested that the free offering that New Relic has for server monitoring may serve our basic needs and should be easy to spin up.

**Comment by Starefossen** [comment]
[This one](http://newrelic.com/server-monitoring) @rvagg ?

**Comment by rvagg** [comment]
looks like it, apparently it's available in the free offering and can do some basic alerting

**Comment by Starefossen** [comment]
Looks like someone has made an Ansible configuration for this as well https://github.com/Recras/ansible-newrelic

**Comment by bnoordhuis** [comment]
I don't want to be the overzealous OSS hippie of the group but I'd be happier with something less proprietary.

**Comment by rvagg** [comment]
the nice thing about using a SaaS for this is that it's yet another server that we have to monitor and we don't have to worry about monitoring the monitor

**Comment by bnoordhuis** [comment]
I understand the appeal from a management perspective but I don't like the stamp of approval for a specific vendor it implies.  We're an OSS project and we should stay as neutral - and open - as possible.

(Aside, I have similar misgivings about Hangouts and Uberconference but I can see how a fully OSS approach there would have a high barrier to entry for most.)

**Comment by wraithan** [comment]
Totally understand @bnoordhuis, mostly suggested it since it is free and just kinda there. It can help find things like our low disk issues and have some alerting that gets the system a bit more stable until a more OSS solution can be built/evaluated/installed. The convenient thing about the newrelic solution is that they are in the business of being as turnkey as possible, which means less configuration up front.

In other monitoring concerns... which ties node closer to newrelic so requires much more of a decision... newrelic has non-profit stuff, if node would like to be a part of that, I'm happy to put in. Then we could use the newrelic java monitoring on jenkins which can monitor the health of the process, as well as the newrelic node monitoring for any node stuff. That said, I 100% understand trying to stay as neutral as possible.

**Comment by jbergstroem** [comment]
How about making this issue slightly more neutral; have people suggest a provider and the rationale to why we should use them? I'm slightly `-1` to installing agents on all our clients -- would rather prefer a simple system that allows us to poll the json output from jenkins. The bottleneck is our master which should get slightly better treatment.

**Comment by jbergstroem** [comment]
To sum the current monitoring issues up:

1. our jenkins master has a disk full issue we need to both mitigate and have a look at. Also, if this guy dives we're in trouble.
2. some slaves has had issues as a result of git versions -- this may be outside of monitoring.
3. our windows slaves has had issues with disk which is suggested to be fixed by `vcbuild.bat clean` between runs.
4. jenkins clients has died in rare occasions as a result of trying to reconnect to master. Not sure why, but I've seen this ~10 times since I started working on clients. This causes the jenkins java process to exit.
5. jenkins clients hardware goes offline either temporarily or for a longer period of time due to various reasons.

(please add if I'm missing something)

**Comment by bnoordhuis** [comment]
I'd suggest something like cacti or ganglia.  One of the great things is that you can have a public dashboard, like http://ganglia.wikimedia.org/latest/.

If those are to enterprise-y to people's liking, it's easy to put something together with collectd or statsd + graphite.

They all require local agents but I don't think you can get away from that if you want detailed system information, like CPU and memory usage, number of processes, etc.  Jenkins' JSON API doesn't return any of that, AFAIK.

**Comment by jbergstroem** [comment]
@bnoordhuis I'm a big fan of collectd but it doesn't really solve the notification issue (the threshold stuff could be used but it would be hacky at best). I don't really care about cpu, disk or any other graphs, just knowing that jenkins and the host is working as intended. I think jenkins already gives us rudimentary information about the host should we want. Anyway – since I'm starting to understand the different wants here, I'm probably not the guy to drive this. I'm happy as long as stuff is up :smile:

**Comment by orangemocha** [comment]
I am neutral to using an enterprise-y solution vs OSS one. I mean, it would be nice to have an OSS tool so we could modify it ourselves but it's not like we have ever done that with Jenkins. So I am +1 for whatever gets the job done. New Relic certainly would and it's nice that it would be free.

I think basic server monitoring and a health dashboard would be useful.

**Comment by jbergstroem** [comment]
I'm pretty happy with the monitor that @Starefossen has been maintaining. I personally wouldn't log into a dashboard  just to look at graphs; there's enough pie charts on the Internet. Does anyone else want to proceed here? Suggesting we close until we see a specific need.

**Comment by maclover7** [comment]
ping -- what's the status here?

**Comment by rvagg** [comment]
meh, I think it's been dismissed. Worth noting that the monitoring that's been discussed here that we're apparently using _isn't_ actually working currently. We used to get updates to #node-build when workers were down, no more. Probably because of the whole crumb thing introduced into the Jenkins API that makes everything annoying.
