### ISSUE TITLE
arm: release worker centos7-arm64 uses GCC4.8

### ISSUE THREAD

**Issue by refack** [nodejs/build#1542]
Some new code was added in that exposed an stdlibc++4.8 bug that was fixed in 4.9
https://ci-release.nodejs.org/job/iojs+release/3855/nodes=centos7-arm64/
(Node minimal compiler has been gcc4.9 since node9)

/CC @nodejs/release @nodejs/build-infra

**Comment by refack** [comment]
As a result ATM we are not building nightlies for ARM7
e.g. https://ci-release.nodejs.org/job/iojs+release/3873/nodes=centos7-arm64/
And will probably fail for 11.x and maybe 10.x is one of several PR that require 4.9 get backported.
P.S. the test CI is setup all 4.9 so we will have now early indication.

/CC @jasnell @targos

**Comment by mhdawson** [comment]
I can run it, would just like @rvagg to confirm that he is comfortable that we just need to run the playbook.

**Comment by mhdawson** [comment]
In test I see that we have a number of  different types of machines:

centos7-arm64-gcc48
centos7-arm64-gcc6

Not sure which versions of the compiler are used for
debian7-docker-armv7
debian8-docker-armv7
ubuntu1604-arm64

From the building docs minimum levels are:

GCC 4.9.4 for 8.X and higher
GCC  4.8.5  for 6.X 

My key concern is that I think we may still need to build 6.x on 4.8.5 on the release machines

**Comment by refack** [comment]
> centos7-arm64-gcc48
> centos7-arm64-gcc6

AFAIK these are "virtual" tags that are used to select different version of devtoolset
gcc48 used the default devtoolset2
gcc6 does `. /opt/rh/devtoolset-6/enabl`

**Comment by mhdawson** [comment]
@gdams is looking at the ansible scripts to get on top of what compiler level is installed for centos7-arm64 based on the updated ansible scripts.

**Comment by mhdawson** [comment]
@refack good to know, but next question is if we have the equivalent for 4.9.4.  I can see test-packetnet-centos7-arm64-1 has those 2 tags but don't see any 4.9.4 equivalent.

**Comment by gdams** [comment]
so we are running [this](https://github.com/nodejs/build/blob/master/ansible/roles/gcc/tasks/main.yml) to add gcc 4.9.4 on rhel7.x, Maybe we need the same logic on Centos7.x?

**Comment by mhdawson** [comment]
I think that might have been for IBM platforms since we did not believe there as a version of the redhat developer toolset available.  It seems like there is a version on arm based on the tags and this in the ARM64 job in test

```bash
 if [[ "$nodes" =~ centos[67]-(arm)?64-gcc6 ]]; then
    exec_cmd=". /opt/rh/devtoolset-6/enable; $exec_cmd"
  fi
```

**Comment by gdams** [comment]
so the following are installed on centos7:

```yaml
  centos7: [
    'ccache,gcc-c++,devtoolset-6,sudo',
],
```

**Comment by mhdawson** [comment]
@gdams does the ansible script forcentOS ARM 64 ensure we have both devtoolset-6 as well as the 4.8.4 compiler?

**Comment by refack** [comment]
AFAIK devtoolset is backward and forward compatible (https://github.com/nodejs/build/pull/809#issuecomment-344239898), so I think that if we have gcc4.8 for node < 11 (status quo) and new gcc6 for >= we solved the issue.

**Comment by mhdawson** [comment]
I do think that the dev toolset is more compatible so what @refack says could be correct.

**Comment by mhdawson** [comment]
This is what is in the selector script

```
[ /centos[67]-(arm)?(64|32)-gcc48/, anyType,     gte(10) ],
[ /centos[67]-(arm)?(64|32)-gcc6/,  anyType,     lt(10)  ],
```

Current tag in release is centos7-arm64 which does not cause selection on either of those.

**Comment by mhdawson** [comment]
Not quite sure why 10 was chosen as the cutover above since the change is in fact between 6.x and 8.x

**Comment by mhdawson** [comment]
Comments in this issue https://github.com/nodejs/build/pull/1203 indicate Rod was concerned that installing the new dev toolset might affect existing builds.

**Comment by mhdawson** [comment]
It also adds some insight on why the switch might have been at 9 versus 8 (problems we'd seen on 8.x).

**Comment by mhdawson** [comment]
So what I'd like as next steps are:

1) Confirm that the ansible scripts would result in having both 4.8.4 and the dev toolset-6
2) Confirm that we are comfortable having both installed on the same machine (ie address/resolve any concerns from #1203).  An alternative might be adding a new machine in release. At this point I'd need @rvagg to comment if that was feasible.

In terms of risk/reward I think it's better not to have nightlies on ARM64 for a little while versus potentially breaking our 6.X and 8.X LTS releases.  Based on that I'd like to take the time so that we can answer the questions above and get input from @rvagg.

**Comment by mhdawson** [comment]
My preference is adding a new machine.  I'll look to see if it is documented how I could add a new machine.

**Comment by mhdawson** [comment]
@nodejs/build if people are ok with giving @gdams infra level access to at least the packet hosting infrastructure, we could probably get the new machines spun up more quickly.

**Comment by mhdawson** [comment]
In addition to steps from above, we probably also need to validate that release binaries built on devtoolset-6 run ok on a centos7 machine with the default 4.8 compiler.

**Comment by refack** [comment]
> @nodejs/build if people are ok with giving @gdams infra level access to at least the packet hosting infrastructure, we could probably get the new machines spun up more quickly.

I think this needs to be discussed in a wider context (no offence intended George).

**Comment by mhdawson** [comment]
I logged into the packet infra and when I go to add a new machine, none of the options are ARM.  Not sure we'd have the ok to add another one anyway as they are pretty big machines with 96 cores and 32G or RAM.

So I think its back to figuring if we are comfortable having both installed on the same machine. Would like input from @rvagg on that front.

**Comment by mhdawson** [comment]
Another option is using docker on the existing machine so we can add a new machine sharing the resources without the potential for messing up the release machine.  We'd probably have to prove that out in test first through.

**Comment by mhdawson** [comment]
@rvagg want to make sure this is still on your radar.

**Comment by rvagg** [comment]
Yeah, sorry, this is a big one that takes some brain space so I've not got to it quicker.

So here's what I'm thinking our core problem is: ci-release _doesn't_ have the gcc48/gcc6 label split, it's only got the one centos7-arm64 machine with a single label `centos7-arm64`, plus there's no logic in place to switch devtoolset based on version.

This is in ci for node-test-commit-arm:

```bash
  if [[ "$nodes" =~ centos[67]-(arm)?64-gcc6 ]]; then
    exec_cmd=". /opt/rh/devtoolset-6/enable; $exec_cmd"
  fi
```

Our VersionSelectorScript.groovy has:

```groovy
  [ /centos[67]-(arm)?(64|32)-gcc48/, anyType,     gte(10) ],
  [ /centos[67]-(arm)?(64|32)-gcc6/,  anyType,     lt(10)  ],
```

So on ci, it's selecting gcc6 for >=10 and that's working fine so we have all green.

On ci-release, the version selector has no impact on arm64 because the label `centos7-arm64` doesn't feature at all. So we're using the default devtoolset (2), i.e. gcc 4.8.

So, given that, here's my proposed solution:

1. Introduce the gcc48/gcc6 labelling on ci-release
2. Introduce the devtoolset-6 invoker script (above) in the ci-release iojs+release script for linux-gnu (it's already specific enough to only invoke for arm64)

Then, optionally, on the next Node 10 and 11 release announcements, we _could_ state that we've switched build environment for ARM64 so upgrades should proceed with caution. However, as we've already discovered, Red Hat are doing funky stuff with devtoolset such that it doesn't appear to have an impact on the ability of the binaries to run on library level of the system they are built on. So systems with libc (and libstdc++, I _think_) versions of at least as new as Cent OS 7 should be fine. So we could just cross our fingers and hope nobody is impacted. The usage level of ARM64 is pretty low (one of my next jobs is to get the download numbers working again, so I don't have current numbers).

How does that sound @refack, @mhdawson, @gdams?

**Comment by refack** [comment]
> * Introduce the gcc48/gcc6 labelling on ci-release
> * Introduce the devtoolset-6 invoker script (above) in the ci-release iojs+release script for linux-gnu (it's already specific enough to only invoke for arm64)

Sound great. It works on the public CI 💯

**Comment by refack** [comment]
Aside: we have [explicit guarantee form glibc fork](https://github.com/nodejs/build/pull/809#issuecomment-339989585), that `devtoolset-6` is backwards and forwards ABI compatible. So the steps suggested are us being triple safe.

**Comment by rvagg** [comment]
done, last nightly rebuilt all green https://nodejs.org/download/nightly/v12.0.0-nightly201811153212f77ac6/

running test builds for 10, 8 and 6 now just to make sure it's doing the right thing.
