### ISSUE TITLE
windows: have a machine run tests in an elevated env

### ISSUE THREAD

**Issue by refack** [nodejs/build#1546]
Refs: https://github.com/nodejs/node/pull/23691
Refs: https://github.com/nodejs/node/issues/23596

**Comment by joaocgreis** [comment]
Windows machines already run tests in an elevated environment, exactly because of this.

What happened with `test-require-symlink` was that the link was actually created and some programs like Node and Git Bash were actually able to use it. However, on Windows Explorer it appears as a useless `.symlink` file, suggested it was never meant to be used that way.

What probably broke the test was some recent Windows update. Node stopped being able to read the link, and the test started failing. We didn't see this in CI because we use Windows 10 Long Term Support Channel. I will see if we can use a different Windows 10 edition in CI to get more frequent updates.

**Comment by joaocgreis** [comment]
The test was fixed by https://github.com/nodejs/node/pull/23691 and the general case by https://github.com/nodejs/node/pull/23724.
