### ISSUE TITLE
Request for build WG availability for Nov 27th security release

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#1586]
A set of security releases is planned for [Nov 27th](https://nodejs.org/en/blog/vulnerability/november-2018-security-releases). @nodejs/build, please be available to help out in case of problems, see below.

From https://nodejs.org/en/blog/vulnerability/november-2018-security-releases/:

    One week in advance open an issue in the build working repository              
    with a notification of the date for the security release.  Use this            
    issue to co-ordinate with the build team to ensure there will                  
    be coverage/availability of build team resources the day of the                
    release. Those who volunteer from the build WG should be available             
    in node-build during the release in case they are needed by the                
    individual doing the release.

@rvagg and @MylesBorins have volunteered to do the releases

**Comment by mmarchini** [comment]
What is the time window? (with timezone information, since Build WG members are distributed around the globe)

**Comment by refack** [comment]
I could be available, but since @rvagg is involved, I think we are covered.
Thanks for the heads-up @sam-github.

**Comment by rvagg** [comment]
So we should probably start locking down CI from the weekend. I'll put up an issue soon to propose timing. Actual release timing is "UTC" so I suspect I'll be working on releases during the day of the 27th my time, which is ahead of UTC. In the past I've prepared them the day before and pulled the trigger when I get up the next morning, which would be mid-afternoon US time. So that'd be quite late 27th UTC.

**Comment by Trott** [comment]
Seems like this should be closed. Obviously, re-open if I'm wrong!
