### ISSUE TITLE
citgm-smoker-pipeline does not propagate machines to citgm-smoker-nobuild

### ISSUE THREAD

**Issue by targos** [nodejs/build#1638]
For example, I executed: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/54/parameters/
I was expecting the jobs to only run on Windows, but they ran on all platforms.

I it possible to change [citgm-smoker-pipeline](https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/build?delay=0sec) to use a list of checkboxes for the machines, like we have in [citgm-smoker-nobuild](https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/build?delay=0sec)?

**Comment by targos** [comment]
@nodejs/citgm-admins

**Comment by richardlau** [comment]
re. checkboxes -- probably not easily. The checkboxes on `citgm-smoker-nobuild` are a [Matrix Combinations Parameter](https://wiki.jenkins.io/display/JENKINS/Matrix+Combinations+Plugin) and get their values from the `nodes` axis in the same job. This axis isn't known to the pipeline (the pipeline itself doesn't spread out over platforms and has no need to).

What does seem to be a problem is that in the pipeline we have a `MACHINES` parameter which is a string parameter that gets passed to `citgm-smoker-nobuild` but because it is of a different type it doesn't get interpreted as a matrix combination. 

I'll look into whether we can convert the `MACHINES` parameter to the correct type in the pipeline before it's passed to the `citgm-smoker-nobuild` job. If we can do that then we could possibly add a choice parameter to the pipeline and manually duplicate the list of platforms (but I'm a little reluctant to introduce something we'd need to manually keep in sync).
