### ISSUE TITLE
Eliminate checkpoint at the end of tests in Jenkins

### ISSUE THREAD

**Issue by joaocgreis** [nodejs/build#165]
After running all the tests, Jenkins test jobs block until the previous job is complete. As seen on the output of [job 277](https://jenkins-iojs.nodesource.com/job/node-test-commit-arm/nodes=pi1-raspbian-wheezy/277/console):
```
Publish TAP Results is waiting for a checkpoint on node-test-commit-arm » pi1-raspbian-wheezy #276
```

It this case, a previous job ([273](https://jenkins-iojs.nodesource.com/job/node-test-commit-arm/273/nodes=pi1-raspbian-wheezy/)) was compiling and for some reason ccache did not seem to help. It took 9h35m, and jobs started afterwards had to wait for it to finish before they could publish the results.

I don't know why this checkpoint is there, the only reason I can think of is to display the comparison in the TAP output, such as `TAP Test Results (2 failures / +2)`.

So,
1. Is this the only reason for this checkpoint?
2. Is it consensual that this is useless for our use case?
3. Is there a way to eliminate it?

**Comment by orangemocha** [comment]
For things like our jobs that test and land pull requests, it's certainly useless. Computing the delta in failures between different PRs, and across multiple branches doesn't add a lot of value. The failure delta might make more sense in more traditional type of CI jobs that run periodically on the same branch. In that category we currently have only node-daily-master. But if the side effect is that a job needs to block on other runs just to report the results, I am definitely in favor of removing that feature.

**Comment by orangemocha** [comment]
It looks like we are going to have to modify the TAP plugin: https://issues.jenkins-ci.org/browse/JENKINS-29650

**Comment by orangemocha** [comment]
Also relevant: https://issues.jenkins-ci.org/browse/JENKINS-9913

**Comment by jbergstroem** [comment]
@orangemocha how do you suggest we proceed here? Doesn't look like upstream jenkins/tap plugin is moving forward anytime soon.

**Comment by orangemocha** [comment]
- [ ] Read https://issues.jenkins-ci.org/browse/JENKINS-9913 well to see if there is a better solution than the following steps
- [ ] Learn how to build Jenkins plugins
- [ ] Build the Jenkins [TAP plugin](https://github.com/jenkinsci/tap-plugin), give it a different ID so that our build can be used alternatively to the existing one
- [ ] Try uploading our built plugin at https://jenkins-iojs.nodesource.com/pluginManager/advanced (Upload Plugin).
- [ ] Test a our plugin with a clone of of one of the test jobs, e.g. node-test-commit-unix
- [ ] Fix checkpoint issue by modifying plug-in code. Hopefully something like https://github.com/jenkinsci/slack-plugin/commit/832e7b50028ca086dd49311ce454e7a19c9a3af9
Test again in our Jenkins
- [ ] Provided it works, update all our node-test-commit-* jobs to use the new plugin instead of the TAP plugin, making sure all configuration for it is the same
- [ ] Open a pull request to https://github.com/jenkinsci/tap-plugin with the fix
- [ ] When the fix gets accepted and released, revert to the official plug-in

**Comment by Trott** [comment]
Closing as this has been inactive for over a year and I believe we intend to move off the TAP plugin. Feel free to re-open or comment if I am mistaken to close this.
