### ISSUE TITLE
consistent failures on git-nodesource-update-reference

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#1650]
```
remote: Compressing objects: 100% (70/70), done.        
14:18:53 error: file write error: Bad file descriptor
14:18:53 fatal: unable to write sha1 file
14:18:53 fatal: unpack-objects failed
14:18:54 debug1: client_input_channel_req: channel 0 rtype exit-signal reply 0
14:18:54 debug1: channel 0: free: client-session, nchannels 1
14:18:55 Build step 'Execute shell' marked build as failure
14:18:56 Notifying upstream projects of job completion
14:18:56 Finished: FAILURE
```

Seeing this on and off failing inconsistently across different branches

https://ci.nodejs.org/job/git-nodesource-update-reference/

**Comment by Trott** [comment]
NFS, maybe?  Won't @-mention because it's the holiday season and all and people don't need the pings, but would normally try pinging rvagg or joaocgreis.

Might removing arm-fanned from the test suite be a reasonable thing to do for now?

**Comment by joaocgreis** [comment]
This appears to be only an issue with `test-requireio_securogroup-debian9-arm64_pi3-1`. It's running https://ci.nodejs.org/view/All/job/git-clean-rpi/366/label=test-requireio_securogroup-debian9-arm64_pi3-1/ now, I'll see if it's fixed after or mark it as offline while I investigate.

**Comment by joaocgreis** [comment]
NFS seemed to be mounted and working well. Rebooted the host, but it didn't come back and is currently inaccessible. @rvagg can you take a look?

**Comment by rvagg** [comment]
Got 3 offline machines back on, including test-requireio_securogroup-debian9-arm64_pi3-1. It's not the first time this particular machine has had problems so it's probably going to need some watching.

FYI I still have test-requireio_davglass-debian9-armv6l_pi1p-1 test-requireio_piccoloaiutante-debian9-arm64_pi3-1 offline (have been offline for a few months) because they need some more hands-on hardware work.
