### ISSUE TITLE
FYI: Windows 7 end-of-extended-support to be 2020-01-14

### ISSUE THREAD

**Issue by refack** [nodejs/build#1663]
Refs: https://support.microsoft.com/en-us/help/4487594
Refs: https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet#section-2

Microsoft has announced that on January 14, 2020 it will end it's support for Windows 7 and Windows Server 2008 R2 (`WINVER === 0x0601`).

Should we recommend that node12 minimal supported version should be Windows8.1/Server2012R2 (`WINVER === 0x0603`)?

/CC @nodejs/platform-windows @joaocgreis

**Comment by seishun** [comment]
Time flies...
Node.js 12 EOL is April 2022, so not bumping the minimum supported version would result in supporting an unsupported OS for over 2 years.

**Comment by mhdawson** [comment]
+1 for moving the supported versions to  Windows8.1/Server2012R2

**Comment by gdams** [comment]
+1 for moving the supported versions to Windows8.1/Server2012R2

**Comment by joaocgreis** [comment]
Sorry for the late reply, I've been away with limited access. 

We already have this policy in `BUILDING.md`: "The community does not build or test against end-of-life distributions (EoL)". I believe this is what should take precedence, or we'd never support anything like non-lts Ubuntu. We should remove Windows 7/2008R2 only when it reaches the end of support, pending a discussion closer to the time (we might want to support it longer, if we have access to extended support or the date is extended).

The only thing we have to consider when starting a new major version is the release machines we use for it and the compatibility level they provide. The Windows 2012R2 release machines we use are good for v12, but we'll have to review for v14. This is not a big issue for Windows anyway, but has proven to be for Unix because of supported libc and kernel versions.
