### ISSUE TITLE
z/os: threadpool_multiple_event_loops failure

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1685]
Seems to be failing since ~ 5 Feb

https://ci.nodejs.org/job/libuv-test-commit-zos/nodes=zos-s390x/1336/console
```bash
ok 287 - threadpool_cancel_work
not ok 288 - threadpool_multiple_event_loops
# timeout
# Output from process `threadpool_multiple_event_loops`:
# CEE5205S The signal SIGTERM was received.
```

**Comment by miladfarca** [comment]
```
getaddrinfo_concurrent
threadpool_multiple_event_loops
```
`threadpool_multiple_event_loops` is calling `getaddrinfo_concurrent` as a separate job which cause it to also timeout.

`getaddrinfo_concurrent` is making a `getaddrinfo` system call which timeout at times. The reason is, system call is being made with `locahost` and OS might be trying to resolve it to an IP address.
```
 64   r = uv_getaddrinfo(req->loop,
 65                      &req->handle,
 66                      getaddrinfo_cb,
 67                      "localhost",
```
changing `localhost` to `127.0.0.1` on both test cases and rerunning them fixed the issue however, calling localhost should be equivalent to calling 127.0.0.1. I will send a note to the marist IT team to discuss the issue first.

**Comment by miladfarca** [comment]
`libuv-test-commit-aix` status is back to normal

**Comment by miladfarca** [comment]
Issue has been fixed on zOS.

**Comment by mhdawson** [comment]
Recent runs have passed, closing
