### ISSUE TITLE
Partially increase storage time of CI results

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/build#1692]
It would be great if the storage time of let's say at least CITGM could be increased to four weeks instead of a single week. We do not run them too often, so it should hopefully not require that much additional storage.

Would it require a lot of space to also store regular CIs longer? Especially CIs which require a long run time would benefit from being stored longer.

**Comment by refack** [comment]
I'll look into it.
But. Master moves quickly, so results get stale. What I used to do what copy&paste the gist to some spreadsheet, just as a reference.

Refs: https://github.com/nodejs/wiki-archive/blob/master/CITGM-results-table.md

**Comment by mhdawson** [comment]
We did have a longer retention period at one point. It was reduced due to space issues.  Having said that I often find results are gone when you need then.

**Comment by BridgeAR** [comment]
Push

**Comment by rvagg** [comment]
Yeah, we should probably give it a try. There's two reasons it's so tight a timeframe:

1. Storage - logs take up a ton of space and it builds really quickly
2. Speed - this is the bigger issue and the main reason we started trimming in the first place. Jenkins has a bad caching habit, it'll load job info into memory and keep it all around. Our logs and test results end up in the same blob. This caused severe slowdowns and timeouts that we only fixed by aggressively trimming. The whole test.tap and tap2json work was part of offloading some of this data out of the primary build bundle but I don't know if we really made much progress. Moving to `V=` builds would also be nice to trim logs, but there's been some pushback in doing that because some people want to see full compile commands.
