### ISSUE TITLE
Add centos7 PPCle machines

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1705]
If possible we'd like to build on Centos76  for PPC now that centos is available at OSU.  Starting with using them for 12.x and above and then seeing if we can use them for older releases as well.

- [x]  Add 2 test centos machines (test-osuosl-centos7-ppc64-le-1, test-osuosl-centos7-ppc64-le-2)
- [x]   Configure test machines with existing Ansible scripts if possible
- [x]  Validate that compiler is installed properly: devtoolset-6 installed
- [x] Update ansible scripts if necessary
- [x]  Update regression tests so that tests also run on centos76 for 12.x+, validate all passes
- [x]  Add 1 release centos machine (release-osuosl-centos7-ppc64-le-1)
- [X] update select-compiler.sh: select devtoolset-6 ONLY for centos7-ppc64le (if it's ubuntu, continue ot use gcc-6)
- [x]  Configure release machine with Ansible
- [x]  Add release machine to release CI.
- [x]  ... add additional required keys to release machine etc.
- [x] Do test builds with cloned release job where we build releases on centos7 for 13+ instead of unbuntu
- [x] Land PR for groovy selector to start doing releases on centos7 for 13+ instead of ubuntu
- [ ] Audit community test jobs to make sure we have added centos7 to all test jobs
- [ ] Identify next release, and plan switch over so that we get X days of nightly build/testing before next
      real release.
- [ ]  Land PR for groovy selector to start doing releases on centos7 for 12+ instead of ubuntu

**Comment by refack** [comment]
Is the plan to (if all goes well) use there and retire the `ubuntu14-ppc64-le` workers?

**Comment by mhdawson** [comment]
@refack assuming we convince ourselves that older binaries still run on all target OS's (of which I'm hopeful) then yes but I don't want to rush that so my plan would be to do that slowly.

**Comment by sam-github** [comment]
@mhdawson Tried to tick off some of the items above, but only build-wg members can do that.

What are the "regression tests"?

**Comment by sam-github** [comment]
@refack You probably already know this, but for anyone else: ubuntu 14.04 is aging out of LTS soon, so yes, we want to move to centos7 because it's support horizon will last long enough for 12.x.

To replace the ubuntu14.04 with centos7 for < 12.x, I need to find gcc 4.8, and 4.9 (at least) for them, and I haven't had any luck with that yet. Worst case is we'll have to build them ourselves via ansible, which would be frustrating.

**Comment by mhdawson** [comment]
And to set expectations if we can/will retire ubuntu14.04 it will be after 12.x not before....

**Comment by sam-github** [comment]
- [x]  Add 2 test centos machines (test-osuosl-centos7-ppc64-le-1, test-osuosl-centos7-ppc64-le-2)
- [x]   Configure test machines with existing Ansible scripts if possible
- [x]  Validate that compiler is installed properly: devtoolset-6 installed
- [x] Update ansible scripts if necessary
- [ ]  Update regression tests so that tests also run on centos76 for 12.x+, validate all passes
- [x]  Add 1 release centos machine (release-osuosl-centos7-ppc64-le-1)
- [x]  Configure release machine with Ansible,
- [ ]   ... add additional required keys etc.
- [ ] Update selection script so that builds for 12.x and above use centos7 instead of ubuntu
- [ ] update select-compiler.sh:
  - [x] step 1, select devtoolset-6 ONLY for centos7-ppc64le (if it's ubuntu, continue ot use gcc-6)
  - [ ] step 2, remove the ubuntu special-case once the ubuntu machines are no longer used to build 12.x
- [ ] remove the previous config to run on both existing ubuntu and centos machines for 12.x +

**Comment by sam-github** [comment]
@mhdawson #1763 is ready for review. I am a bit fuzzy on the rollover plan, but I believe it reflects step-1, in my comment above.

I think the next step is to merge it (you have to do), then configure jenkins (you have to do).

Once ci is running on centos7, I can check the builds.

Once that is happening, is the next step that the groovy exclude script is changed so we *stop* building ubuntu-ppc64le for node >- 12.x? I guess that will be a new PR, I can do it.

**Comment by mhdawson** [comment]
I think the PR is ready to go but I think we should wait until after 12.x goes out next week to land it.  Will plan to look at that on Wednesday.

**Comment by richardlau** [comment]
@mhdawson @sam-github @AshCripps I think this has all been done now and can be closed?

**Comment by mhdawson** [comment]
@sam-github can you confirm and close.
