### ISSUE TITLE
cross-compiling for arm

### ISSUE THREAD

**Issue by mscdex** [nodejs/build#171]
I was curious if there is a plan to start doing cross compilation for arm, especially for pi1, since it seems like it's almost always the one holding up the completion of PR testing/acceptance?

**Comment by orangemocha** [comment]
Yes, we are working on it right now...

**Comment by joaocgreis** [comment]
Up and running! First real run: https://ci.nodejs.org/job/node-test-commit/617/

Still need to move the test logic to the Makefile, but only after this proves stable for some time.

**Comment by mscdex** [comment]
:tada: :+1:

**Comment by orangemocha** [comment]
First run took 29 minutes.. nice improvement! :smile: :+1:

**Comment by mscdex** [comment]
I noticed addons are still compiled on device. The addon tests themselves take ~40 seconds to run, so that means it spent ~5.5 mins compiling the addon tests on-device. So cross-compiling addon tests should save us a little more time yet.

@joaocgreis Is this what you meant by moving the test logic?

**Comment by orangemocha** [comment]
They are compiled on device, but on a separate device so they run in parallel. We could cross-compile them but this was easier to implement and makes for shorter runs.

**Comment by joaocgreis** [comment]
@mscdex The download size was also a concern, the addons don't add much but all the arms share a slow network. I also wanted to keep it as generic as possible. But we can certainly experiment more.

Right now the Jenkins jobs call configure and test.py directly, and have the list of files to archive hardcoded. I want to create rules like `ci-compile` and `ci-test-binary` in the Makefile that do all of that, so that other people can also experiment, and changes in the build process do not break the fanned job.

**Comment by mscdex** [comment]
Ah ok. Keep up the good work @orangemocha @joaocgreis ! :sunglasses:
