### ISSUE TITLE
incident: All RPIs are down :(

### ISSUE THREAD

**Issue by refack** [nodejs/build#1736]
https://ci.nodejs.org/label/Raspbian/
https://ci-release.nodejs.org/label/pi1-docker/
@rvagg

**Comment by rvagg** [comment]
happened because I reconfigured the network and was trying to change some things on the main nfs server - only evidenced later, perhaps when something was reset or reloaded by cron? anyway, pi's lost their nfs roots and froze up
all fixed now, but I still have a few networking-related things to do, I'll just have to be more careful and monitor changes
