### ISSUE TITLE
curl missing on test-linuxonecc-rhel72-s390x-3

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#1752]
https://ci.nodejs.org/job/citgm-smoker-nobuild/560/nodes=rhel72-s390x/console
```console
22:25:41 ++ curl https://nodejs.org/download/release/
22:25:41 /tmp/jenkins7611871491835892409.sh: line 14: curl: command not found
```

**Comment by mhdawson** [comment]
Disconnected the machine until we get ist resolved.

**Comment by sam-github** [comment]
I'm sorry, looking at the bash history, I recall that broke this by deleting curl in order to get the package reinstalled, while thrashing around to see why the ccache rules were failing to curl the HTML page with the latest version. I assumed that the package command reinstalled it because the ccache rules started working again, but that wasn't what happened.

I did `yum reinstall curl`, it is back.

**Comment by refack** [comment]
https://ci.nodejs.org/job/node-test-node-addon-api/1922/MACHINE=rhel72-s390x/console
`curl` is back
