### ISSUE TITLE
Can I have access to the release machines for maintenance purposes?

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#1835]
I gather that since they contain secrets that can be used to publish releases access is limited. I'm OK with that, but it limits my ability to perform maintenance tasks on the platforms I'm helping support, see https://github.com/nodejs/build/pull/1807.

If this would violate our access policy, I understand, and it will always have to be @mhdawson  who does the final ansible runs. If I have to join some team other than the build team to get access, perhaps I should. Suggestions, please?

**Comment by mhdawson** [comment]
We did get the ok for @gdams to have access to the IBM release machines unfortunately he left IBM so he can no longer help on that front. 

This request falls into the same  category and I think it probably even easier to support since Sam is part of the TSC (and would help us spread the load on the IBM side).  @nodejs/build what do you think?

**Comment by gibfahn** [comment]
SGTM, I can vouch for Sam

**Comment by rvagg** [comment]
can we start with access to just the IBM release machines?

**Comment by sam-github** [comment]
@rvagg Yes, please, that's all I want, I'm not likely to need to poke around on others.

**Comment by mhdawson** [comment]
@rvagg, @nodejs/build unless I hear an objection by end of this week I'll assume I can add sam's key to the IBM release machines.

**Comment by sam-github** [comment]
Thanks.
