### ISSUE TITLE
Question: can node-test-commit-unified by removed?

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#1853]
Is https://ci.nodejs.org/job/node-test-commit-unified/ used anymore?

It doesn't run on the centos7 ppc nodes, but I don't want to do maintainenance on dead jobs.

It has no build history, but that doesn't last very long

Is it used?

**Comment by mhdawson** [comment]
@refack looks like you are the only editor of the job

**Comment by sam-github** [comment]
scheduled for removal: https://ci.nodejs.org/job/archive-node-test-commit-unified/

**Comment by joaocgreis** [comment]
@sam-github sorry I only noticed this now. I see there are a few more archived jobs. What we've done for other jobs in the past was to get the XML configuration file from the "Job Config History", commit it to https://github.com/nodejs/build/tree/master/jenkins/xml and then deleting the job completely. Feel free to leave the archived jobs as they are now (4 wont hurt much), but going forward deleting the jobs is preferable because having too many jobs seems to be one of the factors making Jenkins slow.

**Comment by sam-github** [comment]
@joaocgreis  I intended to delete them, I just didn't know what was a safe way. Thanks for above.

Is there any reason I can't still do as you suggest above? Save the XML from the archive jobs, commit it, and delete the `archive-` jobs?

**Comment by joaocgreis** [comment]
@sam-github if you have the time to do that, that would be great!
