### ISSUE TITLE
Removing node-test-commit-custom-suites-freestyle from node-test-commit

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#1864]
Since this is an unmaintained pipeline I'd like to explore rolling up whatever it contributes to node-test-commit into the containered builds if possible. I can't quite figure out what the purpose of this thing is and why it's so darn complicated.

From what I can glean from the bash and the way it's invokved, all it's doing is running the worker tests when invoked from node-test-commit.

It's passed `CI_JS_SUITES=default` and `TEST_ARGS=--worker`. The console output shows it doing:

- `make -j1 bench-addons-build`
- `make -j 4 build-ci`
- `python tools/test.py -j 4 -p tap --logfile test.tap --mode=release --flaky-tests=dontcare --worker`

I think `bench-addons-build` is unnecessary for node-test-commit so it's really just a `build-ci` and the custom test.py, which is very similar to the way we invoke debug and withoutssl runs in the containered jobs (with a bonus that the configs are so much simpler).

It's also got `if [ "$TEST_ARGS" = "--worker" ] && [ "$NODEJS_MAJOR_VERSION" -lt "10" ]; then` so it's limited to Node >= 10. This should go into VersionSelectorScript.groovy (there's more of this logic for s390 and running v8-updates, those should be pulled out too).

So, I believe that if I pull out a `--worker` invocation of test.py into a containered job, put a >=10 restriction in VersionSelectorScript.groovy then I could remove this from node-test-commit. If there's anyone around that has more of a clue about this and believes this assessment is wrong, please speak up now. I'm really unhappy with this weight around our necks and would like it gone. It can be left as is for whatever nightly jobs its doing, but I also wouldn't mind removing those too in due course.

**Comment by richardlau** [comment]
> 
> 
> Since this is an unmaintained pipeline I'd like to explore rolling up whatever it contributes to node-test-commit into the containered builds if possible. I can't quite figure out what the purpose of this thing is and why it's so darn complicated.

It's complicated because it has been (ab)used in different contexts beyond its original purpose. The job was originally written to allow one-off testing of things not tested by the regular CI runs (e.g. want to run the internet or pummel test suites? Or run without intl (this was before the containerized jobs)). Somewhere along the line as requests came in to test more things as part of the regular/nightly CI and instead of adding new jobs the `custom-suites` jobs was just chained into the other jobs called with the appropriate parameters:
e.g.: 
- benchmarks (https://github.com/nodejs/build/issues/1568, this is probably what the `make -j1 bench-addons-build` is for)
- internet (https://github.com/nodejs/build/issues/1470)
- V8 (https://github.com/nodejs/build/pull/1344)
- workers (https://github.com/nodejs/build/issues/1318)

I think the job is [useful for its original purpose](https://github.com/nodejs/build/pull/1436#issuecomment-412096407) of one-off or PR specific tests (for example https://github.com/nodejs/node/pull/28733#issuecomment-512463133). For things in the regular/nightly CI runs I think it would be much clearer to have dedicated jobs (:+1: for containered where it makes sense).
