### ISSUE TITLE
libuv-test-commit-linux never finishes

### ISSUE THREAD

**Issue by cjihrig** [nodejs/build#1888]
If you look at the [libuv-test-commit job history](https://ci.nodejs.org/view/libuv/job/libuv-test-commit/), you'll see that all of the recent jobs were cancelled manually (grey icon). The linux subjob doesn't seem to complete, although all of the platforms seem to run to completion.

**Comment by sam-github** [comment]
I followed down through the logs to look for a clue, found this:
```
Configuration libuv-test-commit-linux » ppcbe-ubuntu1404 is still in the queue: All nodes of label ‘ppcbe-ubuntu1404’ are offline
Aborted
Aborted by unknown
Cancelled libuv-test-commit-linux » ppcbe-ubuntu1404
All downstream projects complete!
Collecting metadata...
Metadata collection done.
Notifying upstream projects of job completion
Finished: ABORTED
```
at https://ci.nodejs.org/job/libuv-test-commit-linux/1578/console

@mhdawson You disabled these 2 machines:
- https://ci.nodejs.org/computer/test-osuosl-ubuntu1404-ppc64_be-1/
- https://ci.nodejs.org/computer/test-osuosl-ubuntu1404-ppc64_be-2/

> Disconnected by mhdawson : No longer used now that 6.x is EOL. Disabling in advance of removing. Going to leave disabled for a few weeks before removing to make sure they are not still used for some reason.

We don't support ppc *BE* them for node, I guess we forgot about libuv!

@cjihrig Do the machines still need to be supported? Can libuv drop ppcbe support? I suspect it only has it because IBM did the work to support our platforms, so now that we don't need those platforms, maybe uv doesn't need them either? Does an order transition have to happen?

I'll enable the 2 machines for now.

**Comment by cjihrig** [comment]
> Do the machines still need to be supported? Can libuv drop ppcbe support? I suspect it only has it because IBM did the work to support our platforms, so now that we don't need those platforms, maybe uv doesn't need them either? Does an order transition have to happen?

I'll leave that call up to the IBMers. cc: @bnoordhuis

**Comment by bnoordhuis** [comment]
> Can libuv drop ppcbe support?

I don't think we've ever claimed to support it. I'm okay with dropping those machines from the test matrix.

**Comment by richardlau** [comment]
The risk should be low for dropping it... big endian issues would be tested on AIX and Linux on s390x.

**Comment by mhdawson** [comment]
That is why I disabled versus deleting them, just in case we needed them back due to something I'd not thought of.  In this case though I think I should just remove be from the libuv jobs.

**Comment by mhdawson** [comment]
Based on the comments from @cjihrig and @bnoordhuis I'll do that now and we can reverse if somebody else comments that we need to keep them in the testing.

**Comment by mhdawson** [comment]
build to validate it completes now: https://ci.nodejs.org/job/libuv-test-commit-linux/

**Comment by sam-github** [comment]
back offline, message linked to this issue

**Comment by mhdawson** [comment]
And this time with the machines disabled: https://ci.nodejs.org/job/libuv-test-commit-linux/1581/

**Comment by mhdawson** [comment]
Looks good closing.
