### ISSUE TITLE
http(s)://blog.nodejs.org/foo are wrongfully redirected

### ISSUE THREAD

**Issue by XhmikosR** [nodejs/build#1898]
For example:

```
C:\Users\xmr\Desktop>curl -ILls http://blog.nodejs.org/2014/01/16/nodejs-road-ahead/ | findstr Location
Location: https://nodejs.org/en/blog/

C:\Users\xmr\Desktop>curl -ILls https://blog.nodejs.org/2014/01/16/nodejs-road-ahead/ | findstr Location
Location: http://blog.nodejs.org/2014/01/16/nodejs-road-ahead/
Location: https://nodejs.org/en/blog/
```

**Comment by rvagg** [comment]
In https://raw.githubusercontent.com/nodejs/build/master/setup/www/resources/config/nodejs.org:

```
server {
    listen *:80;
    server_name blog.nodejs.org;
    ...
```

then, lower down, we have:

```
server {
    listen *:443 ssl http2;
    listen [::]:443 ssl http2;
    server_name blog.nodejs.org;

    return 301 http://blog.nodejs.org$request_uri;
}
```

looks like this was done way back in #389 and was probably a mistake.

Care to submit a PR that switches the `listen` portions of both of those and switches the 301 to https? I think that would work, though I do hate messing with these directives since they can break in surprising ways.

**Comment by XhmikosR** [comment]
I'm too afraid to touch those, TBH. I just noticed this while testing the main site and we have some links like that, so before I change them I thought I'd report it.

**Comment by rvagg** [comment]
OK, let's leave this open as a TODO. It's not technically difficult, it just needs some bravery and time padding in case there are pieces to pick up in the aftermath of such a change (unintended consequences).
