### ISSUE TITLE
cross-compiling for Rasperry Pi bottleneck?

### ISSUE THREAD

**Issue by Trott** [nodejs/build#1902]
Noted this in IRC but now also here for tracking/visibility:

Cross-compile for Raspberry Pi seems to be consistently taking hours, like something that used to be set up got somehow undone or something?

Here's one that took 9 hours to run (although the cross-compile itself took "only" 2.5 hours if I'm reading it right?): https://ci.nodejs.org/job/node-cross-compile/25325/

This one has been running for 8+ hours and counting. https://ci.nodejs.org/job/node-cross-compile/25326/

@rvagg

**Comment by rvagg** [comment]
```
$ ccache -s
cache directory                     /home/iojs/.ccache
primary config                      /home/iojs/.ccache/ccache.conf
secondary config      (readonly)    /usr/local/etc/ccache.conf
cache hit (direct)              12251709
cache hit (preprocessed)          162562
cache miss                        190655
called for link                    43020
called for preprocessing           23319
compile failed                        34
ccache internal error             312718
preprocessor error                    16
unsupported source language        62637
no input file                       8387
files in cache                    166926
cache size                           5.9 GB
max cache size                       7.5 GB
```

that "ccache internal error" counter is the only one incrementing.

Tried removing the cache entirely but that didn't help, they just started counting from 0. So I've done a system update, removed the Jenkins workspace and .ccache (again) and rebooted and so far it seems to be going OK "cache miss" is incrementing now. The cache will need to prime again now until it gets up to speed but hopefully it's good now.

**Comment by rvagg** [comment]
ah, I put the original ccache.conf back in place:

```
max_size = 7.5G
hard_link = true
```

and started getting the errors again, I've commented out `hard_link = true` and the errors have stopped. Presumably this is because ~/.ccache/ is on the root fs /dev/sda1 and the Jenkins workspace is on /dev/sdb1, mounted as /mnt so it can't link across filesystems. @joaocgreis did you set this config up? Is there something different now compared to the original configuration?

**Comment by joaocgreis** [comment]
> @joaocgreis did you set this config up?

No. I don't know how or why that got there. I believe ccache should work with default configuration.

The server LGTM now, the `max_size` is reasonable. I've moved `/home/iojs/.ccache.old` to `/mnt/ccache.old` because there's not much free space in sda1. FWIW, I plan to re-create the server with a new Ubuntu version when I have some time.

**Comment by rvagg** [comment]
>  Took 2 min 36 sec on node-msft-cross-compiler-1

probably
