### ISSUE TITLE
incorrect permissions on SHASUMS256.txt.asc and SHASUMS256.txt.sig  for v12.9.1

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#1904]
https://nodejs.org/dist/v12.9.1/SHASUMS256.txt.asc
https://nodejs.org/dist/v12.9.1/SHASUMS256.txt.sig

These files were serving as a 403 forbidden from nginx as permissions were set to 600.

I ssh'd into the dist server and manually chmod'd to 644 and the files and now things are working. Would be good to do a post mortem and find out why to avoid manual intervention in the future

**Comment by rvagg** [comment]
Good thinking re the fix.

I think I know what's going on. We have careful permissions fixing for all of the assets @ https://github.com/nodejs/build/blob/f95ffc8d7d9930f1bc9505b016fdd84711916759/setup/www/tools/promote/_resha.sh#L25-L26

But that doesn't include what you, as the releaser, push up afterward, which is the .asc and .sig files. So it'll depend entirely on what your local default permissions configuration is. I guess @targos had a setup that made them 600 and they were just pushed up with no modification.

Have put up https://github.com/nodejs/node/pull/29350 to try and address this, doing the permission change on the server rather than locally and relying on scp to get it right. It's an extra ssh but should be quick enough.

**Comment by targos** [comment]
it's weird, because I always release with the same machine and it's the first time that happens.
