### ISSUE TITLE
Inconsistency with OSX build bot

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#1922]
Uncovered as part of https://github.com/nodejs/build/issues/1920

We gave access to the 10.10 machine, which in retrospect is one of our older machines... should have been running on 10.12

What is a bit off is the version of xcode available on the machines. Node 8 and 10 have a minimum clang of 3.4.3. Node 12 has xcode 8. Master is now xcode 10. It seems like we may be inconsistent in what we are building with.

**Comment by rvagg** [comment]
We covered this a bit in https://github.com/nodejs/node/pull/29493 - basically we have no xcode version differentiation but now with the bump to xcode 10 for node 13+ we're going to need to start doing so, on test and release. This is a big TODO for Build to figure out, it's not something we've attempted before, hopefully `xcode-select` can help us manage multiple versions on the same machine so we don't have to over-complicate our infra needs.

**Comment by sam-github** [comment]
What is the specific request here? I'm not clear what would need to happen to close this, or if its still relevant. to: @MylesBorins 

Note that we will soon be running latest Xcode on latest OS X (with deployment target set to a minimum OS X version), because only latest Xcode supports notarization.
