### ISSUE TITLE
Permission issue while building release builds

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/build#1925]
There was a failure building the latest release on Windows. I guess it's just a flake but I think it's still good to have a closer look at this.

Besides that, I would like to resume the build but I can't see any option to do so. There is just an option to rebuild everything. Is it possible to add such an option to the config?

https://ci-release.nodejs.org/job/iojs+release/4710/nodes=vs2017-x86/console

**Comment by rvagg** [comment]
This happens on windows if you abort a build in mid compile and start one straight away without giving the system time to clean up. The previous build running on this machine was just prior and aborted: https://ci-release.nodejs.org/job/iojs+release/nodes=vs2017-x64/4709/
Just keep that in mind in future and pause for a minute or two. There's probably a Jenkins timeout setting we could use to do this but so few people interact with these systems that maybe we're just getting used to how it works. Now you know too!

**Comment by joaocgreis** [comment]
Exactly as @rvagg said. Let me add that in the test CI we got around this by not using the Git plugin and having explicit Git commands, which allows us to `taskkill msbuild` before running Git. On ci-release this would be harder to do because the same job is used for all platforms.

About resuming the build, that functionality comes from a Jenkins plugin, and given the amount of issues we've had with those, I'd rather avoid them as much as possible in ci-release. You can achieve the same functionality by using the Rebuild button (or starting a new job) and selecting only the platforms that failed.
