### ISSUE TITLE
Coverage website looks weird

### ISSUE THREAD

**Issue by addaleax** [nodejs/build#1932]
https://coverage.nodejs.org/ looks odd, the header image is huge and styles are mostly missing. I think this is happening because https://nodejs.org/layouts/css/styles.css 404s, but I can’t tell whether that’s a build or a website issue (there were some recent changes to the nodejs.org repo that likely affect this but I’m not sure where the fix should end up, here or there). /cc @XhmikosR

**Comment by richardlau** [comment]
https://github.com/nodejs/nodejs.org/pull/2544 looks like a likely suspect.

**Comment by richardlau** [comment]
I think https://github.com/nodejs/build/pull/1933 should update the right place.

**Comment by richardlau** [comment]
https://benchmarking.nodejs.org/ also looks affected. I've raised https://github.com/nodejs/benchmarking/pull/289.

**Comment by XhmikosR** [comment]
Sorry, I couldn't know that the styles were used from other sites :/

I think the best solution would be to redirect styles/css and eventually update those sites to use the new path to styles CSS.

**Comment by XhmikosR** [comment]
Alright, I made #1935 which should fix this.

But, I could definitely use a list of sites that use the assets from the main site. Which BTW is bad practice for this reason, especially the CSS.

I could work on just adding the needed CSS on each site and also make sure everything is working fine; I just need a list of sites.

**Comment by rvagg** [comment]
@XhmikosR in the past when we've done major reworking of the website, we've used redirects to keep things consistent. I wouldn't like to have a _massive_ list of redirects but the overhead isn't terrible so the list could grow. See toward the bottom of the config file @ https://raw.githubusercontent.com/nodejs/build/master/setup/www/resources/config/nodejs.org (in this repo, setup/www/resources/config/nodejs.org, not bothering to link because GH wants to display it as markdown). Perhaps this would be a good thing to do for any significant resources that have been moved? CSS, images I guess.

benchmarking and coverage are the main sites that reuse the CSS I think. If I can be indelicate, I believe the reason for the linking I think is that the people that manage those sites aren't designers and are just happy to reuse consistent styles. I suspect the maintainers of both of those sites would be more than happy to receive some design attention for their sites, including, perhaps, restructuring of resources and where they are located.

**Comment by XhmikosR** [comment]
@rvagg I already have #1935 which adds the redirects.

I think the easiest short-term solution, without risking to break things again, will be to include the CSS in those repos. This way it won't be affected by an upstream change. If there's an upstream change, changes will be needed anyway.

I'll think about it and maybe provide PRs on each repo.

For the time being #1935 should fix the breakage by adding redirects.

**Comment by rvagg** [comment]
ah, got it, sorry, missed #1935 in my notifications scan

**Comment by richardlau** [comment]
> But, I could definitely use a list of sites that use the assets from the main site. Which BTW is bad practice for this reason, especially the CSS.
> 
> I could work on just adding the needed CSS on each site and also make sure everything is working fine; I just need a list of sites.

@XhmikosR I [searched the org for `layouts/css/style`](https://github.com/search?q=org%3Anodejs+layouts%2Fcss%2Fstyle&type=Code) and also referred to https://github.com/nodejs/nodejs.dev/issues/275. I don't claim to know how these sites work but it does seem that https://benchmarking.nodejs.org/ is [generated by copying from https://github.com/nodejs/benchmarking](https://github.com/nodejs/benchmarking/blob/master/benchmarks/README.md#benchmark-results-display).

I think https://coverage.nodejs.org/ [used to be generated from https://github.com/nodejs/testing](https://github.com/nodejs/testing/tree/master/coverage) but that repository is now [archived](https://github.com/nodejs/testing/issues/56) and the scripts moved to [nodesjs/build](https://github.com/nodejs/build/pull/1055).

**Comment by XhmikosR** [comment]
Ok, so it's just these 2 websites, so with the current open PRs things will be fixed.

We can revisit how to handle the CSS case later.
