### ISSUE TITLE
Release ARMv7 machines down 

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/build#1946]
Noticed when building v8.16.2 release -  https://ci-release.nodejs.org/label/debian7-docker-armv7/ 

Also, the pi-docker builds failed with a Git issue - https://ci-release.nodejs.org/job/iojs+release/nodes=pi1-docker/4739/console I've cleaned the workspace and will try and rebuild.

**Comment by mhdawson** [comment]
@BethGriggs I just restarted the agent on -1 and it seems to be back, will restart on -2 as well.

**Comment by mhdawson** [comment]
Both are back up now, closing. Please re-open if it's not resolved.

**Comment by BethGriggs** [comment]
I'm still struggling to get a `pi-docker` Release build through (I _think_ that job produces the armv6 builds) - https://ci-release.nodejs.org/job/iojs+release/4746/nodes=pi1-docker/

The job fails with a Git checkout error - but wiping the workspace has resulted in the Git stage timing out. Any suggestions, and/or could someone take a look at the machines that serve that job?

**Comment by BethGriggs** [comment]
The build is now past the Git checkout - but i'll leave this issue open until it completes

**Comment by rvagg** [comment]
looks like it's all finished now - just be aware in future that repopulating a cleaned workspace on these machines is quite expensive so will extend your build time by quite a bit. Perhaps that was the best course in this case though.

With 8.x going away this problem should get resolved because we switched to cross compiling our release builds for 10+.
