### ISSUE TITLE
Location of ARMv7 binaries

### ISSUE THREAD

**Issue by phillipj** [nodejs/build#197]
While working on verifying the uploaded binaries on /dist/ for [nodejs.org #156](https://github.com/nodejs/new.nodejs.org/issues/156) I noticed the location of ARMv7 binaries have changed between v4.0.0 and 4.1.1

**armv7l**: https://nodejs.org/dist/v4.0.0/node-v4.0.0-linux-armv7l.tar.xz<br/>
**armv7**: https://nodejs.org/dist/v4.1.0/node-v4.1.0-linux-armv7.tar.gz

Was this an intentional change?

P.S. we're currently linking to the wrong path for v4.1.1 in the release blog post.

**Comment by rvagg** [comment]
Whoa, not great, must be because I replaced the ARMv7 build machine and the original config must have this wrong.

@Fishrock123 I've copied those files back in to staging and renamed them properly, could you run a promote again to get them copied in and signed? Then, after 1/2 a day or so we'll run it again and remove the `armv7` versions but in between we'll have both.

**Comment by rvagg** [comment]
fixed in setup @ 77c98f2

**Comment by Fishrock123** [comment]
Re-promoted.

**Comment by phillipj** [comment]
@rvagg @Fishrock123 when you remove the `armv7` file from /dist/, please remember to revert my quickfix https://github.com/nodejs/new.nodejs.org/commit/800748034e68720e361fc0cf17bf24e336db8954

**Comment by phillipj** [comment]
+ altering the filename in the shasums list

**Comment by rvagg** [comment]
thinking now that we could just leave them there, at least until the next release comes out
