### ISSUE TITLE
nodejs.org/download/release/latest/ points to 12.13.0, contradicting docs

### ISSUE THREAD

**Issue by apaprocki** [nodejs/build#1979]
This page https://github.com/nodejs/node/tree/master#current-and-lts-releases states:

> https://nodejs.org/download/release/
> 
> The latest directory is an alias for the latest Current release.

That directory (https://nodejs.org/download/release/latest/) points to 12.13.0, which is not the latest Current release.

@MylesBorins commented in nodejs/Release#495:

> would you be open to filing a bug over at nodejs/build about that? That alias is incorrect and should not have been made

**Comment by nschonni** [comment]
Probably better tracked on https://github.com/nodejs/nodejs.org/issues/2706

**Comment by rvagg** [comment]
I just think we're in a very awkward window, where 12.13.0 is both the latest Current and the latest LTS, it's on the front edge of what we've currently published so I'd call the link "correct" at least in spirit.

Technically though, we just have no easy way to determine what "current" is. There are ways, like unpacking a tarball and inspecting the innards, or looking up the tag on github and navigating to node_version.h to figure out if `LTS` is `true` or not.

We do a lot of inspection work in https://github.com/nodejs/nodejs-dist-indexer to make index.json and index.tab. But that's a separate process to making those symlinks. That all happens with some very simple logic all contained in https://github.com/nodejs/nodejs-latest-linker/blob/master/latest-linker.js

If someone feels strongly enough that this brief window that may happen each year (may not also, in previous years we've not had the gap) is a genuine problem worth solving, my suggestion would be to hack on nodejs-latest-linker and "fix" it. I think we could fix the order of calls so that it's called after nodejs-dist-indexer so that index.json is in place, which has an `"lts"` field. `process.argv[2]` should be the directory that index.json is in so it could probably read that and figure out which directory to link.

It's not something I have time for, nor do I feel this is actually a problem. But I'll provide guidance for someone that wants to hack and get it deployed when it's ready.
