### ISSUE TITLE
Removed Smartos 14 from https://ci.nodejs.org/job/node-test-commit-smartos/

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#2004]
I removed the smartos labels from https://ci.nodejs.org/job/node-test-commit-smartos/.

Opening just to confirm this is correct. I believe smartos 14 is being removed, but the jobs were still hanging waiting for smartos14 executors

@rvagg

**Comment by richardlau** [comment]
smartos14 was removed in https://github.com/nodejs/build/pull/1987. The jobs started being queued for smartos14 executors because the lines that excluded them from running were removed from VersionSelectorScript.

**Comment by rvagg** [comment]
thanks for catching that! maybe it's time we made an offboarding-checklist for our servers so we don't forget things like this.

Also removed from:
* archive-node-test-known-issues
* libuv-test-commit-smartos
* libuv-test-pipeline (renamed to archived-libuv-test-pipeline because it doesn't look like it's used)
* llnode-continuous-integration
* node-test-node-addon-api (doesn't look used)
* node-test-node-addon-api-new
