### ISSUE TITLE
can we give ashcripps access to help ansible smartos machines?

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#2005]
@mhdawson would like me to help with the ansibling of smartos machines this coming monday. I haven't found an issue that exactly says what's happening, it just seems there is lots of mention of smartos.

If its a lot of work, it might be a good thing to get @AshCripps to help us.

He is newish to the community build WG, but he is part of our team at IBM, and its intended that he spend a bunch of his time here.

I'm not sure at what point exactly he can request to join the build-wg. He meets the criteria of being known to current members (@mhdawson @richardlau and me), and of significant employment repercussion should he do something malicious.

So, just as a heads up, we hope he will be able to join the WG soonish, and perhaps can get limited access to the smartos machines this monday. I've already mostly gotten him setup with ansible, though not with any build secrets, in prep for him running ansible against the nearform minis.

@rvagg and other @nodejs/build WG members, thoughts on 

1. temp access monday for smartos provisioning?
2. whether its too soon to join the build WG? Should we wait until he has a few more PRs in?

**Comment by richardlau** [comment]
> I'm not sure at what point exactly he can request to join the build-wg. He meets the criteria of being known to current members (@mhdawson @richardlau and me), and of significant employment repercussion should he do something malicious.
> 

😅 I'm not currently a member of the Build WG... but since you're not the first person to assume I am let's fix that: https://github.com/nodejs/build/pull/2006 😄.

**Comment by rvagg** [comment]
> temp access monday for smartos provisioning?

Personally very hesitant on this one, DO and Joyent have some of key resources on machines hosted in them. Infra access to both of those services gives you pretty much everything since you can get access into the disks that hold all the crown jewels. From a security perspective there's really no such thing as "temporary access" unless we're willing to regenerate all secrets.

Will take further discussion about expanding infra to email where we tend to handle this kind of thing.

> whether its too soon to join the build WG? Should we wait until he has a few more PRs in?

No concern here, hop on board. We have a lot of test- machines in Joyent to reprovision, having nodejs_build_test access lets you do at least some of the work. It would just need some in infra to provision and setup firewall access to ci.nodejs.org.

**Comment by rvagg** [comment]
In the list of machines we need reprovisioned, there is one that I'm concerned about because it will likely involve more yak shaving than it shoud.

`test-joyent-ubuntu1604_arm_cross-x64-1` is one of our two ARM cross compiler machines, so we have redundancy here and it's all nodejs_build_test access so low risk and low(ish) security. I fear for the time sink that it may end up being so help would be appreciated. It may go perfectly well and our Ansible configs may be completely up to date and work without a hitch. But we only have two of these machines and don't tend to reprovision them so they're candidates for stale Ansible.

ansible/roles/cross-compiler/ is where all of this is at.

If someone who has (or gets) nodejs_build_test access can take responsibility for this new server then someone with infra can (1) provision a fresh one (2) replace the IP in the ci.nodejs.org firewall and (3) turn off the old one, then hand the rest over. We have the second cross compiler to rely on during the downtime if things don't go smoothly. Plus, whoever does this will learn a ton about how we do cross compiles and the moving of those resources around, and that's one overly complex part of our infra that it would be _really good_ to have more people understanding.

**Comment by joaocgreis** [comment]
I can reprovision the cross compiler. Or @sam-github would you like to do that? I'm happy to help if you need at any point.

**Comment by joaocgreis** [comment]
And happy to welcome @AshCripps to the Build WG if he wants to join!

**Comment by AshCripps** [comment]
I'd be happy to join!

**Comment by mhdawson** [comment]
@joaocgreis it would be great if you could do the cross compiler.  I was hoping to get Sam/Ashley to help with the smartos ones. 

@rvagg I was planning to provision the machines and then get @sam-github and if possible @AshCripps to help do the ansible parts.  I know it should be relatively straight forward but trying to spread the load a bit.

**Comment by mhdawson** [comment]
FYI I've already created the test smartos machines. I'll pass over the IP's to @sam-github
