### ISSUE TITLE
bottleneck in node-test-commit-arm

### ISSUE THREAD

**Issue by targos** [nodejs/build#2026]
https://ci.nodejs.org/job/node-test-commit-arm/

I takes hours. Blocked by `debian9-docker-armv7`. 
There seems to be only one machine for it and it is really slow.

**Comment by rvagg** [comment]
Been having trouble with some of these machines so I've removed and reprovisioned those two, the remainder is fairly new due to similar problems. Slowness may be a different problem but it's going to be entirely cache dependent on these and the new machines have no cache so they're going to be slow regardless.

**Comment by BridgeAR** [comment]
Could this be reopened? The CI job is again blocked on `debian9-docker-armv7`. I guess the cache should be set up by now and the other machines do not seem to have any issues.

**Comment by targos** [comment]
It really looks like there's only one executor for `debian9-docker-armv7`.
I stopped all running jobs to experiment and started only two new jobs:

https://ci.nodejs.org/job/node-test-pull-request/26774/ (arm subjob: https://ci.nodejs.org/job/node-test-commit-arm/27473/)
https://ci.nodejs.org/job/node-test-pull-request/26775/ (arm subjob: https://ci.nodejs.org/job/node-test-commit-arm/27474/)

The second one clearly seems to be waiting for a free executor.

**Comment by targos** [comment]
Yeah, only one of the hosts is online:

![image](https://user-images.githubusercontent.com/2352663/69224935-ad07ab80-0b7d-11ea-85b8-ce4c276f16f9.png)

**Comment by targos** [comment]
Same issue with debian8:

![image](https://user-images.githubusercontent.com/2352663/69241894-054fa500-0ba0-11ea-8e47-e7a3eb21046a.png)

**Comment by targos** [comment]
The same nodes are used for `debian8-docker-armv7` too, so even more jobs are blocked:

![image](https://user-images.githubusercontent.com/2352663/69241986-392aca80-0ba0-11ea-9b99-9ce91bb49b2b.png)

**Comment by Trott** [comment]
I tried to SSH into the two offline hosts, but I can't. (They timeout.) I can ssh into the online host. So, maybe they're *really* offline and not just online-but-without-agent.jar-running or whatever.

**Comment by jbergstroem** [comment]
`-1` and `-3` were neither accessible via ssh nor console through the web admin. After reboot I could log in again and they seem to get new jobs.

**Comment by targos** [comment]
So it's solved, thanks!

**Comment by BridgeAR** [comment]
It came up again. See e.g., https://ci.nodejs.org/job/node-test-commit-arm/27675/ (Started 4 hr 24 min ago)

**Comment by BethGriggs** [comment]
@BridgeAR, the sub-job https://ci.nodejs.org/job/node-test-commit-arm/27675/nodes=debian9-docker-armv7/console appeared to have been hanging for several hours. I went ahead and aborted it to hopefully unblock CI 🤞.

//cc @targos I believe the CI that was aborted was on your PR - I resumed the build.

**Comment by rvagg** [comment]
test-scaleway-ubuntu1804-armv7l-1 was offline, that didn't help matters, had to force restart it, I think we just need to be more tuned into these machines, they can be a bit flaky sometimes.

**Comment by BridgeAR** [comment]
And again: https://ci.nodejs.org/job/node-test-commit-arm/27872/nodes=debian9-docker-armv7/

It does not hang, it's still compiling, just **super** slow.

**Comment by rvagg** [comment]
Discussed that one ^ on IRC, it'd because there was no cache for 13.x and this was the first 13.x since reprovision. A re-run on the same machine took a normal amount of time.

Unfortunately "normal" is still ~40 minutes for compile then extra for tests. Not great, but I believe it's largely to do with the growing codebase size and the best we can do is give up on native compiles and add a cross-compile step.

**Comment by BridgeAR** [comment]
I would like to reopen this issue. ARM is still slow. As soon as I start multiple CIs this becomes a huge bottleneck.

Example: https://ci.nodejs.org/job/node-test-commit-arm/28572/

`Started 4 hr 42 min ago`

It is always `debian9-docker-armv7` that is extremly slow.

**Comment by BridgeAR** [comment]
This does not seem to have something to do with the code cache. It happens consistently for master and the cache should be available in that case. It also only happens for ARM 7 with Debian 9.

**Comment by rvagg** [comment]
I've been trying to make these machines work better with the current master but we seem to have passed some threshold of code size or complexity that makes the builds extra slow. I recently reduced `JOBS` from 4 to 2 because we were getting OOM errors when compiling. It seems to me that with a primed ccache, it still shouldn't take nearly as long to build as it is. So far I haven't figured out what's going on with that. Maybe these machines have slower block storage now that Scaleway is trying to retire its ARMv7 machines. One thing I haven't tried is adding enough swap that would allow `JOBS=4` to still work, maybe then it'll pick up objects out of a primed ccache quicker... that seems questionable though.

**Comment by rvagg** [comment]
oh yeah, and the other option is to cross-compile, basically the same procedure we do with arm-fanned but without the fanning

**Comment by rvagg** [comment]
2 of the 3 machines down again today, big backlog with jobs taking >4h

I've removed debian8-docker-armv7 and debian9-docker-armv7 from node-test-commit-arm, it's just an arm64 job for now.

Before we bring them back in we need to figure out if it's possible to increase reliability and speed of these builds.

**Comment by BridgeAR** [comment]
Arm is again a bottleneck on our CIs: https://ci.nodejs.org/job/node-test-commit-arm-fanned/14621/

![image](https://user-images.githubusercontent.com/8822573/80492659-a4a17100-8964-11ea-8f58-1876d81b6fae.png)

**Comment by rvagg** [comment]
```
/dev/sdd1       110G  105G     0 100% /exports2
```

1/2 of the Pi's will be offline because of this. I mentioned previously that I need to restructure the way the NFS mounts are being used now that the repo is so massive.

I'm disabling arm-fanned for now while I find time to make this happen, it's obviously not sustainable as it is now.

The plan is to put everything but ~iojs/build onto a larger HDD array on that server and leave ~iojs/build as the only things using the SSDs that are currently in use. It just needs a bit of fstab, dhcp/tftp nfs-boot fiddling and some ansible updating.
