### ISSUE TITLE
hudson.plugins.git.GitException: Command "git clean -fdx" returned status code 1

### ISSUE THREAD

**Issue by evanlucas** [nodejs/build#204]
See https://ci.nodejs.org/job/node-test-binary-arm/73/RUN_SUBSET=5,nodes=pi1-raspbian-wheezy/console

This was on one of the fanned arms

**Comment by orangemocha** [comment]
Possibly due to a dangling node instance, though I am not 100% sure.

It happened again on the same slave on the next run: https://ci.nodejs.org/job/node-test-binary-arm/74/RUN_SUBSET=6,nodes=pi1-raspbian-wheezy/console

I marked the slave as temporary offline so that CI can continue to operate until @rvagg is able to investigate or reboot (as he is the only one with access to that machine).

**Comment by rvagg** [comment]
rebooted, cleaned workspace and back online

**Comment by evanlucas** [comment]
Thanks!

**Comment by blankhang** [comment]
> rebooted, cleaned workspace and back online

had same issues and after reboot and cleaned workspace my jenkins node worked again
thanks
