### ISSUE TITLE
Windows CI issues on v10.x

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/build#2070]
Based on looking at https://github.com/nodejs/node/issues/30639#issuecomment-559453240,
I suspect something specific about `test-azure_msft-win10-x64-3` and `test-azure_msft-win2016-x64-3` may be causing the test failures seen on v10.x. 

Can we mark these two as offline in Jenkins temporarily so that I can do a test CI to see if this is the case?

**Comment by richardlau** [comment]
Marked the following offline with a reason linking back to this issue:
https://ci.nodejs.org/computer/test-azure_msft-win10-x64-3/
https://ci.nodejs.org/computer/test-azure_msft-win2016-x64-3/

**Comment by richardlau** [comment]
@joaocgreis is it possible that the work being done in https://github.com/nodejs/build/issues/1996 is somehow related?

**Comment by joaocgreis** [comment]
@richardlau thanks, taking the machines offline is the right thing to do in this case. I'll take a look ASAP and try to figure out what's happening there.

In any case, those two machines are going away very soon. While I'd rather understand what's happening there, we've had other issues that only happen in specifics machines and that's why I'm refreshing all of them.

**Comment by joaocgreis** [comment]
Should be fixed: https://github.com/nodejs/node/issues/30639#issuecomment-559583146
