### ISSUE TITLE
Windows release servers don't have release ssh config

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#2078]
@joaocgreis a little TODO for you. I've been getting the Pi 1's ready for release builds again for 8.x in case we're going to push one out before year end and it seems there's a lot of work to be done on 8.x and 10.x (at least) since we don't run them regularly enough to notice.

Windows release machines don't seem to have the ssh config properly in them (not an ansible task), they need an .ssh/config with `node-www` pointing to the right place and the release ssh private key for `staging`.

*  release-rackspace-win2012r2-x64-1 https://ci-release.nodejs.org/job/iojs+release/4898/nodes=vs2017-x86/ & https://ci-release.nodejs.org/job/iojs+release/4898/nodes=vs2017-x86/
*  release-rackspace-win2008r2-x64-4 https://ci-release.nodejs.org/job/iojs+release/4897/nodes=vs2015-x86/
* release-rackspace-win2008r2-x64-3 https://ci-release.nodejs.org/job/iojs+release/4897/nodes=vs2015-x64/

are the ones I've encountered so far, so maybe whatever you recently reprovisioned?

**Comment by joaocgreis** [comment]
@rvagg thanks for the quick warning!

The issue seems to be that `ssh -F \\config` no longer works, and that's exactly what we were using (defined in the env vars section of iojs+release). `ssh -F \config` and `ssh -F c:\\config` both work, I changed it to the latter. Looks fixed.

Rebuilds of the jobs you mentioned:
- https://ci-release.nodejs.org/job/iojs+release/4903/
- https://ci-release.nodejs.org/job/iojs+release/4904/

And master just to be sure: https://ci-release.nodejs.org/job/iojs+release/4905/

Those machines have not changed at all recently. They should be ready to release 8.x, same as they were last time. (I'll add a new VS2019 one soon, but not touch the existing ones.) From the Job Config History I see the job did not change either. Looking at the console output between https://ci-release.nodejs.org/job/iojs+release/nodes=vs2017-x64/4896/consoleFull and https://ci-release.nodejs.org/job/iojs+release/nodes=vs2017-x64/4898/consoleFull, it looks like Jenkins stopped converting `\\` into a single `\`, which explains this issue. Possibly some plugin update.
