### ISSUE TITLE
cmake on CITGM infrastructure

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/build#2097]
Some modules partially use cmake and seem to fail due to the lack of it on our infrastructure.

Would it be possible to add cmake to fix that?

**Comment by targos** [comment]
Refs: https://github.com/nodejs/citgm/issues/770

**Comment by rolftimmermans** [comment]
I'm a maintainer of zeromq.js and we use CMake to build the node add-on. Is there any way I can assist to get CMake added to the build systems/images?

**Comment by sam-github** [comment]
If the machines have a working registry system (yum, apt, brew), and that system has a sufficiently up-to-date cmake, then this should be not too difficult, but like all things build, it takes a bit of legwork:

- List affected jobs: ...
- List affected build workers: ...
- List what version of cmake is available, if any, on their OS level: ...
- List exact name of the package (per host), and add it to the relevant ansible yml file: ...
- Run ansible on each of the hosts to install cmake
- Trigger builds of all affected jobs (see)

@rolftimmermans We don't onboard people into build very quickly because of the amount of root privs in CI it gives, but much of the work above doesn't require any privileges.

If someone took this to the stage where I just had to run ansible-playbook on a PR they put together, I'd find an hour to do that, but otherwise, I'm working on a few other build tasks ATM and won't have time to start this. Someone else might have time.

**Comment by richardlau** [comment]
We do have some machines with cmake installed as we have two running libuv jobs:
- https://ci.nodejs.org/view/libuv/job/libuv-test-commit-linux-cmake/
- https://ci.nodejs.org/view/libuv/job/libuv-test-commit-windows-cmake/

I haven't looked (yet) at how those jobs specify which nodes to run on and whether there's overlap with the hosts the CITGM jobs currently run on.

**Comment by joaocgreis** [comment]
Installed CMake on all Windows machines (included in PR https://github.com/nodejs/build/pull/2099).

**Comment by BridgeAR** [comment]
What's the status here?

**Comment by AshCripps** [comment]
cmake should now be available on all test macs

**Comment by richardlau** [comment]
cmake is now on the IBM platforms in the CI (we're using cmake to build libuv).

**Comment by bl-ue** [comment]
Stable bots don't seem all that useful 🤔
