### ISSUE TITLE
Add node-test-commit-plinux to node-test-commit

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#211]
I've created this job to test pLinux for BE and LE https://ci.nodejs.org/job/node-test-commit-plinux/

I created it by cloning node-test-commit-linux and modifying to cover the plinux platforms.

I'd like to add it to node-test-commit as one of the jobs in the MultiJob Phase so that it gets run to cover pLinux on the CI runs done to validate PRs.

There are failures, but there are issues raised for all of them and they are being worked.  I see that there are other platforms with failures covered by node-test-commit so I'm thinking this should not be  blocker.

Its not been an issue until recently but there are been ~3 changes in the last week that have introduced failures on PPC would like to get coverage.

**Comment by mhdawson** [comment]
@jbergstroem, @rvagg, @orangemocha   any concerns or is it ok to go ahead ?

**Comment by mhdawson** [comment]
One thing that probably needs to be addressed is to ensure it does not run for 0.10.X or 0.12.X or io.js release prior to 4.X.  I did trim the NODES_SUBSET to that it only includes io.js, pure_doc_changes and all_nodes but I expect we may need something more. @orangemocha would you have a suggestion of how we handle this.

**Comment by orangemocha** [comment]
I reviewed the job configuration and it generally looks good to me. 

Regarding NODES_SUBSET, your combination filter looks correct to ensure that it won't run on v0.x. :+1: 

In the NODES_SUBSET choice parameter definition however, I would include 0.10 and 0.12. I am almost sure that it won't fail if they are not there (when invoked by node-test-commit on v0.x), but it's easier to add them then to test it. It will still be a no-op on those versions because of the combination filter.

I noticed that the last build took 25 minutes. This puts it close to our current longest pole. Is ccache set up on these machines?

+1 for adding this to node-test-commit. I would suggest notifying the collaborators when you do so, to let them know about the failing tests.

**Comment by mhdawson** [comment]
@orangemocha  thanks, will add back the 0.10 and 0.12 to the NODES_SUBSET.  I know I should probably know this already but whats the standard way to notifying the collaborators.

CC test is not setup,  @jbergstroem do we have standard doc for how we set that up ?

**Comment by orangemocha** [comment]
You can mention @ nodejs/collaborators, without the space.

**Comment by mhdawson** [comment]
On the ccache front, looking at the history for the last 3 runs they are <10 mins.  I'm guessing the first 2 runs at around 25mins were warming up the cache on our 2 machines for the new job.

Unless anybody objects by tomorrow morning my time I'll go ahead and add the link to node-test-commit and send out the heads up to the collaborators.

**Comment by jbergstroem** [comment]
@mhdawson no more setup for `ccache` is needed. What you're looking at when it takes time to build is a new v8 (or no cache at all). If it doesn't improve the path to `ccache` might differ but in this case you should be all good.

**Comment by mhdawson** [comment]
@nodejs/collaborators as an FYI I just added node-test-commit-plinux as a sub-job for node-test-commit so that we run regression tests on the plinux platforms.   plinux LE is currently green while the following 2 tests fail for plinux BE

not ok 711 test-tick-processor.js
not ok 45 test-child-process-fork-regr-gh-2847.js

There are issues opened for these 2 and people are working on them.
