### ISSUE TITLE
arm cross-compile failures for v10.x

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/build#2182]
Not sure if this has been raised already, I've hit a few arm-cross compile failures when trying to run CI on v10.x. 

https://ci.nodejs.org/job/node-cross-compile/nodes=cross-compiler-armv6-gcc-4.9.4/27790

```
14:34:47 FATAL: java.nio.channels.ClosedChannelException
14:34:47 java.nio.channels.ClosedChannelException
14:34:47 Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 137.116.94.125/137.116.94.125:4035
```

https://ci.nodejs.org/job/node-cross-compile/nodes=cross-compiler-armv6-gcc-4.9.4/27789 and https://ci.nodejs.org/job/node-cross-compile/nodes=cross-compiler-armv6-gcc-4.9.4/27788/

```
13:45:02 java.lang.OutOfMemoryError: Java heap space
13:45:02 Caused: java.io.IOException: Remote call on JNLP4-connect connection from 137.116.94.125/137.116.94.125:4035 failed
13:45:02 	at hudson.remoting.Channel.call(Channel.java:961)
13:45:02 	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:283)
```

**Comment by rvagg** [comment]
FTR test-azure_msft-ubuntu1604_arm_cross-x64-1 got disconnected because of this issue, its backup test-joyent-ubuntu1604_arm_cross-x64-1, was down yesterday so we lost capacity, whoops!

I've cleaned and updated test-azure_msft-ubuntu1604_arm_cross-x64-1 and rebooted it. Cross fingers I think and see if it's fixed.
