### ISSUE TITLE
Multiple infra failures on arm machines

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#2205]
https://ci.nodejs.org/job/node-test-commit-arm/

https://ci.nodejs.org/job/node-test-commit-arm/29801/
https://ci.nodejs.org/job/node-test-commit-arm/29797/
https://ci.nodejs.org/job/node-test-commit-arm/29796/

All of them failing due to socket hangups

```
18:35:28 Error: socket hang up
18:35:28     at connResetException (internal/errors.js:613:14)
18:35:28     at TLSSocket.socketCloseListener (_http_client.js:406:25)
18:35:28     at TLSSocket.emit (events.js:328:22)
18:35:28     at net.js:672:12
18:35:28     at TCP.done (_tls_wrap.js:563:7) {
18:35:28   code: 'ECONNRESET'
18:35:28 }
```

Same errors as https://github.com/nodejs/build/issues/2178

**Comment by MylesBorins** [comment]
Only happening on these three hosts, both from packetnet

https://ci.nodejs.org/computer/test-packetnet-centos7-arm64-1/builds
https://ci.nodejs.org/computer/test-packetnet-centos7-arm64-2/builds
https://ci.nodejs.org/computer/test-packetnet-ubuntu1604-arm64-1/builds

It concerns me that it is 3 different machines all having the same error... two different operating systems. They do share the same architecture as well as provider... so perhaps they are having network issues?

**Comment by rvagg** [comment]
It's tricky trying to interpret jenkins errors like this, they often hide the real issue and all you see is something that makes it look like something inside jenkins is at fault.
I'm tempted to blame the JRE on this since one of the common themes is arm64 but there's some variation in the version installed (1.8.0 222 vs 1.8.0 242).
On all 4 packet.net arm64 machines I've done a system upgrade, upgraded slave.jar (it's nearly a year old on all of them), cleaned out the workspaces and rebooted. Let's leave this issue open as a reminder to monitor for a few days to see if it's fixed.

**Comment by jkleinsc** [comment]
I'd like to try getting GitHub actions running on arm64.  I have an arm64 server on packet.net for Electron that I can use for testing a POC.

**Comment by jkleinsc** [comment]
POC here: https://github.com/jkleinsc/node/runs/490669108

**Comment by rvagg** [comment]
We haven't done any self-hosted github acitons builders yet @jkleinsc, but it'd be great to start exploring that. If you think this is something we should consider adopting here then maybe we can wire it up on our packet.net infra; as long as runs aren't going to conflict with our existing CI runs or we could entirely replace them. We currently test on Ubuntu 16.04 and CentOS 7.

**Comment by jkleinsc** [comment]
@rvagg I think moving over to GitHub actions could be a great way to reduce the maintenance load on the build WG as it is infrastructure you do not have to maintain.  The self hosted runners would have to still be maintained, but I'm pretty sure the agent that runs on the self host runners is self updating.  The only caveat that might be an issue is that GitHub doesn't recommend using self hosted runners on public repos: https://help.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#self-hosted-runner-security-with-public-repositories.  I do wonder though if docker containers were used if it would mitigate the security issue.

**Comment by mmarchini** [comment]
I'm interested in seeing a POC of a runner so we can compare maintenance burden with Jenkins. From a configuration perspective, setting up Actions jobs seems a lot more straightforward than Jenkins.

OTOH, we can't move things permanently from Jenkins to Actions right now as we first need to make sure we can cover the minimum compiler and operating system versions on Actions. Even if we can cover, there are several platforms not supported by Actions (FreeBSD, SmartOS, AIX, PPC, LinuxOne). With that being said, [the runner is open sourced](https://github.com/actions/runner), so adding support for these platforms is possible (of course, I don't expect the WG to do it).

Another thing to consider is that our Release workflow relies on Jenkins today, so even if we decide to add runners for the supported platforms, we need to keep the Jenkins jobs to make sure Release still works. Having duplicated machines (one running Jenkins, one running Actions) seems like a bigger maintenance burden though.

Other small issues like lack of custom parametrized runs on Actions also prevents us from moving away from Jenkins (stress tests, for example).

I'm still hopeful for GitHub Actions, but any move in that direction means a bigger change on how we operate and deserves it's own Strategic Initiative. Which is why I'm interested in seeing how a POC will play out, we might find out it's not worth starting any migrations here, or we might find out the maintenance burden is significantly lower, justifying a migration.

**Comment by richardlau** [comment]
> 
> 
> I'm interested in seeing a POC of a runner so we can compare maintenance burden with Jenkins. From a configuration perspective, setting up Actions jobs seems a lot more straightforward than Jenkins.
> 
> OTOH, we can't move things permanently from Jenkins to Actions right now as we first need to make sure we can cover the minimum compiler and operating system versions on Actions. Even if we can cover, there are several platforms not supported by Actions (FreeBSD, SmartOS, AIX, PPC, LinuxOne). With that being said, [the runner is open sourced](https://github.com/actions/runner), so adding support for these platforms is possible (of course, I don't expect the WG to do it).
> 

The runner may be open sourced but would require rewriting in something more portable than .NET core: 
- https://github.com/actions/runner/issues/296
- https://github.com/actions/runner/issues/243

**Comment by mmarchini** [comment]
Moved the discussion on Action runners to a separate issue and marked the comments here as "off-topic" to avoid diverging from the issue at hand.
