### ISSUE TITLE
Jenkins daemon on `test-packetnet-ubuntu1604-x64-` not restarting after OOM

### ISSUE THREAD

**Issue by mmarchini** [nodejs/build#2212]
For reference: https://github.com/nodejs/build/issues/2211

The JVM died from OOM on both machines, but systemd didn't restart it, blocking our CI from running. We might want to change our configuration to ensure Jenkins is restarted if the JVM crashes.

**Comment by rvagg** [comment]
Also, I've had the third, https://ci.nodejs.org/computer/test-softlayer-ubuntu1604-x64-1/ offline for a while now, probably needs a reprovision, so that didn't help!

We have this in the systemd config on those machines:

```
[Service]
Type=simple
User=iojs
Restart=always
RestartSec=30
StartLimitInterval=0
```

From the [systemd docs](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart=):

> If set to `always`, the service will be restarted regardless of whether it exited cleanly or not, got terminated abnormally by a signal, or hit a timeout.

So I don't understand why it didn't restart (for reference, the systemd status output: https://github.com/nodejs/build/issues/2211#issuecomment-596764424).

Maybe this is a problem with the older systemd in 16.04 and that upgrade to 18.04 should occur sooner than later on these machines? (I was thinking of doing this when I got around to reprovisioning test-softlayer-ubuntu1604-x64-1).

**Comment by mmarchini** [comment]
The Java process was still running after the OOM, so maybe we need to tweak something on Java/Jenkins for the process to exit on OOM.

**Comment by rvagg** [comment]
ooof

https://stackoverflow.com/questions/12096403/java-shutting-down-on-out-of-memory-error has some good commentary, `-XX:+CrashOnOutOfMemoryError ` sounds like a winner if available, `-XX:OnOutOfMemoryError="kill -9 %p"` if not. We use OpenJDK 8 in most places I think, no idea  what's available.
