### ISSUE TITLE
Status reported by bot doesn't match status of last Jenkins run

### ISSUE THREAD

**Issue by mmarchini** [nodejs/build#2241]
I noticed this on several pull requests. Seems like the bot doesn't always update all Check statuses:

![img-2020-03-19-150913](https://user-images.githubusercontent.com/4048656/77119562-f107a180-69f3-11ea-832c-0e92f66f5229.png)
![img-2020-03-19-150906](https://user-images.githubusercontent.com/4048656/77119564-f238ce80-69f3-11ea-8302-690ec9e1a3d0.png)

**Comment by rvagg** [comment]
This might be to do with my change of jenkins-workspace machines. I know I put the first one into the GitHub bot config but don't recall doing the second (might have, my memory is fuzzy). If someone has access to that machine and wants to check that both new 18.04 workspace machines' IPs are in there that would be helpful. Otherwise I'll check tomorrow when in front of my computer.

**Comment by rvagg** [comment]
Did someone touch the github-bot server? the config file is right, in sync with what we have here in roles/github-bot/templates/environment-file.j2 which has the 2 IP addresses that should be currently pinging it and it says the `github-bot` service has been running since 7 hours ago. I've done another reload just in case, maybe the problem will be fixed?

**Comment by mmarchini** [comment]
@rvagg I don't think the problem is related to the recent changes on jenkins-workspace machines. These changes were last week, right? I've been seeing it for a while.

> Almost every PR? This particular issue is particular to the linux-containered job and only if one of the axes failed.

@richardlau you're right, I'm only seeing it on `linux-containered`, but it's frequent enough to be annoying. I just landed three PRs, two of which this happened. The combo of flaky tests not marked as flaky with the misconfiguration you mentioned is probably the reason I'm seeing this often. I think I'm also a bit unlucky, looking at the other PRs ready to land with :x: on GitHub, most of them don't have this issue :smile:.

Would be happy to help fix this, but I'd need some pointers (I also don't think I have enough access to see how things are set up).

**Comment by mmarchini** [comment]
probably not actionable (similar to https://github.com/nodejs/build/issues/2224)
