### ISSUE TITLE
Give libuv collaborators permission to edit libuv job configuration in Jenkins

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2243]
The current permissions for the libuv CI jobs looks like this:
![image](https://user-images.githubusercontent.com/5445507/77355622-ac09a500-6d3c-11ea-861a-76b5ad17290e.png)

(I'm not aware of the history behind why there are individuals in the access table)

I would like to propose giving libuv collaborators (`libuv*Collaborators`) permission to configure the jobs. This would be in a similar manner to what we have documented for working groups (https://github.com/nodejs/build/blob/master/GOVERNANCE.md#jenkins-job-configuration-access) with `libuv` the group with the "ability to run/cancel jobs" (as currently the case) and `libuv*Collaborators` "ability to modify jobs".

Related is an effort to trim down `libuv*Collaborators` to active collaborators (https://github.com/libuv/libuv/pull/2682#issuecomment-589758303) which would reduce the number of people in the group who would be given the additional permission.

cc @nodejs/libuv

**Comment by bnoordhuis** [comment]
> Related is an effort to trim down libuv*Collaborators to active collaborators

I removed the inactive collaborators a few days ago so `@libuv/collaborators` is now down to 10 people.

**Comment by rvagg** [comment]
Not a -1, but I'm hesitant on this, it's so easy to screw things up and to do so in a way that extends beyond individual jobs. Some people know their limits and not to go fiddling with things they don't know about but others take the attitude that because they _can_ access something, then they can just wade on in.
I think I'd be more comfortable with an opt-in system. Maybe have a new group `@libuv/jenkins-admins` and let the libuv team manage a process of putting people in that who they trust to access this stuff? Or just people that explicitly ask for elevated permissions, rather than just making the "Configure" button appear for everyone.

**Comment by mhdawson** [comment]
For other team, we did create a -admins team and then let that team managed who was part of of the admins (I think that approach is even documented somewhere). I'd be +1 for that for libuv.

**Comment by vtjnash** [comment]
As someone who would end up with extra permissions, and ended up here because I am looking to fix an issue with the libuv build configuration (https://github.com/libuv/libuv/issues/2930), I'm also hesitant on being granted too much configuration power. I think I'd be too easy on a complex project like Jenkins for me to end up in the wrong section and cause headaches by altering something I didn't mean to. Aside from the increased security risk if someone steals my account and intentionally wants to wreak havoc also.

**Comment by richardlau** [comment]
It doesn't sound like there's much enthusiasm for this so I'll close.
