### ISSUE TITLE
Download slow, breaking CI

### ISSUE THREAD

**Issue by johnny88** [nodejs/build#2263]
Hello,

I noticed that the download speed of node js has become rather slow which breaks a our azure pipeline task. Basically it times out and our build doesn't continue.

Any help with this would be appreciated and let me know if you need anything from me, thanks!

[Azure task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js?view=azure-devops)

**Comment by aviatrix** [comment]
what i've seen is that nodejs.org itself is erroring out with error 500 for the past 30-40 minutes, now seems to be up again

**Comment by johnny88** [comment]
Download still seems to be slow unfortunately, even if the site is up.

**Comment by adamayoung** [comment]
Also getting this in my Azure Pipeline when trying to install Node 13.x

**Comment by mihaimircea** [comment]
Same error for trying to install node 12.16.1, from ubuntu-latest on Azure Pipelines

**Comment by johnny88** [comment]
I think the problem is that when the download takes too long the node azure pipelines task times out/is unable to use a half downloaded file.

**Comment by Moussto** [comment]
It's being tracked in the node repo nodejs/node#32683

**Comment by johnny88** [comment]
Ok, I'll close then.

**Comment by johnny88** [comment]
This is still technically a problem, and the more eyes on it the better.

**Comment by ErisDS** [comment]
This is causing a lot of problems with CI/build tools and in cases where these are charged for computation time, costing people a lot of money:

https://github.com/actions/setup-node/issues/132

**Comment by joepie91** [comment]
> This is causing a lot of problems with CI/build tools and in cases where these are charged for computation time, costing people a lot of money

This sort of comment is really *not* okay.

It's not the build team's problem nor responsibility if people haven't bothered to set up some local redundancy/caching and the resulting failures are costing them money, *especially* for a free service.

I'm sure they have enough on their mind already, *without* additional pressure from "this is costing us money!" type comments.

**Comment by fishcharlie** [comment]
@joepie91 

> This sort of comment is really _not_ okay.
> 
> It's not the build team's problem nor responsibility if people haven't bothered to set up some local redundancy/caching and the resulting failures are costing them money, _especially_ for a free service. Everyone's business/infrastructure continuity is their own responsibility.
> 
> I'm sure they have enough on their mind already, _without_ additional pressure from "this is costing us money!" type comments.

This is fair. I do think it's **extremely** important to realize the increased frustration due to the size and impact of Node.js. The larger an open source project becomes, the more responsibility it has. I think it's fair to hold a project the size of Node.js to a higher standard than most open source projects.

It's nearly impossible in this day and age to have 0 dependencies and 100% redundancy.

The reality is that it is costing people money. It's also important to understand that yes, in an ideal world, redundancy and caching should exist. But a lot of systems don't have very good support for that. This is not an ideal world.

The Node.js team should take responsibility for this. It's unfair to place all the blame or responsibility on them. I think most of the frustration is due to the lack of updates from the Node.js team. And I believe that frustration is warranted.

For me personally, all I ask is more transparency and updates from the Node.js team.

**Comment by joepie91** [comment]
> The larger an open source project becomes, the more responsibility it has. I think it's fair to hold a project the size of Node.js to a higher standard than most open source projects.

To a degree, yes. But hardware breaks, servers break, and especially when something isn't a service that people are actually paying for and have an availability agreement for, I don't think it's reasonable to expect equivalent service to a commercial service, like people seem to do here (and in other threads about the issue).

> The reality is that it is costing people money. It's also important to understand that yes, in an ideal world, redundancy and caching should exist. But a lot of systems don't have very good support for that. This is not an ideal world.

Sure. But it's one's own decision to actually *use* such imperfect systems without petitioning the vendors to fix them, and the costs for that decision/tradeoff should be shouldered by those picking the systems, not by some random third party that had nothing to do with the decision (Node.js core, in this particular case).

> I think most of the frustration is due to the lack of updates from the Node.js team.

An update was provided [here](https://github.com/nodejs/node/issues/32683#issuecomment-609791309). Presumably the status has not changed since. I'm not sure what other updates people are expecting from something that is, again, a free service.

**Comment by addaleax** [comment]
Yeah. I think this is the kind of thing that deserves a post-mortem with concrete steps to stop this from happening again, but for the moment, if there’s anything happening then you’ll see it here.

> > I think most of the frustration is due to the lack of updates from the Node.js team.
> 
> An update was provided [here](https://github.com/nodejs/node/issues/32683#issuecomment-609791309). Presumably the status has not changed since. 

:100:

**Comment by Trott** [comment]
@nodejs/build-infra

**Comment by mhdawson** [comment]
We are getting a lot of `No such file or directory`  in /var/log/nginx/nodejs/nodejs.org-error.log but non of those are for requests to downloads

**Comment by mhdawson** [comment]
At the same time plenty of requests for downloads in /var/log/nginx/nodejs/ndoejs.org-access.log

**Comment by mhdawson** [comment]
Going to see if there is anything in the cloudflare logs

**Comment by sam-github** [comment]
> HTTP/2 stream 0 was not closed cleanly

^--- that's interesting, do we always serve over HTTP/2? Is it possible something changed wrt. that?

**Comment by mhdawson** [comment]
One thing on cloudflare that stands out so far is that for the last month only 12% of the traffic was uncached, and stat for last week is similar.  Uncached for the last 6 hours is 48%

**Comment by jgehrcke** [comment]
I don't think that Cloudflare in front of a single box is the right solution for serving these dist files when robustness is the goal.

Even small hiccups in the backend are exposed.

The single machine that we talk about here is in the hot path more often than it should be. For Cloudflare to fall back to serving from cache while the backend is not available very specific conditions need to be met: https://support.cloudflare.com/hc/en-us/articles/200168436-Understanding-Cloudflare-Always-Online 

I myself have Cloudflare in front of a single box and was often surprised how this setup does _not_ magically heal transient problems in the backend.

Let's strive towards a solution where the backend is never in the hot path. 

Typically, dist files like the ones we talk about here should be served by a real CDN like fastly (which sponsors the hosting for Python), cloudfront, Google Cloud CDN, etc.

**Comment by mhdawson** [comment]
Are people still seeing the issue? I have yet to have a download be slow or fail?

**Comment by mkonikov** [comment]
In our CI our build at `3:52:30 pm ET` failed. Running another one now and will advise if run into issues.

**Comment by targos** [comment]
@mhdawson I seems back to normal. The load on the server is much lower than before, SSH stopped lagging and `kswapd0` / `ksoftirqd/0` no longer use the CPU.

**Comment by tholu** [comment]
@mhdawson Seems fast again now for me, just in time as I set up a simple caching of the needed artifacts. How did you fix it?

**Comment by mhdawson** [comment]
Interestingly it also seems like the cached bandwidth on cloudflare as a ratio to total traffic is going back up. That started at around 4:30 EST PM today based on the graph. As of 5:15 EST  is was down to 14% versus 50% when we saw bad performance.  It started to go up in terms of the uncached  percentage around 7PM EST on April 5th.

As @targos mentioned the load on our machines also seems lower which would make sense if more of the load is being cached. 

@tholu I wish I could say I fixed something but I've not changed anything. Was just ramping up looking at the logs and trying to figure out what was going on :). 

There were some outages reported for cloudflare today, but nothing that seems related or with times that match the period of time we saw the higher uncached bandwidth. 

```
Apr 6, 2020
Issues enabling DNSSEC
Resolved - Cloudflare has resolved the issue and services have resumed normal operation.
Apr 6, 13:44 UTC
Monitoring - Cloudflare has implemented a fix for this issue and is currently monitoring the results.

We will update the status once the issue is resolved.
Apr 6, 13:35 UTC
Investigating - Cloudflare is investigating issues with enabling DNSSEC.

This does not affect existing DNSSEC configurations, which are working as expected.

We are working to understand the full impact and mitigate this problem. More updates to follow shortly.
Apr 6, 12:53 UTC
Performance Issues in Frankfurt, Germany
Resolved - This incident has been resolved.
Apr 6, 12:12 UTC
Monitoring - A fix has been implemented and we are monitoring the results.
Apr 6, 12:05 UTC
Investigating - We are investigating possible performance issues in Frankfurt, Germany (FRA)
Apr 6, 11:29 UTC
```


Our cloudflare logs are being pushed to google storage and I've  not yet found how to get those, if things are working better now then looking at those can probably wait until @rvagg is online and can take a look or point me to instructions/doc as to how they are stored.

Looking further back in the access logs on our machine I do see lots of
500 errors for downloads.  Tailing the access log file now I don't see any.

My main guess is that for some reason less of the traffic was served from the cache between 7PM EST on April 5th and today around 4:30 EST where it started to go back to normal.

**Comment by MattIPv4** [comment]
A suggestion for improving caching here would be to increase the age on the cache control header for /dist/*.

As I noted in Slack, it seems these are currently served with a max-age of four hours, which seems incredibly low considering these files will never change. Why not set something much higher, like a year?

I have no insight into the Cloudflare config, but it’s worth also checking caching for these files is enabled there. Maybe setup a page rule to ensure they have a long cache configured via Cloudflare directly as well?

**Comment by mhdawson** [comment]
Submitted ticket 1864572 with Cloudflare to see if they are aware of anything that might have caused this or alternatively asking for any suggestions as to what we should look for in our configs that might have caused it.

**Comment by mhdawson** [comment]
I don't see a lot of config options for the caching, the one that seems to match 4 hours is the browser cache TTL. My initial thought is that a different value for that would have necessarily helped. In a lot of cases if downloads are from CI's those probably start with a fresh environment that won't have the cache anyway.

**Comment by MattIPv4** [comment]
Updating that will change caching for the entire nodejs.org site which might not be desirable. And yes, that’s controlling browser cache which wouldn’t have much impact on CI, I agree.

I believe configuring a page rule should be possible though, which can be set to only target /dist/ and allow for a custom cache configuration within Cloudflare, so that Cloudflare will cache and serve assets for longer before going back to the origin server on DO to get a new copy.

**Comment by jgehrcke** [comment]
> I don't see a lot of config options for the caching,

@mhdawson 

- In the "origin" server's nginx config, tweak the Cache-Control headers emitted for the dist/ files -- CF will honor that, and can be told to cache the dist/ files for time scales much longer than 4 hours.
- Be sure to add a `stale-if-error` header because the world does not want to have a single box in the hot path for nodejs downloads (see https://support.cloudflare.com/hc/en-us/articles/115003206852 at the bottom "Toggle Always Online")

**Comment by MattIPv4** [comment]
For example, the page rule might be configured with:

Target: nodejs.org/dist/*
Cache level: Cache everything
Edge cache ttl: a month
Browser cache ttl: a year

**Comment by targos** [comment]
Be careful with these settings. There are files under `dist` that should not be cached too long.
At least `index.json` and `index.tab`

**Comment by rvagg** [comment]
Just diving into this now, here's the variables so far that I can't reconcile:

VM metrics for our main web server over the past 7 days to right now:

<img width="749" alt="20200407_do_www_metrics" src="https://user-images.githubusercontent.com/495647/78610433-2c391a00-78a8-11ea-8924-4165c9ff8217.png">

The most interesting part of that is the spike in bandwidth that takes us up toward what I think is that similar threshold that we were hitting with DO _before_ we went full caching with CF; in theory we shouldn't be seeing that anymore since CF is supposed to take that load from us. Zooming out to 30 days shows this as an anomaly.

But here's CF in the past 24 hours:

<img width="577" alt="20200407_cf_24h_www_metrics" src="https://user-images.githubusercontent.com/495647/78610549-702c1f00-78a8-11ea-8a08-dbcfebc9568a.png">

Zoomed out to 7 days:

<img width="570" alt="20200407_cf_7d_www_metrics" src="https://user-images.githubusercontent.com/495647/78610559-76ba9680-78a8-11ea-9194-f76b8f8a48c0.png">

Looks entirely normal.

_Plus_ we do have load balancing with CF and the CF load balancing logs (available through the dashboard @mhdawson) show zero events! So at no point does CF admit to having to switch between our primary+secondary.

So two puzzles:

* Why is DO bandwidth spiking like this?
* Why isn't CF reacting to unresponsiveness if there is in fact unresponsiveness on the backend?

I want to blame both of them, but that's kind of weird. For now at least it seems to have subsided.

One scenario where this might be explainable:

* Someone has our backend address and is hitting it directly (DoS?)
* It's not being hit _quite_ enough to trigger CF LB thresholds

I just don't understand that second bit, if users are experiencing such pain, why wouldn't CF's LB algorithm be kicking in to deal with it.

**Comment by MattIPv4** [comment]
If modifying the origin is an option, then setting a long max-age for dist, as well as including immutable & stale-if-error should encourage Cloudflare to do much more aggressive caching of these assets.

**Comment by MattIPv4** [comment]
> Someone has our backend address and is hitting it directly (DoS?)

Cloudflare has their full ranges public, if this hadn’t been done already, why not configure the origin with a firewall that only lets those in?

**Comment by nschonni** [comment]
nginx config is over here https://raw.githubusercontent.com/nodejs/build/master/ansible/www-standalone/resources/config/nodejs.org

**Comment by rvagg** [comment]
> Interestingly it also seems like the cached bandwidth on cloudflare as a ratio to total traffic is going back up. That started at around 4:30 EST PM today based on the graph. As of 5:15 EST is was down to 14% versus 50% when we saw bad performance. It started to go up in terms of the uncached percentage around 7PM EST on April 5th.

I couldn't see this in the graphs by the time I got to the Cloudflare dashboard--probably because of the way it aggregates so the 24 hour period I was looking at was delayed from @mhdawson's observation.

So, I've used the Cloudflare API to pull out as much data I could. We have a limit on the number of days we can go back unfortunately so I can't see a weekly pattern (which is usually important for our download stats).

1 minute intervals of `cachedBytes / bytes`, plotted to show the spread gives a very interesting picture. Times are UTC:

<img width="1112" alt="20200407_cf_cached_percent_1m_samples" src="https://user-images.githubusercontent.com/495647/78624604-60730180-78cd-11ea-9232-9b9464f94753.png">

We have regular cache purges of nodejs.org content and it's a pretty blunt instrument that we use when we deploy new assets to the website. It's something we need to improve and it explains some variation in cached %. You can see some dips in the graph for previous days that probably (we could check) line up with the deployment of nightly and v8-canary builds that happen daily and cause an purge. But the recovery is quick. The anomaly on this graph shows massive cache invalidation, huge variation across time, and no linear recovery pattern, it's just on then off and back to normal on the right side of the graph.

... Therefore, I'm inclined to believe there's some hiccup in Cloudflare's caching process that caused an anomaly block. That, in turn, hammered our server with a pattern that was very similar to what we had last year that finally forced us to fully front our servers with Cloudflare. But we didn't get any load balancing failover attempts--perhaps our health checks aren't aggressive enough? Perhaps the difference between a health check on `/en/` is trivial because that content is in memory for nginx, while everyone who was trying to download a binary had to reach in to disk. So the health check wasn't able to test the full I/O on the server and measure its real stress levels.

**Comment by rvagg** [comment]
Since this is no longer "active" I'll close this and we can move diagnosis discussion to #2264

**Comment by johnny88** [comment]
Thanks again for fixing this, really appreciate it!
