### ISSUE TITLE
Access to ARM VM?

### ISSUE THREAD

**Issue by ronag** [nodejs/build#2291]
I'm trying to resolve an issue that only seem to occur on ARM. However, I do not have access to any machine where I can reproduce and debug. Would it be possible for me to gain temporary access to such a VM?

https://ci.nodejs.org/job/node-test-binary-arm-12+/5335/
https://github.com/nodejs/node/pull/29656

**Comment by addaleax** [comment]
SGTM

**Comment by sam-github** [comment]
SGTM

If I can ssh in, I can give you the access, but I'm not very familiar with the arm machine setup. I had trouble finding the machine names from above. It might even be that builds happen on one machine but tests run on other machines.

I'd need the name of the machine(s) from https://ci.nodejs.org/computer/ that you need access to, and confirmation that https://github.com/ronag.keys is the key you'd want to use.

**Comment by ronag** [comment]
> I'd need the name of the machine(s) from ci.nodejs.org/computer that you need access to, 

Not really sure... I guess an ARM machine which can build Node? Sorry for being vague.

> and confirmation that @ronag.keys is the key you'd want to use.

Confirmed.

**Comment by rvagg** [comment]
Getting in to the Pi cluster is a bit of an involved process and compilation is very slow (we cross-compile for these because of this).

Would you mind trying out on different hardware first? test-scaleway-ubuntu1804-armv7l-1 (and its 2 friends) aren't being used currently, we've removed them from CI for now. They're ARMv7 hardware but are faster than the Pi's so not unreasonably slow to get a compilation and test run on.

I've put your key into test-scaleway-ubuntu1804-armv7l-1, you can log in with `ssh root@212.47.233.202`. Might be best to switch to user `iojs` to do your clone, compile and test.

If you can't replicate it there then we'll get you set up on a Pi; it's very possible that your bug only shows up when running in very slow environments. Maybe a race condition that is masked by faster processors.

**Comment by ronag** [comment]
Hm, I am not able to reproduce the issue on that machine :/

**Comment by ronag** [comment]
@rvagg Thank you. The problem has been resolved. I no longer require access to the machine.
