### ISSUE TITLE
Set up second OSX1015 release machine

### ISSUE THREAD

**Issue by AshCripps** [nodejs/build#2309]
Ive set up the [jenkins agent](https://ci-release.nodejs.org/computer/release-orka-macos10.15-x64-1/) for the ORKA release machine and have followed the instructions here -> https://github.com/nodejs/build/blob/master/ansible/MANUAL_STEPS.md#release--machines. But I cant do the final step because I dont have access to the release secrets. cc @rvagg 

Also what is the general smoke test for a new release machine? just add it to the job and then check the new nightly?

**Comment by sam-github** [comment]
Try a https://ci-release.nodejs.org/job/iojs+release/build?delay=0sec and kick off a "test" job, twice (I never do the others, release, rc, nightly). One of the two jobs is going to be on the orka machine, one on nearform.

What exact step can't you do? If you can ssh into any release machine (and you can, the nearform), then you can copy the .ssh directory over to the orka release machine.

**Comment by AshCripps** [comment]
The notorization keychain step

**Comment by sam-github** [comment]
If you don't have access tomorrow I'll do those steps in the morning. I'll have to ssh into release-orka-macos10.15-x64-1 and do them there, right? I just verified I have ssh acces.

**Comment by rvagg** [comment]
happy for #2310 to go through so @AshCripps can do it unassisted to make sure my docs and the assets I've left are correct & enough

**Comment by AshCripps** [comment]
test builds:

https://ci-release.nodejs.org/job/iojs+release/5984/nodes=osx1015-release-tar/

but https://ci-release.nodejs.org/job/iojs+release/nodes=osx1015-release-pkg/ doesnt seem to picking up the orka machine even though it has the correct label

**Comment by richardlau** [comment]
> 
> 
> test builds:
> 
> https://ci-release.nodejs.org/job/iojs+release/5984/nodes=osx1015-release-tar/
> 
> but https://ci-release.nodejs.org/job/iojs+release/nodes=osx1015-release-pkg/ doesnt seem to picking up the orka machine even though it has the correct label

Isn't it waiting for https://ci-release.nodejs.org/job/iojs+release/5984/nodes=osx1015-release-tar/ to finish first?

**Comment by AshCripps** [comment]
Yes you are right, forgot jobs arent concurrent on the same machine running now -> https://ci-release.nodejs.org/job/iojs+release/5985/nodes=osx1015-release-pkg/. The tar job passed.

**Comment by AshCripps** [comment]
Looks like the pkg build passed and was notorized, we now have 2 osx1015 release machines!

**Comment by rvagg** [comment]
For newer jenkins-release-admins folks: please make sure you include both the commit _and_ the date string in non-release builds (test in this case). There's a lot of pieces in the chain that assume a certain format and it's best to conform to it. @AshCripps, your files are sitting in staging, not being promoted, because the promote scripts can't figure out what they are. In this case it's looking for a regex that will help it say "ah, it's a `custom` but the filename tells me it needs to go into the `test` directory, and there's an associated regex for that. https://github.com/nodejs/build/blob/37ffa593f214d467cbaf12280dfa97473a8206eb/ansible/www-standalone/tools/promote/settings#L12-L14 The date in the name also helps with ordering when looking at the list: https://nodejs.org/download/test/ (there's going to be more v15.0.0-test builds in the next 6 months).

Continuing on the other discussion today about enforcing `$commit`, if we can enforce commit and datestring then that would be nice too. datestring isn't strictly required for release builds but it's not a problem if it's there.
