### ISSUE TITLE
WG Membership - Larson Carter

### ISSUE THREAD

**Issue by larson-carter** [nodejs/build#2324]
Hello,
My name is Larson Carter.

I'm wanting to get more heavily involved in the node family!

This repo/project/role here is one of the best fits for me. I have a lot of sysadmin experience. I would probably say more than my programming experience. I would like to help out with managing servers and the services. 

I was going to make a PR based off https://github.com/nodejs/build/pull/524 however that PR is so old. I didn't know what places to put my name, so that is the reason for this issue. So if someone could guide me where to place my name. I'm interested in contributing to all areas.
* Infra
* Jenkins
* Releasing
* Release-Jenkins
* I'm sort of interested in GitHub bot however that is the area where I have the least experience.

> Depending on the level of trust and competence assessed by existing Build WG members, new members may not be given immediate access to protected resources. This is at the discretion of the Build WG. We ask that you not take offence if we appear slow to grant access to resources you ask for as we take our responsibilities regarding security and the stability of our infrastructure very seriously.
I also completely understand this and I can't agree more. Stability, speed, community outreach are my top 3 priorities.

**> The WG meets every three weeks on a Zoom Webinar, schedule is available on the Node.js Foundation calendar. A designated moderator approved by the WG runs the meeting. Each meeting should be published to YouTube.**
I'm 100% able to join every meeting every 3 weeks. My schedule is often flexible but life does happen sometimes. Other than random occurrences happening I will be in attendance.

> Moderation Policy
> The Node.js Moderation Policy applies to this WG.
>Code of Conduct
> The Node.js Code of Conduct applies to this WG.**

I 100% agree to both the Moderation Policy and the Code of Conduct

Please let me know how I can actually file the PR. I just don't want to mess with it syncing to the private org.

Thank You!

**Comment by rvagg** [comment]
Hi @larson-carter, it's great to have your interest!

A couple of recent threads that might be worth reviewing that discuss membership and things that can be done around here. https://github.com/nodejs/build/issues/2171 https://github.com/nodejs/build/issues/2197

The main barrier is building a trust relationship, mostly that involves just showing up to discussion--here and in meetings and even in IRC (Freenode #node-build). It hasn't been straightforward for us to find easy onboarding mechanisms for new folks that we have no existing relationship with, so the challenge is in building that relationship. It's been easier to deal with people from well established companies, particularly those with some kind of relationship with Node.js because we can build that trust relationship much easier than someone unaffiliated that we've never had contact with before. I hope you understand the challenges here. But please don't let that dissuade you, it just means that you have to work on visibility and being able to offer help where you can. We have multiple levels of access to resources that we use for onboarding people, but we don't usually offer any of that straight away unless we have some relationship already in place.

If there's something in particular that grabs you about what we're doing that you think you could improve or address then let us know. Perhaps there's something that we're not properly dealing with now that doesn't require deep access to anything that you could help out with and get the ball rolling!

Any questions that come up, fire away, here or in new issues.

**Comment by larson-carter** [comment]
Alright thank you for the reply. I'm going to go part by part and give some replies!

**> A couple of recent threads that might be worth reviewing that discuss membership and things that can be done around here. #2171 #2197**
I took a look at these and I'll definitely look a them again.

**> The main barrier is building a trust relationship, mostly that involves just showing up to discussion--here and in meetings and even in IRC (Freenode #node-build).**
I completely understand this. Main question for me is. What software do you use to join the IRC? Is there a website that will track my username across devices?

**> It hasn't been straightforward for us to find easy onboarding mechanisms for new folks that we have no existing relationship with, so the challenge is in building that relationship.**
I'm certainly going to try to work on building trust/a relationship right now!

**>  I hope you understand the challenges here. But please don't let that dissuade you, it just means that you have to work on visibility and being able to offer help where you can. We have multiple levels of access to resources that we use for onboarding people, but we don't usually offer any of that straight away unless we have some relationship already in place.**
Yep, I completely understand. I value that too, it overall makes things a lot easier in the open source world.

My only real question is the IRC. So if I could get an answer to that I will be set.

**Comment by devsnek** [comment]
@larson-carter there are a lot of irc clients available. i think one of the more popular ones is irccloud, but if you like you can just join directly using https://webchat.freenode.net/#node-dev

**Comment by larson-carter** [comment]
@devsnek Alright, I just joined irccloud and joined the channel

**Comment by rvagg** [comment]
A bunch of people in #node-build interact with it via Slack. I'm not sure what slack that is that has a bridge, I prefer just plain IRC for this, but that's an option too that others may be able to fill in.
