### ISSUE TITLE
About stripping node binaries 

### ISSUE THREAD

**Issue by Aschen** [nodejs/build#2367]
I noticed that stripped Node binaries are ~10% smaller. 
Is it intended to keep the object and debug information into the released binaries?

Node.js 14 binary is `72.4MB` and the stripped version is `62.4MB`

**Comment by mmarchini** [comment]
> Is it intended to keep the object and debug information into the released binaries?

It is. Many tools used for observability in production relies on non-stripped binaries to work properly. Also, it's possible to strip the binary afterwards in cases where the users what to do it, whereas it's not possible to reverse the stripping without having the contents that were stripped (which would make the bundle size almost equal as a non-stripped binary anyway). Because of that, official builds on nodejs.org are not stripped.

**Comment by Aschen** [comment]
OK that's what I thought, thanks!
