### ISSUE TITLE
Update Jenkins to 2.235.2 (Security Advisory)

### ISSUE THREAD

**Issue by bnb** [nodejs/build#2384]
There was just a Jenkins security advisory sent out in addition to a new release, addressing a handful of security issues around XSS (at least, in the case of the ones that are potentially relevant to us). Would likely be nice to consider trying to update here shortly ❤️ 

Reference: https://www.jenkins.io/security/advisory/2020-07-15/

**Comment by Trott** [comment]
@nodejs/jenkins-admins

**Comment by AshCripps** [comment]
@nodejs/build-infra will be the only ones capable of an update

**Comment by Trott** [comment]
Doesn't need to be on the build-agenda....unless no one is available to do the upgrade....labeling just in case.

**Comment by mhdawson** [comment]
I think @rvagg, @jbergstroem have done most of the updates in the past.  Maybe its an opportunity for @AshCripps to pair with one of them on the update?

**Comment by rvagg** [comment]
Sorry, I get these notices via email and I thought I'd taken care of this one but I was on holiday last week and everything's a bit blurry so I must be mixing it up with the plugins update that came just prior.

We get updates via the apt repositories on our Jenkins servers but it's a pretty brutal restart when it happens so normally I do it in my afternoons (AEST) when it's quietest but it usually also requires doing the "Prepare for Shutdown" from the admin menu so people can't start new jobs and hold it up even further -- although that's problematic because it blocks the flow-on jobs like post-to-github so you have to go through cycles of cancelling the shutdown and preparing again.. very awkward and usually best to wait until _nothing_ is happening.

**Comment by rvagg** [comment]
done, and plugins updated too
