### ISSUE TITLE
Jenkins was out for awhile today

### ISSUE THREAD

**Issue by Trott** [nodejs/build#2386]
Here's a copy/paste fo a conversation I had with myself in IRC today. Putting it here to document the outage and what I did to get Jenkins working again.

```
11:14 AM node-stress-single-test stopped working for me in the last half hour or so. I fill in all the parameters for starting a job, submit the form, and then.... no job ever seems to get queued. I'm sure there's somewhere in the interface I can look to see what's going on, but... not sure where.
11:14 AM I ran https://ci.nodejs.org/job/node-stress-single-test/127/, but have submitted, like, 5 jobs since then.
11:15 AM Keep hoping "this is the one that will work!"
11:16 AM Build history is weirdly empty for everything. Maybe we filled up a disk or something? 
3:18 PM Was hoping leaving it alone for a few hours would see it self-heal, but nope....
3:21 PM Looks like my disk-full suspicion may have been correct.
3:21 PM java.io.IOException: No space left on device
3:41 PM Going to clear the workspace of node-stress-single-test on test-packetnet-ubuntu1804-x64-2 to see if that helps. I don't expect it will, but not sure what else to do at this moment.
4:04 PM Didn't help.
10:31 PM It looks like the git-rebase task has over 1000 jobs saved. I'm going to save the first 1000 and delete the rest to see if that gets CI working again.
10:32 PM That did it!
10:32 PM Here's what I ran in script console in Jenkins:
```

```groovy
MAX_BUILDS = 1000 // max builds to keep

def jobs = Jenkins.instance.items;

for (job in jobs) {
  if (job.hasProperty("builds")) {
    println "Job: " + job.name
    def recent = job.builds.limit(MAX_BUILDS)
    //println "Recent Builds: "  + recent
    //println "============================="
    for (build in job.builds) {
        if (!recent.contains(build) && !build.isBuilding()) {
            println "Deleting: " + build
            build.delete()
            println ""
        }
    }
  }
}
```

**Comment by Trott** [comment]
Ran the script again with `MAX_BUILDS = 500` because Jenkins was not starting jobs again.

**Comment by Trott** [comment]
That deleted  a lot more stuff obviously, and Jenkins is running again. But this seems like something that we should take steps to prevent from happening?

**Comment by Trott** [comment]
@nodejs/jenkins-admins

**Comment by rvagg** [comment]
Sorry, could be me, I'm currently cleaning disks on the workspace machines in response to seeing this issue but have been taking them offline to do it. Will finish up what I'm doing and then figure out what the specific problem is here.

**Comment by rvagg** [comment]
This should be all done now, it looks like it's running fine again

I took each of the workspace machines offline, then removed their workspaces entirely, updated the .jar, cleaned out some of the temporary stuff in ~iojs, and did system updates. The 3rd machine (ibm) was offline because of a Java memory problem but it's back online now. So we're back down to minimal disk, starting again without the need for massive indexes so we should have some time again before it starts to clog up again.

I'm not sure what can be done to automate this kind of thing, workspace sprawl just seems to be a jenkins problem. I suppose there might be some plugin or option that can help deal with it. These workspace machines deal with a lot of data, pretty much every parent job gets run through them, plus they deal with linting too. So they have big disks for that purpose and in theory should be fine for, say, ~6 months but occasionally need a bit of love and cleaning.
