### ISSUE TITLE
Request to join @nodejs/build-infra

### ISSUE THREAD

**Issue by mmarchini** [nodejs/build#2418]
I mentioned this on IRC and https://github.com/nodejs/build/issues/2362#issuecomment-667575361, but I think we need a couple more folks on build-infra to help with incidents on the infra machines. With that in mind, I'd like to join @nodejs/build-infra to help with incidents where build-infra access is required. I'm a Netflix employee (Netflix is a OpenJS member), TSC member, OpenJS CPC regular member, and already am a Build WG member, which should cover the "trust requirement" of joining the team.

I have good time availability to deal with incidents, have experience with Linux/Unix operations (it's part of my job and has been part of previous jobs as well), and have helped with/managed incidents in our test machines in the past (https://github.com/nodejs/build/issues/2351, https://github.com/nodejs/build/issues/2352, https://github.com/nodejs/build/issues/2256, https://github.com/nodejs/build/issues/2238, https://github.com/nodejs/build/issues/2230). When investigating issues I'm always cautious and ensure fixes won't have unwanted side effects before executing, and I prioritize open communication by updating on IRC if I'm investigating ongoing issues, and opening issues on the repo for each incident (either while working on it, or if it's an already known incident with quick fix right after it's fixed).

Let me know what you think :)

**Comment by rvagg** [comment]
FYI this is being discussed (just so you know it's not being ignored), will update shortly

**Comment by rvagg** [comment]
Sorry for the delay, entirely on my end as usual. We had a quick chat about this and are all :thumbsup: but we'd like to on-board @richardlau at the same time too, who's agreed to join in the fun as well.

There's a few challenges that make this a bit tricky:

1. On-boarding - it'd be good to have at least myself and @mhdawson together in a private Zoom to do the on-boarding, @joaocgreis and @jbergstroem too if we can wrangle it. But also including @richardlau we're _almost_ at peak terrible-timezone-overlap. So finding a time to do it might be a challenge. Even our regular meeting time slot(s) are awkward for someone each week.

2. Documentation & enumeration of the implicit - we've maintained a relatively small and tight group for so long that a lot of the things we do and know are more implicit than explicit. We know (mostly) how to not step on each-others toes and not because we have a well documented process. We're going to have to not only document this, but in many cases figure out what we've been doing to make it work! It's not a big deal I think, but there are some ways we can screw things up pretty bad if we go tinkering with things when it's not our place to do so or mess with things that someone else is actively working on. We also have a good sense of who "owns" what and who to defer to, so we might need to be explicit about that. I think the process of on-boarding will actually be a good chance to figure some of this stuff out so we ought to be prepared to turn it into some kind of documentation in the process.

3. Relationship management - as an extension to point 2, we do some juggling of relationships with our various donors, and a lot of this is also not documented at all, it exists in our heads to various degrees and we know who to defer to and who to ask when things are uncertain. We need to keep our donors happy and not over-extend friendships. We have explicit limits/quotas on some services but others we have grey areas that we have to carefully navigate. e.g. on SoftLayer we don't have an explicit limit I think, but I trust @mhdawson to keep that one in check, @joaocgreis handles everything Azure, we have a Droplet quota on DO but have some flexibility on other services (like block devices) that we need to keep tight check on. None of our donors are "do what you like" and most of them need careful tending and ongoing maintenance of the relationships. It can be sensitive and it'd be good to not rock boats too much - but it would also be good to share the load of handling this too.

Let's try and get an on-boarding scheduled, but it might also be a good idea to begin a list of things such an on-boarding will need to cover. That might go into a separate issue I think.

**Comment by richardlau** [comment]
@mmarchini Would you be able to make the timeslot of yesterday's Build WG meeting (https://github.com/nodejs/build/issues/2427) but next Tuesday (15 September) for onboarding? That was the time suggested in the meeting (https://github.com/nodejs/build/pull/2430) to get yourself, me, @mhdawson and @rvagg together on a private Zoom to do some onboarding.

**Comment by mmarchini** [comment]
Yes, same time next week works for me

**Comment by mhdawson** [comment]
@richardlau can you send out an invite?

**Comment by rvagg** [comment]
include @joaocgreis and @jbergstroem too, hopefully they might able to make it too as they have key pieces of the puzzle in their heads too.

**Comment by richardlau** [comment]
> 
> 
> @richardlau can you send out an invite?

Invites have been sent to @mmarchini, @mhdawson, @rvagg, @jbergstroem and @joaocgreis

**Comment by mhdawson** [comment]
@richardlau can you drop and re-add me. I think I was confused when I looked at next week and deleted it.

**Comment by richardlau** [comment]
> 
> 
> @richardlau can you drop and re-add me. I think I was confused when I looked at next week and deleted it.

done

**Comment by jbergstroem** [comment]
11pm for me but I will try to make it!

**Comment by mhdawson** [comment]
@mmarchini is an infra admin so I believe this can be closed.
