### ISSUE TITLE
Node.js Security Release Sep 15 2020

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#2429]
As pers Node.js security release process this is the issue to request WG members are available to fix any CI issues.

@richardlau has already volunteered to lock/unlock the CI on the day of the security release.

**Comment by richardlau** [comment]
https://github.com/nodejs/node/blob/master/doc/guides/security-release-process.md says to lock the CI down 24 hours before release, so I've locked the CI down now and posted in https://github.com/orgs/nodejs/teams/collaborators/discussions/107.

**Comment by gengjiawen** [comment]
Looks like this time take very long. Any estimate time we can use CI again ?

**Comment by richardlau** [comment]
> 
> 
> Looks like this time take very long. Any estimate time we can use CI again ?

No. We're still trying to get a clean CI for one of the patches.

**Comment by richardlau** [comment]
CI is unlocked and releases are out.

**Comment by nschonni** [comment]
Can someone trigger the "unofficial builds" so we can get the Alpine binaries for docker-node?

**Comment by gengjiawen** [comment]
> Can someone trigger the "unofficial builds" so we can get the Alpine binaries for docker-node?

You probably need to open issue in https://github.com/nodejs/unofficial-builds.

**Comment by rvagg** [comment]
FYI the holdup is this https://github.com/nodejs/unofficial-builds/issues/22

something we need to get fixed since alpine depends on the musl builds being available. I'd suggest someone could help by modifying the scripts in that repo but without access it's a bit hard to test it out! It's really down to myself and @mmarchini at the moment who have access and a bit of a clue about how it all works.
