### ISSUE TITLE
create ansible script for jenkins host

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#243]
collecting things that needs to be done:
- [ ] add the jenkins-ci upstream package repo for ubuntu 14.04 lts
- [ ] interact with `dotgpg` for secrets
- [ ] optional rsync backup step
- [ ] set up initial firewall that blocks incoming ipv6 on eth0
- [ ] add a ipv4 firewall with a specific chain for jnlp clients
- [ ] create a ansible helper that adds to the jnlp firewall

**Comment by rvagg** [comment]
fwiw I used https://github.com/redbo/cloudfuse a bit when transferring the nodejs.org server to its new location. It has copies of a lot of the important data from the old server. I haven't used it since but we could start using it for things like jenkins backups. There is a limitation about permissions, however, I don't think you can store that kind of metadata on the rackspace cloud files.

I'd really love to get backups for Jenkins and nodejs.org off DigitalOcean and into some kind of object store or other unmanaged storage space.

**Comment by joaocgreis** [comment]
- [ ] Add `-Dhudson.slaves.ChannelPinger.pingInterval=2` to `<arguments>` in `jenkins.xml`, to support Azure slaves.

**Comment by rvagg** [comment]
@joaocgreis is this why we haven't been seeing so many failures of late? can you explain why this worked?

**Comment by joaocgreis** [comment]
@rvagg yes, the connection to Azure slaves should be fixed now. Azure has a load balancer that closes connections after 4 minutes of inactivity, and the default ping interval of Jenkins is 5 minutes. The Linux slave I created has `ClientAliveInterval 120` set explicitly in `sshd_config`, that's why ssh works so well. (Ref: https://github.com/nodejs/build/issues/232)

**Comment by gdams** [comment]
@jbergstroem can this be closed? I think that the jenkins worker playbooks are now complete
