### ISSUE TITLE
Moving away from gitter

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#247]
A few people (including me) aren't very happy with gitter and would like to move away from it. The options as I see it are IRC and slack.

Lets discuss why we should choose the one over the other. My vote would be on IRC (history in Slack is a premium feature) and solving history/backlogging could be done in two ways:

1. add the logging bot already active in other nodejs channels: http://logs.libuv.org/channels
2. using irccloud or a similar "always on" client that buffers while you are away

**Comment by TheAlphaNerd** [comment]
Not a fan of gitter myself.

For clarification, I assume this is working group discussion? 

Unless all node wg's decide to go under a single slack, which may not be a terrible idea, I personally think IRC is the best option.

**Comment by mikeal** [comment]
So, there's no project or foundation-wide policy around this. However, one of the requirements of all projects and WGs is that they are "transparent, participatory, and effective."

To that end systems which introduce significant barriers to entry might be flagged as anti-participatory or anti-transparent. However, you can balance those issues if the tool is effective and you can ensure transparency and participatoryness (not a word) in other ways.

A good example are the meetings many WGs and TCs have. They are not as transparent or participatory as GitHub but are used in such a way as decisions are not made on them without first being adequately serviced on GitHub issues. They then function as "final call" for dissent so that contributions are not held up indefinitely (so that the project remains *effective*).

**Comment by mhdawson** [comment]
I suffer from the problem that I don't have irc open enough either because  updates cause my machine to reboot or the browser crashes or whatever.  Slack (and I think gitter as well) on the other hand sends me an email with a summary of what I've missed and in particular when my name is called out.  I  find that really helps me not being too late with a reply or missing the question completely.  So my first take would be to vote against irc.  Having said that I'm always ready to learn something new if that resolves the problems.   In terms of irccloud I see this "Stay connected for 2 hours" in the free version I'm not sure it would achieve "always on"

**Comment by jbergstroem** [comment]
@mhdawson didn't know irccloud changed their pricing structure which would then imply that we're pushing the burden of payment to a user. that's not good. [ircanywhere](http://ircanywhere.com) is an alternative. Not sure either would solve the 'ping me on email if i'm missing out' though.

**Comment by mikeal** [comment]
wow, @mhdawson just wrote up exactly my current workflow around all these tools I can't seem to use :)

**Comment by bnoordhuis** [comment]
I feel that as an open source project we should prefer open source alternatives over closed source ones, if for no other reason than that it's good to stay neutral and to have control over our data.

IRC has the additional benefit that you can be fairly anonymous.  That's important to some people.

As to logs, I can add the channel to slurp, our IRC bot.

**Comment by jbergstroem** [comment]
@bnoordhuis see [pr](https://github.com/piscisaureus/slurp/pull/5). 

@mikeal, @mhdawson created this: https://github.com/ircanywhere/ircanywhere/issues/276

**Comment by orangemocha** [comment]
What issues did you experience with Gitter? Apparently I have been lucky, but it has always worked seamlessly for me so I have to say I am pretty happy with it. It is also open and free and uses GitHub for authentication, which is nice.

IRC without always-on would be a step back IMO. It would be great if we can figure out a way to make it work for everybody, without requiring people to jump through too many hoops. But if we had to pay for it/irccloud, would it win in a side-by-side comparison with Slack?

**Comment by rvagg** [comment]
I'm a very happy IRCCloud user, I can strongly recommend it ($5 per month). I'm always on. Always have access to logs of discussions that happen when I'm not at the computer, it doesn't take up as many resources as my gitter tab does, and it's snappy (particularly compared to gitter). And the mobile client is good too.

**Comment by DavidTPate** [comment]
An alternative to Slack might be [Rocket.Chat](https://rocket.chat/) it's an open-source alternative. They support things like GitHub authentication which I know the whole authentication scheme for slack is less than ideal for an Open Source collaborative project. I haven't used it much, but tried it out a few times and it seems pretty cool. Would need to research the history retention and such.

**Comment by jbergstroem** [comment]
Another benefit for using IRC is that a lot of nodejs working group members already hang out in node.js or io.js, giving us a nice overlap if they have build-related questions (which as been more frequent as of late)

**Comment by mhdawson** [comment]
Is there an irc channel in use ? I tried node_build today and looked like nobody else was connected

**Comment by orangemocha** [comment]
@mhdawson it's `node-build`

**Comment by Starefossen** [comment]
Just for reference (if anyone happens to stumble upon this) I think most members of the Build WG have transitioned over to the `#node-build` IRC channel on Freenode.

**Comment by jbergstroem** [comment]
Closing this. As mentioned above, feel free to join us at `#node-build` on irc.freenode.net!
