### ISSUE TITLE
Upgrade java used for the jenkins CI server from 8u202

### ISSUE THREAD

**Issue by sxa** [nodejs/build#2492]
I was just looking at the java that hosts ci.nodejs.org and it seems to be Oracle's 8u202 (the last version before Oracle started [restricting the licensing of java 8](https://blogs.oracle.com/java-platform-group/oracle-java-se-releases-faq))

Since this version is now almost two years old I would recommend upgrading it to keep secure, and in the spirit of open source I would reocmmend using a version sourced from AdoptOpenJDK instead of Oracle (Disclaimer - I work at AdoptOpenJDK).

We have discussed this previously in issue #1222 that went stale, but I think we should seriously consider revisiting this and upgrading the CI hosts as a minimum to a more recent 8 (or later version if desired). Using the OpenJ9 variant instead of HotSpot would potentially have memory benefits too. Happy to assist in any way I can of course :-)

**Comment by rvagg** [comment]
Yeah, probably a good idea, but we've learned to be very hesitant about _any_ changes to Java in our Jenkins stack because we've had such a terrible history with Java-related problems being thrown up at random - _when you have something stable, don't touch it!_ is the mentality. It really needs someone dedicated to dealing with potential fall-out from such an upgrade. Otherwise we're just consuming what the OS is feeding us.

**Comment by richardlau** [comment]
Given the Jenkins servers are running on Ubuntu 16.04 and the end of LTS for that is the end of this month we should start planning on updates, including this.

**Comment by richardlau** [comment]
We're now running on Java 17, see https://github.com/nodejs/build/issues/2984.
