### ISSUE TITLE
Missing status label for GitHub check

### ISSUE THREAD

**Issue by danielleadams** [nodejs/build#2493]
When I opened a PR in nodejs/node (https://github.com/nodejs/node/pull/36435), I started the node-test-pull-request job and one of the checks that I received is pictured in the following:

<img width="941" alt="Screen Shot 2020-12-08 at 6 00 32 AM" src="https://user-images.githubusercontent.com/6271256/101475784-c9a68b00-391a-11eb-8d41-dd2ebfa20365.png">

The Details link to: https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu1804_sharedlibs_debug_x64/23997/. The check says `${STATUS_LABEL}` instead of the label that would have been received from Jenkins. 

I'm not sure if this is a bug in GitHub or missing data that is updating the PR.

Update: Once the issue was resolved with the test, the status check is not getting marked as resolved/passed.

**Comment by richardlau** [comment]
I've shuffled around how the GitHub status labels are name in the [node-test-commit-linux-containered](https://ci.nodejs.org/job/node-test-commit-linux-containered) job so that `STATUS_LABEL` is set as early as possible in the job. This should hopefully prevent edge cases were the job fails before `STATUS_LABEL` is set in future jobs.

**Comment by danielleadams** [comment]
thanks @richardlau!
