### ISSUE TITLE
Upgrade Node.js version on node-test-linter job

### ISSUE THREAD

**Issue by aduh95** [nodejs/build#2504]
I got a PR with a [failing linter job on CI](https://ci.nodejs.org/job/node-test-linter/38339/) because it seems the Node.js version on the CI doesn't understand the language features used in https://github.com/nodejs/node/pull/36018.

I can see that in 32544396ae681178cbbca7091719c77dab203f49 (cc @phillipj), Node.js version was upgraded from v10.x to v14.x, yet the job is still failing. The console output in the Jenkins UI doesn't tell what is the `node --version` used for the job, but it seems it's not Node.js 14 (which support those features).

Would it be possible to add the Node.js version used by the linter job in the console output to help contributors understand linter failures? Can we upgrade the Node.js version to v14.x if it's not already in place?

**Comment by richardlau** [comment]
Theoretically yes, but it would require a member of @nodejs/build-infra (of which I am one) to find some time to update the machines. 

The linter job runs on a different set of hosts to the github-bot (which is what https://github.com/nodejs/build/commit/32544396ae681178cbbca7091719c77dab203f49 addressed). For the hosts that run the linter jobs I believe the ansible setup is https://github.com/nodejs/build/blob/2ddeda680b032f03f9d5425142cf62da785f6b86/ansible/roles/jenkins-workspace/tasks/main.yml#L117 but I don't know (without testing) whether we'd need to removed the existing NodeSource repo before adding the one for the later version of Node.js in order to force the update.

Can this wait until the New Year? We have security releases coming in January (https://nodejs.org/en/blog/vulnerability/january-2021-security-releases/) -- with holidays coming up I'm not overly keen on making infrastructure changes until after those are done.

**Comment by aduh95** [comment]
This can certainly wait, thanks for the explanation!
