### ISSUE TITLE
IBM i hosts offline

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2509]
"pending—All nodes of label ‘ibmi72-ppc64’ are offline"

cc @ThePrez 

I can't ssh into any of our IBM i CI hosts (connection is refused) so I'm going to disable https://ci.nodejs.org/job/node-test-commit-ibmi/ for now as it's otherwise preventing the daily builds from completing.

**Comment by ThePrez** [comment]
Well drat. Looks like those systems got rebooted for some maintenance activity and the SSH daemon is not set to autostart. Manually started the ssh daemon and it should be connectable now.

**Comment by ThePrez** [comment]
I've also configured the SSH daemon to be autostarted so hopefully this doesn't occur on future reboots.

**Comment by richardlau** [comment]
I don't appear to be able to ssh into them with the build/test keys 😞.

**Comment by ThePrez** [comment]
The `nodejs` user got disabled, as we've seen happen a time or two in the past.

I queried the history log (for my own future reference, with SQL `SELECT * FROM TABLE(QSYS2.HISTORY_LOG_INFO(CURRENT TIMESTAMP - 24 DAY)) X WHERE MESSAGE_TOKENS like '%NODEJS%'`) and found the profile was disabled on December 18th due to too many invalid signon attempts. 

I've re-enabled the profile and will reach out to the cloud provider next week for a better long-term mitigation approach

**Comment by richardlau** [comment]
Thanks @ThePrez. I've logged in, restarted the agents and reenabled the job.
