### ISSUE TITLE
Disabled node-test-commit-arm-fanned

### ISSUE THREAD

**Issue by Trott** [nodejs/build#2548]
I clicked "Disable project" in the node-test-commit-arm-fanned  page because the Pi tests seem stalled.

Here's my blob of text from the build IRC/Slack:

> Didn't investigate but looks like https://ci.nodejs.org/job/git-nodesource-update-reference/ is not working which means all the Pi tests are stalled?
> 
> That might be a symptom of a different problem rather than a cause. Regardless, Pi tests don't appear to be running or else are taking a long time. 
> 
> Here's one with no active workers that's been running for 16 hours. https://ci.nodejs.org/job/node-test-binary-arm-12+/9474/
> 
> I clicked "Disable project" in the node-test-commit-arm-fanned  page, but I'm not sure that's the right thing to do, so I'm running https://ci.nodejs.org/job/node-test-pull-request/36261/ to see. If that works to remove Pi tests, I'll open an issue in the build repo letting folks know I did that. If it doesn't work, I'll re-enable.

**Comment by targos** [comment]
According to Jenkins, all nodes are offline: https://ci.nodejs.org/job/git-nodesource-update-reference/

![image](https://user-images.githubusercontent.com/2352663/108601372-877ada80-739c-11eb-81f7-d94d5cfe434b.png)

**Comment by rvagg** [comment]
> Disk space is too low. Only 0.045GB left on /home/iojs/build.

Cluster is offline, we burned up disk. I'll get the workspaces cleaned up and do some updates while I'm there.

I think maybe it's time to fully retire the Pi1s from the cluster? It's only enabled for Node 10 now I think but it will be responsible for at least 1/3rd or the space used, even if each node is used just once.

**Comment by mhdawson** [comment]
@rvagg I'd be comfortable with that. I don't think we've seen failures which were specific to Pi1 versus other later Pi's and that couple with the fact that there are only a few months of support left in 10.x means that is is very unlikely that we'll miss something by retiring the Pi1s.

**Comment by rvagg** [comment]
This may not be ideal, but I've just changed the logic in `node-test-commit-arm-fanned` where it selects whether to run `node-test-binary-arm` or `node-test-binary-arm-12+` so that there's only one condition now that's "if node version >= 12, run `node-test-binary-arm-12+`". It means that Node 10 will still trigger a cross-compile and git propagation, just not the binary test, as in https://ci.nodejs.org/job/node-test-commit-arm-fanned/18934/

That will save us on Pi workspaces, and maybe the compile is a nice thing to still test, but it's not very clean. We can remove it after 10 retires (or someone else decides to clean this up in the meantime).

I've re-enabled arm-fanned and am running some initial jobs now to populate workspaces.

**Comment by rvagg** [comment]
I see a lot of green and the shared disk is at 49%, calling this success for now but need to keep monitoring
