### ISSUE TITLE
AIX host build failing around 90% of the time

### ISSUE THREAD

**Issue by Trott** [nodejs/build#2566]
test-osuosl-aix72-ppc64_be-2 is failing a lot. A quick look suggests build failures, not test failures.  

https://ci.nodejs.org/computer/test-osuosl-aix72-ppc64_be-2/builds

Only two of the last 20 builds have passed. (One is in progress.)

![image](https://user-images.githubusercontent.com/718899/110801443-1ce9eb80-8232-11eb-890a-1f24cf197c00.png)

**Comment by Trott** [comment]
@nodejs/platform-aix

**Comment by Trott** [comment]
@nodejs/platform-aix

**Comment by sxa** [comment]
There's a big mix of failures too so it's not just one issue :-(

**Comment by AshCripps** [comment]
Ive taken the host offline to see if I can try and investigate its failures - it seems to just crash part way through the build

**Comment by Trott** [comment]
> Ive taken the host offline to see if I can try and investigate its failures - it seems to just crash part way through the build

It looks like it's still online? (Or maybe you put it back online?) 

https://ci.nodejs.org/computer/test-osuosl-aix72-ppc64_be-2/builds

![image](https://user-images.githubusercontent.com/718899/110972759-34e46c80-8311-11eb-8c3a-dc21694d4435.png)

**Comment by AshCripps** [comment]
Ive stripped it off the label for now and am running test builds, I managed to get a build working locally but even jenkins build crashed on the V8 step (hangs for over 10 mins then jenkins kills the build) I currently have a local build running to see if it gets past this step (been stuck for over a half hour now) if not Ill keep the label removed and get support to have a look at the machine.

**Comment by AshCripps** [comment]
machine "fixed" and added back to the pool. Turns out it was a parallelisation issue and running a build on that machine with anything bigger than `JOBS=3` caused it to hang on a V8 instruction. Ive set this machine to 3 and removed the hardcoded value from the job which means the other machines will use the value of 6 added in their startup scripts. I will open a PR to explore moving `JOBS` to a machine specific variable for AIX
