### ISSUE TITLE
Moving nodejs.dev to an openjs foundation google cloud billing account

### ISSUE THREAD

**Issue by benhalverson** [nodejs/build#2580]
I'm a member of the nodejs.dev team working on the Google calendar integration. I was wondering if someone can help move the nodejs.dev google billing account from a personal account to an OpenJS Foundation billing account.

Some additional context is in this issue: https://github.com/nodejs/nodejs.dev/issues/883#issuecomment-799482096

**Comment by MylesBorins** [comment]
Some extra context is that I made a nodejs GCP account and have the billing account directly attached to my credit card right now. It hasn't been an issue because we've stayed within the free tier up until now... that said I've also bee one of the only people managing it.

If we are going to expand usage / access I'd like it moved off my personal billing account.

/cc @brianwarner

**Comment by MylesBorins** [comment]
One more thing worth adding... I actually have a custom billing account setup for Node.js that has another $187 of credits on it that expire in April. I would just need to add someone else to this account and have the credit card changed.

**Comment by brianwarner** [comment]
@MylesBorins I believe if you add me to the account, I can attach the Foundation's billing profile?

**Comment by MylesBorins** [comment]
This is completed
