### ISSUE TITLE
Disabled Raspberry Pi (node-test-commit-arm-fanned) in CI

### ISSUE THREAD

**Issue by Trott** [nodejs/build#2583]
There have been only two working Raspberry Pi 3 devices for the past 36 hours or so and I don't know how to fix them. (I couldn't connect via SSH, a few Jenkins commands I tried all failed, and I couldn't find anything in the repo about how to basically get them to reboot if I can't SSH to them. I can SSH to the two online ones just fine, though.)

Refs: https://github.com/nodejs/node/issues/37831

**Comment by richardlau** [comment]
I tried a few of the offline ones and can't ssh into them either.

**Comment by rvagg** [comment]
Have done a cluster restart, they're being updated now, will update here when they're safely back in and I've reenabled arm-fanned

The 3's are particularly unreliable. Something happened early last year (or maybe it was earlier than that) in the software stack that means they lock up and drop off with some regularity. We don't see anything similar with the other models.

More drastic action might be an entire base OS update, but that's quite a time investment I can't afford at the moment, it'll require some experimentation. We do need to refresh our container OS versions though, so there's a bunch of work that could be done at some point. The 1b's should probably be entirely decomissioned while I'm at it since they're basically out of the CI loop now.

**Comment by rvagg** [comment]
Re-enabled, but I'm afk for a while now so I'd appreciate if someone could keep an eye on it in the coming hours. I've pushed a test job through it from master but can't watch it finish.

**Comment by Trott** [comment]
> Re-enabled, but I'm afk for a while now so I'd appreciate if someone could keep an eye on it in the coming hours. I've pushed a test job through it from master but can't watch it finish.

Three out of three arm-fanned jobs have passed so far, so I think we're good for the moment. Thanks!
