### ISSUE TITLE
Jenkins MultiJob plug-in issues

### ISSUE THREAD

**Issue by orangemocha** [nodejs/build#265]
Version 1.19 of the plug-in introduced a bug for which the setting "Build only if SCM changes" is reversed. https://issues.jenkins-ci.org/browse/JENKINS-30952

@joaocgreis worked around this by flipping the setting in all the node-test-\* jobs. https://github.com/nodejs/build/issues/232#issuecomment-156534118

Version 1.20 introduced yet another bug that leads to a NullPointerException in some cases: https://issues.jenkins-ci.org/browse/JENKINS-31527. See https://github.com/nodejs/build/issues/263#issue-118334975 for a few examples of failures in our CI.

It is unclear whether 1.20 solves the issue about the SCM polling setting.

I downgraded the plug-in to version 1.19. I suggest we stick to this version until the above issues are fixed in the plug-in.

**Comment by jbergstroem** [comment]
Issue tracker with a few bugs open about this here: https://issues.jenkins-ci.org/browse/JENKINS-31527?jql=project%20%3D%20JENKINS%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20component%20%3D%20'multijob-plugin'

**Comment by jbergstroem** [comment]
So, in the spirit of forking, does anyone want to take a stab at fixing these so we can get the "build if scm changes" fix?

**Comment by rvagg** [comment]
![screen shot 2016-02-02 at 4 09 58 pm](https://cloud.githubusercontent.com/assets/495647/12740461/748e1880-c9c7-11e5-9c25-59935a0027f7.png)

https://github.com/jenkinsci/tikal-multijob-plugin/commits/master

They appear to think they got that build condition thing sorted out in 1.20. 

As for the NPE, I'd love to see the errors we had in https://github.com/nodejs/build/issues/263#issue-118334975 but the logs are now gone cause of auto-cleanup. If it's the same stack-trace with the same line# as in the JIRA report then it'd be from https://github.com/jenkinsci/tikal-multijob-plugin/blob/master/src/main/java/com/tikal/jenkins/plugins/multijob/MultiJobBuilder.java#L170 which hasn't changed since 1.20 but I'd like to confirm that. It'd be to do with `lastJob` not having a workspace for `getWorkspace()` and probably wouldn't be hard to fix but we'd need a failure case to be able to test it.

Unfortunately this all means upgrading the plugin, trying it out, understanding where our breakage is and fixing from there.

**Comment by jbergstroem** [comment]
We have all old jobs at the backup server. I'll try and find something around when the dates when we complained.

**Comment by joaocgreis** [comment]
Finally fixed by https://github.com/nodejs/build/issues/775 . I hope we don't end up with some different issue like in 1.20.
