### ISSUE TITLE
scripts/release-post.js always fills "Source Code" link with "Coming soon"

### ISSUE THREAD

**Issue by targos** [nodejs/build#2751]
See with version 16.8.0:

![image](https://user-images.githubusercontent.com/2352663/130864183-ae1f7013-4fde-4dbf-8f49-af6a60629ad5.png)

It's been happening for a while now. I didn't open an issue before because I thought it was my fault somehow, but I just saw that it also happened to @danielleadams last week: https://github.com/nodejs/nodejs.org/commit/1cfee5b6ff123962216c3a5030ff0f5cf248151a#diff-f51dba60b01bf6ae650269a3e87fdbefd528776c0c11b35f8a2396408aeaf5d4R150

**Comment by targos** [comment]
The problem is that the specific URL for the source code systematically returns a 404 right after the release is promoted.

**Comment by rvagg** [comment]
weird that it's "Source code" specifically.. full list of existing 'Coming soon':

```
v0.12.18/index.html:SmartOS 64-bit Binary: <em>Coming soon</em><br>
v10.0.0/index.html:Linux 32-bit Binary: <em>Coming soon</em><br>
v10.0.0/index.html:SmartOS 32-bit Binary: <em>Coming soon</em><br>
v10.2.0/index.html:Linux 32-bit Binary: <em>Coming soon</em><br>
v10.2.0/index.html:SmartOS 32-bit Binary: <em>Coming soon</em><br>
v10.4.1/index.html:Linux 32-bit Binary: <em>Coming soon</em><br>
v10.4.1/index.html:SmartOS 32-bit Binary: <em>Coming soon</em><br>
v12.0.0/index.html:ARMv6 32-bit Binary: <em>Coming soon</em><br>
v14.14.0/index.html:Source Code: <em>Coming soon</em><br>
v14.3.0/index.html:SmartOS 64-bit Binary: <em>Coming soon</em><br>
v14.5.0/index.html:Source Code: <em>Coming soon</em><br>
v14.8.0/index.html:Source Code: <em>Coming soon</em><br>
v15.0.0/index.html:Source Code: <em>Coming soon</em><br>
v15.3.0/index.html:Source Code: <em>Coming soon</em><br>
v15.5.0/index.html:Source Code: <em>Coming soon</em><br>
v16.7.0/index.html:Source Code: <em>Coming soon</em><br>
v4.2.0/index.html:ARMv6 32-bit Binary: <em>Coming soon</em><br>
v4.2.4/index.html:ARMv6 32-bit Binary: <em>Coming soon</em><br>
v4.7.3/index.html:Linux s390x 64-bit Binary: <em>Coming soon</em><br>
v4.7.3/index.html:AIX 64-bit Binary: <em>Coming soon</em><br>
v4.9.0/index.html:Linux s390x 64-bit Binary: <em>Coming soon</em><br>
v4.9.0/index.html:AIX 64-bit Binary: <em>Coming soon</em><br>
v5.6.0/index.html:ARMv6 32-bit Binary: <em>Coming soon</em><br>
v6.0.0/index.html:ARMv6 32-bit Binary: <em>Coming soon</em><br>
v6.12.3/index.html:ARMv6 32-bit Binary: <em>Coming soon</em><br>
v6.16.0/index.html:ARMv6 32-bit Binary: <em>Coming soon</em><br>
v6.3.0/index.html:ARMv6 32-bit Binary: <em>Coming soon</em><br>
v7.0.0/index.html:SmartOS 64-bit Binary: <em>Coming soon</em><br>
v7.1.0/index.html:SmartOS 64-bit Binary: <em>Coming soon</em><br>
v7.2.0/index.html:SmartOS 64-bit Binary: <em>Coming soon</em><br>
v7.2.0/index.html:ARMv6 32-bit Binary: <em>Coming soon</em><br>
v7.2.1/index.html:SmartOS 64-bit Binary: <em>Coming soon</em><br>
v7.3.0/index.html:SmartOS 64-bit Binary: <em>Coming soon</em><br>
v7.4.0/index.html:SmartOS 64-bit Binary: <em>Coming soon</em><br>
v8.1.1/index.html:ARMv6 32-bit Binary: <em>Coming soon</em><br>
v8.1.1/index.html:ARMv7 32-bit Binary: <em>Coming soon</em><br>
v8.15.0/index.html:ARMv6 32-bit Binary: <em>Coming soon</em><br>
v8.16.1/index.html:ARMv6 32-bit Binary: <em>Coming soon</em><br>
v8.6.0/index.html:ARMv6 32-bit Binary: <em>Coming soon</em><br>
v8.9.2/index.html:Linux PPC BE 64-bit Binary: <em>Coming soon</em><br>
v8.9.3/index.html:Linux PPC BE 64-bit Binary: <em>Coming soon</em><br>
v9.0.0/index.html:ARMv6 32-bit Binary: <em>Coming soon</em><br>
v9.11.0/index.html:ARMv6 32-bit Binary: <em>Coming soon</em><br>
```

Most of them look old. I can explain the ARMv6 & 7 entries (although they should have been updated!), the SmartOS ones are a bit surprising - maybe we removed those builds without removing it from the script? But "Source code", I don't have any theories for that at the moment.

**Comment by targos** [comment]
For "Source Code", I suspect that there's some external automation that detects the release while we are doing it and tries to download it. Then the 404 error is cached by Cloudflare.
Btw, is it intended to cache non-200 responses?

**Comment by richardlau** [comment]
Promotion is supposed to queue a CDN purge (and the queue processed every five minutes), so there might be a delay between promotion and the downloads being visible but I can't explain why only the "Source code" tarball would be the only one affected.

**Comment by rvagg** [comment]
I think we cache every response type at the edge.

It's a plausible theory. There's a cache purge when you run the promote script but that's on a delay since it's picked up by a cron job. So if you prepare the release post in the time between promote and when the cache purge happens and someone (or something) has attempted to ping the source file based on a signal such as git tag, then I guess we'd end up with a cached 404.

**Comment by rvagg** [comment]
A couple of things we could attempt:

1. Mess around with cache settings for `/dist` / `/download` to avoid caching
2. Come up with a better cache purge mechanism for releases - we increased the cron delay last year iirc because it was happening too quick while the nightlies dribbled in and wanted them promoted and cache purged in larger and fewer batches - but releases are different since we know they're done once, so a purge could be done immediately. It's just the hand-off between privileged processes that's the problem here since we rely on a queue mechanism to pass from the `dist` user (that releasers have access to) and, I think, the `nodejs` user, who has access to the cache purge script and our cloudflare API key. I don't particularly want to give `dist` more access to protected resources since we're not awesome at keeping the access list tidy!

**Comment by rvagg** [comment]
https://github.com/nodejs/nodejs.org/pull/4136 here's one simple option
