### ISSUE TITLE
macOS pkg release build failures

### ISSUE THREAD

**Issue by targos** [nodejs/build#2850]
The last four nightly builds failed. See https://ci-release.nodejs.org/job/iojs+release/8214/nodes=osx11-release-pkg/console

**Comment by targos** [comment]
@nodejs/jenkins-release-admins

**Comment by rvagg** [comment]
https://github.com/nodejs/node/blob/6beee312a47165f8dd65fe802b6280310e6caede/Makefile#L833

that line will need fixing, npm's package.json has a new `"templateOSS"` section with a `"version": "2.4.3"` in it, so `NPMVERSION` is coming out as:

```
8.3.1
    "version": "2.4.3"
```

rather than just `8.3.1` as it would previously have done.

hence:

```
07:10:54 pkgbuild --version v8.3.1     "version": "2.4.3" \
07:10:54 		--identifier org.nodejs.npm.pkg \
07:10:54 		--root out/macos/dist/npm \
07:10:54 		--scripts ./tools/macos-installer/pkgbuild/npm/scripts \
07:10:54 			out/macos/pkgs/npm-v8.3.1     "version": "2.4.3".pkg
```

in the build logs

**Comment by targos** [comment]
Proposed fix: https://github.com/nodejs/node/pull/41575

**Comment by targos** [comment]
Thanks for investigating @rvagg !
