### ISSUE TITLE
Remove Blueocean from Jenkins?

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#2870]
Do we use Blueocean anywhere? Does anyone rely on it? I know we experimented with it a while back but I don't think it's become part of our normal workflow .. or has it? The plugins never get updated because they don't maintain compatibility with the LTS Jenkins we run (or maybe any version? do they still maintain Blueocean? I don't know).

Basically - can we remove it and will anyone yelp if we do?

**Comment by sxa** [comment]
IMHO it can provide really useful visualisations ... when it works. Unfortunately I'm not sure it does in our instance. When I tried it against a run of node-test-commit just now it spun for a while then timed out with `An error occurred during a connection to ci.nodejs.org. PR_END_OF_FILE_ERROR`. If it was able to display the whole set of subjobs from a node-test-commit it would be far more useful, but in the absence of being able to make that work it probably just causes confusion so perhaps should be removed. Interested to hear if anyone else uses it, or has investigated why it's problematic (Quite probably due to being out of date as Rod says...)

**Comment by mmarchini** [comment]
Can we disable it before removing? That way we can keep it disabled for a bit and if anyone scream we know it was being used. If no one screams we can just go ahead and remove it.

**Comment by rvagg** [comment]
> Can we disable it

Yes, I believe we can. Good idea. I'll do that now.

**Comment by rvagg** [comment]
OK, I've disabled everything with "Blue Ocean" in its name; it took a few loops through the list because you can't disable things that have dependents but eventually after unticking everything I could they all got disabled. https://ci.nodejs.org/pluginManager/installed

Let's see if anyone yelps.
