### ISSUE TITLE
Some coverage pages are missing

### ISSUE THREAD

**Issue by tniessen** [nodejs/build#2985]
Example:

- JavaScript: https://coverage.nodejs.org/coverage-ea9943158654bca9/index.html
- C++: https://coverage.nodejs.org/coverage-ea9943158654bca9/cxxcoverage.html

**Comment by mhdawson** [comment]
We do delete coverage data because we only have so much storage. I suspect this it what's happened in this case unless these are more recent.

**Comment by richardlau** [comment]
According to Jenkins the job has been broken for over a month
![image](https://user-images.githubusercontent.com/5445507/177194350-56a02e40-0417-4884-9aa4-1afa9758a818.png)
failing due to the rsync process timing out:
e.g. https://ci.nodejs.org/view/Node.js%20Daily/job/node-test-commit-linux-coverage-daily/lastFailedBuild/nodes=benchmark/console
```console
04:16:23 + rsync -r out coveragedata:coverage-out
04:16:23 Build timed out (after 30 minutes). Marking the build as failed.
04:46:23 rsync: connection unexpectedly closed (96469308 bytes received so far) [sender]
04:46:23 rsync error: unexplained error (code 143) at io.c(226) [sender=3.1.1]
```

I'm guessing even the recent pages that appear to be there may be incomplete uploads.

This usually means it is time to prune older results, which is a manual process involving three different machines 😞. As I've stated in #nodejs-build in Slack, fixing coverage.nodejs.org is not high priority and the long term goal is to shift fully to codecov.io (https://github.com/nodejs/build/issues/2797).

**Comment by tniessen** [comment]
@richardlau Should we close this now that codecov appears to be working for the most part?

**Comment by richardlau** [comment]
@tniessen Yes, let's close. I plan to land/deploy https://github.com/nodejs/build/pull/3145 after I'm back at work in two week's time and that is going to end up also removing the bits that update our own hosted coverage.

**Comment by richardlau** [comment]
FWIW I've created a CloudFlare Page Rule to permanently redirect coverage.nodejs.org to https://codecov.io/gh/nodejs/node: https://github.com/nodejs/build/pull/3145#discussion_r1197985902
