### ISSUE TITLE
better access windows vm for collaborators

### ISSUE THREAD

**Issue by gengjiawen** [nodejs/build#2999]
Recently we deal with a windows related fix https://github.com/nodejs/node-gyp/pull/2565 takes really long to test.
I am thinking is there a better way to give collaborator better access to windows VM.

We also have many v8 issues related to windows. ( I am switch to mac, hard for me to deal with more)

cc @mhdawson

**Comment by gengjiawen** [comment]
Not sure can azcure give free hours to collobarator account or codespace support windows.

**Comment by mhdawson** [comment]
@gengjiawen I meant people with time to manage giving access versus cpu cycles themselves although that is an issue as well since we have been using up our Azure allocation pretty quickly.

Ideally there would be some way people would ask for Azure access directly from MS and they would be granted some cycles based on being on the Node.js collaborator list.
