### ISSUE TITLE
aix72-ppc64 fails to load /opt/freeware/libexec64/git-core/git-remote-https

### ISSUE THREAD

**Issue by tniessen** [nodejs/build#3031]
`aix72-ppc64` appears to be failing reproducibly:

```
17:33:50 + git clone --depth 1 https://github.com/nodejs/build.git
17:33:50 Cloning into 'build'...
17:33:50 Could not load program /opt/freeware/libexec64/git-core/git-remote-https:
17:33:50 Symbol resolution failed for /opt/freeware/lib64/libkrb5support.so because:
17:33:50 	Symbol _GLOBAL__AIXI_libintl_so (number 58) is not exported from dependent
17:33:50 	  module /usr/lib/libintl.a[libintl.so.8].
17:33:50 	Symbol _GLOBAL__AIXD_libintl_so (number 59) is not exported from dependent
17:33:50 	  module /usr/lib/libintl.a[libintl.so.8].
17:33:50 Examine .loader section symbols with the 'dump -Tv' command.
17:33:50 Build step 'Execute shell' marked build as failure
```

This appears to have happened in every build since some time this morning (UTC).

**Comment by richardlau** [comment]
Probably due to some package updates when I ran the Ansible scripts this morning for https://github.com/nodejs/build/issues/3030
```
Sep 14 12:05:21 Updated: libiconv-1.17-1.ppc
Sep 14 12:05:22 Updated: ca-certificates-2021.2.52-3.ppc
Sep 14 12:05:26 Updated: krb5-libs-1.18.5-1.ppc
Sep 14 12:05:27 Updated: libssh2-1.10.0-1.ppc
Sep 14 12:05:36 Updated: ncurses-6.3-1.ppc
Sep 14 12:05:36 Installed: libnghttp2-1.46.0-1.ppc
Sep 14 12:05:37 Updated: curl-7.83.1-1.ppc
Sep 14 12:05:40 Updated: git-core-2.35.1-1.ppc
Sep 14 12:05:46 Updated: git-core-doc-2.35.1-1.noarch
Sep 14 12:05:48 Updated: git-2.35.1-1.ppc
Sep 14 12:05:50 Updated: sqlite-3.37.2-1.ppc
Sep 14 12:05:50 Updated: lz4-1.9.3-1.ppc
Sep 14 12:05:50 Updated: gdbm-1.23-1.ppc
```

> ```
>17:33:50 + git clone --depth 1 https://github.com/nodejs/build.git
> 17:33:50 Cloning into 'build'...
> 17:33:50 Could not load program /opt/freeware/libexec64/git-core/git-remote-https:
> 17:33:50 Symbol resolution failed for /opt/freeware/lib64/libkrb5support.so because:
> 17:33:50 	Symbol _GLOBAL__AIXI_libintl_so (number 58) is not exported from dependent
> 17:33:50 	  module /usr/lib/libintl.a[libintl.so.8].
> 17:33:50 	Symbol _GLOBAL__AIXD_libintl_so (number 59) is not exported from dependent
> 17:33:50 	  module /usr/lib/libintl.a[libintl.so.8].
> 17:33:50 Examine .loader section symbols with the 'dump -Tv' command.
> 17:33:50 Build step 'Execute shell' marked build as failure
> ```

It looks like `/opt/freeware/lib64/libkrb5support.so` probably wants the `libintl.so` in `/opt/freeware/lib64` but it isn't getting it because the jobs are running with a `LIBPATH` of `/opt/jdk-17.0.4.1+1-jre/lib/server:/opt/jdk-17.0.4.1+1-jre/lib:/opt/jdk-17.0.4.1+1-jre/../lib:/usr/lib` (https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/42765/injectedEnvVars/). I've set `LIBPATH` to `/opt/freeware/lib64:/usr/lib:/lib` in the Jenkins start script for AIX (Java will automatically prepend its own lib path to that). 

Test build appears to be progressing: https://ci.nodejs.org/job/node-test-commit-aix/42767/nodes=aix72-ppc64/console

**Comment by aduh95** [comment]
https://ci.nodejs.org/job/node-test-commit-aix/42766/ turned green, it looks like that fixed it, thanks 🎉
