### ISSUE TITLE
node-test-commit-v8-linux fails to pull V8 deps

### ISSUE THREAD

**Issue by targos** [nodejs/build#3050]
See https://ci.nodejs.org/job/node-test-commit-v8-linux/4903/nodes=benchmark-ubuntu1604-intel-64,v8test=v8test/console

There are often errors like this:

```
16:55:25 [0:05:35] fatal: unable to access 'https://chromium.googlesource.com/external/github.com/google/googletest.git/': Could not resolve host: chromium.googlesource.com
```

**Comment by richardlau** [comment]
FTR https://ci.nodejs.org/job/node-test-commit-v8-linux/4894/ passed but it was the only one in the last fortnight to do so.

**Comment by richardlau** [comment]
Upgrade won't happen today due to other infra issues.

FTR, neither of the two builds today had the deps fetching problem:
- https://ci.nodejs.org/job/node-test-commit-v8-linux/4905/ passed.
- https://ci.nodejs.org/job/node-test-commit-v8-linux/4906/ built but failed the perf test.

Although all of the builds yesterday did fail with the deps fetching problem.

**Comment by richardlau** [comment]
Upgraded the benchmark machine used for V8 builds to Ubuntu 18.04. I'm hesitant to go higher due to available versions of python and unversioned python (since I think the older V8 versions in Node.js 14 may still require `python` to be python 2).

Test builds:
- v14.x: https://ci.nodejs.org/job/node-test-commit-v8-linux/4913/
- v16.x:
- v18.x:
- main:

**Comment by richardlau** [comment]
Upgrade doesn't appear to have fixed the issue 😞 
https://ci.nodejs.org/job/node-test-commit-v8-linux/4913/nodes=benchmark-ubuntu1804-intel-64,v8test=v8test/console
```
7:31:02 [0:03:48] error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
17:31:02 [0:03:48] fatal: The remote end hung up unexpectedly
17:31:02 [0:03:48] fatal: early EOF
17:31:02 [0:03:48] fatal: index-pack failed
```

**Comment by sxa** [comment]
Two things to try:
- Are you able to replicate it from the command line outside jenkins? (i.e. is it something environmental when run via jenkins?)
- If "yes" to the first, can you use a `git@github.com:...` URL to do the operation and does that fail?

**Comment by richardlau** [comment]
> Two things to try:
> 
> * Are you able to replicate it from the command line outside jenkins? (i.e. is it something environmental when run via jenkins?)

hmm. I just ran two builds manually on the machine and they succeded 😕. I don't have time to do more runs tonight.

> * If "yes" to the first, can you use a `git@github.com:...` URL to do the operation and does that fail?

No, because these are fetching deps from chromium.googlesource.com.

**Comment by richardlau** [comment]
The Nearform machines are now retired from the CI. This was only seen there and has not occurred on the Hetzner replacements.
