### ISSUE TITLE
Give access to @UlisesGascon to Mac OS test machines

### ISSUE THREAD

**Issue by UlisesGascon** [nodejs/build#3068]
As requested by @richardlau in Slack, I open this issue so we don't lose track :)

**Comment by UlisesGascon** [comment]
Sure @mhdawson! How do I get started?

**Comment by mhdawson** [comment]
I think the first step is to agree to give @UlisesGascon ongoing access to the MacOS machines in our test infra. 

As per:https://github.com/nodejs/build/blob/main/GOVERNANCE.md#special-access-requests

In these cases the following will be used to decide if ongoing access can be provided:

* Does the scope and size of the need justify providing access.
  * Yes we need help maintaining the MacOS machines. It seems to be slowly degrading despite
     the work (many thanks) being done by existing build WG members, for example during the
     last set of security releases there was only 1 machine available meaning each built
     took 2 hours sequentially.
* Is the individual a collaborator. If so then access should be allowed provided the first point is satisfied.
  * No   
* Length and consistency of involvement with Node.js working groups and/or community.
  * @UlisesGascon has been a member of the security-wg since May this year. He is active in the bi-weely meetings
    and has been contributing to the work on the threat model - https://github.com/nodejs/node/pull/45223
* Consequences to the individual in case of misbehaviour. For example, would they potentially lose their job if they were reported as mis-behaving to their employer ? Would being banned from involvement in the Node.js community negatively affect them personally in some other way ?
  * They work at one-beyond.com and list there OpenSource contributions prominently on resumes/linked in etc. Misbehaviour would likely have a negative impact on their chosen career path.
* Are there collaborators who work with the individual and can vouch for them.
  * I don't work with @UlisesGascon directly, but from his involvement/participation in the
    security-wg I'm confortable with giving him access to at least one of the
    MacOS test infra.

**Comment by mhdawson** [comment]
@nodejs/build

**Comment by Trott** [comment]
SGTM

**Comment by richardlau** [comment]
+1

**Comment by richardlau** [comment]
I've invited @UlisesGascon to nodejs-private and added them to the build team there so they can access the secrets repo. Their gpg key has been added to the `build/test` and `build/infra-mac` areas of the secrets repo.

**Comment by UlisesGascon** [comment]
Thanks @richardlau for grant me access
