### ISSUE TITLE
Jenkins monitor and 'false positives'

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#312]
I'm getting slightly annoyed by the azure bots. I guess the "real" issue is that they go offline, but the amount of emails we're getting as a result is starting to ramp up. If these were "real" (I love quoting) issues, that'd be fine but I don't see anyone acting on these since they just come online at a later stage anyway.

Could we perhaps change the routine so we check for instance every 5 minutes and do a simple scoring system where bots needs to be offline for 2 or 3 consecutive checks before sending an alert?

**Comment by rvagg** [comment]
@Starefossen is the source to this somewhere on github? Can you point us in the right direction to be able to make changes? Unless you have time to make such a change of course.

Also @joaocgreis can you update us on the status of the azure machines? Is this just a reality we need to accept and adapt to somehow? Do you have any plans for new things to try?

**Comment by Starefossen** [comment]
Source code is up at https://github.com/Starefossen/jenkins-monitor. Would need to refactor how the nodes are stored in redis to account for scoring.

**Comment by joaocgreis** [comment]
@rvagg me and @jbergstroem already made a few attempts at fixing the Azure slaves by adjusting keep alive ping timeouts. I looked at it more carefully today, and still haven't given up. 

The tricky thing with timeouts is that jenkins has to be restarted for changes to take effect, but after the restart everything works well. The problem happens in the time window after the Azure load balancer cuts the connection because of inactivity and before jenkins notices it and restarts the slave. Not sure if both the master and the slave must detect that the connection was cut though.

If this proves to be a dead end, I have no other clues yet.

**Comment by Starefossen** [comment]
I have deployed a new version of Jenkins Monitor with a simple scoring algorithm. Current configuration is based on @jbergstroem suggestion – 5 minutes interval and 3 consecutive offline before notifying. This means there will be a 15 minutes delay before a notification is sent out and hopefully this will reduce the number of "false" positives.

**Comment by jbergstroem** [comment]
Much better as a result of above comment. I consider this fixed -- closing.
