### ISSUE TITLE
Request access to `rhel8-ppc64le`

### ISSUE THREAD

**Issue by RaisinTen** [nodejs/build#3168]
While working on https://github.com/nodejs/node/pull/45038, which adds single-executable support to Node.js, I noticed a segfault occurring consistently on CI - https://github.com/nodejs/node/pull/45038#issuecomment-1410641379.

I'd like to get access to the system, so that I can further debug this and hopefully fix it.

cc @richardlau

**Comment by richardlau** [comment]
I've taken [test-osuosl-rhel8-ppc64_le-1](https://ci.nodejs.org/computer/test-osuosl-rhel8-ppc64_le-1/) offline in Jenkins and added @RaisinTen 's keys to it. @RaisinTen you should be able to ssh into the machine with:

```shell
ssh cloud-user@140.211.168.183
```

builds are normally done by the `iojs` user:
```shell
sudo -s su - iojs
```

Please let us know when you're done with the machine so that we can return it to the CI pool.

**Comment by RaisinTen** [comment]
@richardlau I've found out the root cause and opened an issue about it - https://github.com/nodejs/postject/issues/70 with a solution I'll go ahead with for now. Thanks a lot!

**Comment by richardlau** [comment]
I've removed @RaisinTen 's keys from [test-osuosl-rhel8-ppc64_le-1](https://ci.nodejs.org/computer/test-osuosl-rhel8-ppc64_le-1/) and marked it online again in Jenkins.
