### ISSUE TITLE
CI reliability is broken

### ISSUE THREAD

**Issue by anonrig** [nodejs/build#3175]
There isn't any issues on the repo for the past 10 days.

https://github.com/nodejs/reliability/issues

**Comment by nschonni** [comment]
From the last message https://github.com/nodejs/reliability/actions/runs/4088929364/jobs/7051095994#step:8:25 the report body is now too big to post as a GitHub issue. Not sure there is anything for this repo to debug

**Comment by targos** [comment]
Yeah, there's nothing the build WG can do about it.
BTW today's run was able to create the issue: https://github.com/nodejs/reliability/issues/495

**Comment by richardlau** [comment]
FWIW https://github.com/nodejs/reliability is running [`ncu-ci walk pr`](https://github.com/nodejs/reliability/blob/506849d9032f01b28f9b9951fc9f397c3d401c3f/.github/workflows/reliability_report.yml#L25) from [node-core-utils](https://github.com/nodejs/node-core-utils). If anyone comes up with a reasonable way of capping [the generated report](https://github.com/nodejs/reliability/blob/506849d9032f01b28f9b9951fc9f397c3d401c3f/.github/workflows/reliability_report.yml#L28-L30) so that the `body` field is [less than 65536 characters](https://github.com/nodejs/reliability/actions/runs/4069941326/jobs/7010224445#step:8:26), please open a PR in either the node-core-utils or reliabiity repositories.
Refs: https://github.com/nodejs/node-core-utils/blob/main/docs/ncu-ci.md#ncu-ci-walk-type
