### ISSUE TITLE
Benchmark CI is down

### ISSUE THREAD

**Issue by anonrig** [nodejs/build#3245]
It seems the benchmark machines are down or the job is wrong. I'm seeing the following log on the build history of https://ci.nodejs.org/view/Node.js%20benchmark/job/benchmark-node-micro-benchmarks/

```
(pending—All nodes of label ‘[benchmark-ubuntu1804-intel-64](https://ci.nodejs.org/label/benchmark-ubuntu1804-intel-64)’ are offline)
```

**Comment by targos** [comment]
The benchmark machines are unreachable.

/cc @efrisby

**Comment by targos** [comment]
We should setup these machines so that they restart automatically after a power outage, like the macs. It may require physical access to tweak the BIOS settings.

**Comment by efrisby** [comment]
Hi, 

I will get those machines started tomorrow morning when I'm on site in HQ. I was on annual leave and just back a few days. 

Thanks,
Eamonn

**Comment by efrisby** [comment]
Hi, those servers are now back online, we are putting a better alert notification in place, to make sure we don't miss this again. We will also investigate the power settings to see if they are in place, as we would have odd power failures from time to time and they would restart, it seems hit and miss, not sure if it is related to the age of the machines themselves and any hardware issues. 

Can someone confirm who is the provider of those machines, can we look to replace perhaps with more modern hardware?

**Comment by richardlau** [comment]
> Can someone confirm who is the provider of those machines, can we look to replace perhaps with more modern hardware?

According to https://github.com/nodejs/build/issues/791 [those machines are Intel's](https://github.com/nodejs/build/issues/791#issuecomment-314792020). I wasn't in Build nor the TSC at the time. Maybe @mcollina or @mhdawson have more information.

**Comment by mcollina** [comment]
Intel shipped those two machines to NearForm back in the day. Since then, those machines have been operated by NearForm, and there was no direct involvement by Intel. @efrisby manages them for NearForm (unless things changed).

> Can someone confirm who is the provider of those machines, can we look to replace perhaps with more modern hardware?

This would require a donor to set things up. Given the availability of cheapish dedicated HW online (Hetzner sells for 50-100€/month, other providers have similar prices), foundation resources could be asked for.

Ultimately, I don't think having more modern HW matters in this case, as long as those machines are up. We do not want to measure maximum absolute speed, but rather do a comparison on the same HW.

**Comment by richardlau** [comment]
Let's move/keep discussions about whether replacements are needed to https://github.com/nodejs/build/issues/3615.
