### ISSUE TITLE
test-equinix-ubuntu2004_docker-arm64-3 (and all hosted containers on it) is down

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#3359]
Attempts to ssh into the host are timing out:

```console
$ ssh test-equinix-ubuntu2004_docker-arm64-3
ssh: connect to host 145.40.99.31 port 22: Connection timed out
$
```

Logging into the out-of-band console shows that the machine is stuck on a
```console
grub>
```
prompt which is not the usual UEFI prompt that we've seen the Altras stuck on in https://github.com/nodejs/build/issues/2894.

**Comment by richardlau** [comment]
Running `boot` errors:
```console
grub> boot
error: you need to load the kernel first.
grub>
```

**Comment by vielmetti** [comment]
Try the instructions at https://gist.github.com/vielmetti/dafb5128ef7535c218f6d963c5bc624e and report back.

This is a known issue and is actively being worked on right now so that new installs don't run into this. I'll update the gist when I think everything is settled, but not everything is settled yet.

**Comment by sxa** [comment]
Yep - that has resolved it. Thanks for the reminder @vielmetti (For reference: `configfile ($root)/EFI/GRUB/grub.cfg`)
