### ISSUE TITLE
Request for access to AIX

### ISSUE THREAD

**Issue by anonrig** [nodejs/build#3399]
I'm having some issues with my pull request - https://github.com/nodejs/node/pull/48477. I'd like to request a temporary access to the AIX CI machine to resolve the issue.

cc @nodejs/build

**Comment by richardlau** [comment]
@anonrig I've added your [key](https://github.com/anonrig.keys) to [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/computer/test-ibm-aix72-ppc64_be-2/).

Log in with
```console
ssh root@169.54.113.165
```

**IMPORTANT** Switch to the `iojs` user:
```console
sudo -u iojs bash
```

(this assumes you want `bash` rather than the default `ksh`)

The build from https://ci.nodejs.org/job/node-test-commit-aix/46938/ is in `/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64`
```console
cd /home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64
```

If you need to manually rebuild code, make sure to set some environment variables to use gcc 10 and ccache:
```console
export CC=gcc-10
export CXX=g++-10
export LINK=g++-10
export PATH=/opt/ccache-3.7.4/libexec:/opt/freeware/bin:/opt/freeware/bin:/usr/opt/python3/bin/:/usr/bin:/etc:/usr/sbin:/usr/ucb:/home/iojs/bin:/usr/bin/X11:/sbin:.

**Comment by anonrig** [comment]
Thank you for your help @richardlau. I've resolved my issue, and you can remove my access to the AIX machine. I'm not closing this issue. Appreciate it if you can close it, after you remove my access. Thanks.
