### ISSUE TITLE
Self-nomination, @ovflowd to the Build WG

### ISSUE THREAD

**Issue by ovflowd** [nodejs/build#3426]
I hope this doesn't sound like an arrogant request. But I would like to self-nominate myself to the Build WG.

Even though I can't contribute to many of the other topics of the Build WG, I can impact our Web infrastructure here.

I've been around for a while and making a few contributions here and there, And I'd like to join the team to make more meaningful contributions and be closer to the agenda and discussions that the WG takes. I've also contributed to deep technical issues within the Build repository with configuration files, discussions and issues. I've also been involved in the #nodejs-build Slack channel and been super active in their technical discussions.

I'm genuinely excited to be able to contribute deeper to the current issues we have on our infrastructure. Note that I'd like to clarify that I'm probably going to be a temporary member at best;

Thank you!

**Comment by MoLow** [comment]
big +1 on this nomination. I don't think it is an arrogant request at all.

**Comment by mhdawson** [comment]
I think joining the build wg makes sense, but that usually starts with test level access. I'm thinking that won't give you the access you were hoping for.  

So +1 to you joining the build wg, but just a heads up that you might still not have the level of access to the website you might want.

This comment does make me wonder a bit:
> Note that I'd like to clarify that I'm probably going to be a temporary member at best;

The existing build WG members, particularly those with infra level access are cautious because change can cause problems, and in some cases in ways we only discover much later. In that context we'd hope that those we give higher level access will be around long term to deal with any longer term issues.

**Comment by ovflowd** [comment]
> So +1 to you joining the build wg, but just a heads up that you might still not have the level of access to the website you might want.

That's fine by me. I do understand this comes over time!

> The existing build WG members, particularly those with infra level access are cautious because change can cause problems, and in some cases in ways we only discover much later. In that context we'd hope that those we give higher level access will be around long term to deal with any longer term issues.

Also fine by me. I'll be around, just being explicit that I will probably not engage in that many Build WG related projects, but I will definitely be around for giving support.

**Comment by UlisesGascon** [comment]
> That's fine by me. I do understand this comes over time!

+1 in the nomination.

> Also fine by me. I'll be around, just being explicit that I will probably not engage in that many Build WG related projects, but I will definitely be around for giving support.

We had a great pairing session to finish the last changes in Cloudflare for the Vercel migration 👍

**Comment by ovflowd** [comment]
cc @nodejs/build do we have consensus here?

**Comment by ovflowd** [comment]
Guess this is not gonna happen.

**Comment by mhdawson** [comment]
@ovflowd sorry, in the last meeting (minutes in https://github.com/nodejs/build/pull/3578/files)  I agreed that I'd reach out to you. We are ok with adding you at the test level, I was just going to confirm that it makes sense given your goals.

**Comment by mhdawson** [comment]
I talked to @ovflowd today and since he already has lots on his plate in terms of docs and web, there would be limited cycles to contribute on the build side. So the answer is that is does not make sense right now but may in the future. So this makes sense as closed @ovflowd can create a new issue if/when it does make sense in the future.
