### ISSUE TITLE
Investigate common problem with Windows Runs

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#3536]
This seems to be one of the top problems with 14 occurences in a [recently reliability report](https://github.com/nodejs/reliability/issues/692) - 

	error: remote GitHub already exists.

Looking at one of the jobs I'm not even sure if that is the real problem as the job progresses after that comment. I'm wondering if its more that something was not cleaned up from a past job etc.

@StefanStojanovic @nodejs/platform-windows could you please investigate as this seems to be one of the larger contributors to failures in the CI and is specific to how the windows jobs work.

**Comment by mhdawson** [comment]
@richardlau great to hear, I guess we'll see in the reliability reports if it goes away.

**Comment by StefanStojanovic** [comment]
I checked all `error: remote GitHub already exists.` errors found during report generation in [create-report action](https://github.com/nodejs/reliability/actions/runs/6581639074/job/17881904553). I second what @richardlau said - all of those were compile debug runs and were failing because of changes in the build repo. I'm expecting it not to show up anymore

BTW, I'll be out of office next week, so I'm unavailable until Monday, October 30.

**Comment by mhdawson** [comment]
Don't see it in recent reports, closing.
