### ISSUE TITLE
request: access to the AIX CI Machine

### ISSUE THREAD

**Issue by abmusse** [nodejs/build#3571]
I would like to gain access to the AIX CI Machine to debug a test failure in libuv 

Ref: https://github.com/libuv/libuv/pull/4222#issuecomment-1812962233

**Comment by richardlau** [comment]
+1

**Comment by richardlau** [comment]
Since @abmusse isn't a collaborator this request falls under https://github.com/nodejs/build/blob/main/GOVERNANCE.md#temporary-access

> - Does the scope and size of the need justify providing access.

Yes.

> - Is the individual a collaborator. If so then access should be allowed provided the first point is satisfied.

No. 

> - Length and consistency of involvement with Node.js working groups and/or community.

He's been working on Node.js since February (https://github.com/nodejs/node/pull/46546). 
[Pull requests in nodejs/node](https://github.com/nodejs/node/pulls?q=is%3Apr+author%3Aabmusse).
[Pull requests in libuv/libuv](https://github.com/libuv/libuv/pulls?q=is%3Apr+author%3Aabmusse).

> - Consequences to the individual in case of misbehaviour. For example, would they potentially lose their job if they were reported as mis-behaving to their employer ? Would being banned from involvement in the Node.js community negatively affect them personally in some other way ?

Yes, he works for IBM.

> - Are there collaborators who work with the individual and can vouch for them.

I'll vouch for him. He's working with @mhdawson and myself on supporting IBM platforms in Node.js.

**Comment by mhdawson** [comment]
+1 from me

**Comment by richardlau** [comment]
Checked with @abmusse and he would still like access. Since no objections I'll proceed with granting access to one of our AIX machines.

**Comment by richardlau** [comment]
@abmusse is now a member of the working group so automatically has access. We don't need a separate issue to track anymore.

**Comment by targos** [comment]
I removed @abmusse's keys and put the machine back online.
