### ISSUE TITLE
OSX Package not being created by build job (headers are not being built either)

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/build#358]
Last job that built PKG and headers was [#472](https://ci-release.nodejs.org/job/iojs+release/472/nodes=osx1010-release-pkg/)

First job to not build either was [#475](https://ci-release.nodejs.org/job/iojs+release/475/nodes=osx1010-release-pkg/), there were a number of failures in between.

I just finished building [#477](https://ci-release.nodejs.org/job/iojs+release/477/) which unfortunately has no .pkg or headers :cry:

**Comment by rvagg** [comment]
Check the -tar slave and see what it's doing, e.g. https://ci-release.nodejs.org/job/iojs+release/475/nodes=osx1010-release-tar/consoleFull for 475, I think they might be switched and perhaps it was my fault. Will look into it shortly.

**Comment by rvagg** [comment]
Ah, it's because the job it does depends on the OSTYPE env var on the machine so it's always running the tar job on the tar machine and pkg job on the pkg machine even though they both have both labels so it can look like it's switched around but it's consistently the same machine. I need to change it so that the job it does depends on the label the salve is used as instead.

But in summary, it still should be building properly, you just won't necessarily find the build job listed under the right osx slave.

**Comment by jbergstroem** [comment]
I confirmed all artefacts being there as well; the logic is just a bit off.
