### ISSUE TITLE
win-vs2022-arm64 builds often fail due to `compiler is out of heap space`

### ISSUE THREAD

**Issue by MoLow** [nodejs/build#3707]
```
15:20:10 C:\workspace\node-compile-windows\node\deps\v8\src\codegen\code-stub-assembler.h(3330,1): fatal  error C1060: compiler is out of heap space [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_initializers.vcxproj]
15:20:10   frames-tq-csa.cc
15:20:10 C:\workspace\node-compile-windows\node\deps\v8\src\codegen\code-stub-assembler.h(3391,5): fatal  error C1060: compiler is out of heap space [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_initializers.vcxproj]
15:20:10   data-view-tq-csa.cc
15:20:10 C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\xtr1common(84,1): fatal  error C1060: compiler is out of heap space [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_initializers.vcxproj]
```

https://ci.nodejs.org/job/node-compile-windows/55848/nodes=win-vs2022-arm64
https://ci.nodejs.org/job/node-compile-windows/55857/nodes=win-vs2022-arm64
https://ci.nodejs.org/job/node-compile-windows/55870/nodes=win-vs2022-arm64

**Comment by StefanStojanovic** [comment]
I've noticed the increase as well. Will look into it.

**Comment by StefanStojanovic** [comment]
Here's an update: Since the RAM is an issue, there are some things I can try. The simplest one is to increase the size of the pagefile and see how that affects the CI. I've checked the reliability report and the `compiler is out of heap space` errors seem to be evenly spread among all VS2022 machines. This is helpful as I can apply changes to half of them (changes that are machine-related) and follow how it affects the distribution and number of errors. I'll share results and updates when I have them, just wanted to let everyone know this is not forgotten.

**Comment by StefanStojanovic** [comment]
Looking at the latest [reliability reports](https://github.com/nodejs/reliability/issues), machines 1, 2, and 3 are no longer running into the `compiler is out of heap space` issue. Those are the machines that now have been given double the size of the pagefile. I'll apply the same setting on the other 3 and see if that will make the issue disappear.

**Comment by StefanStojanovic** [comment]
I haven't seen the `compiler is out of heap space` recently in the reliability reports. Closing the issue.
