### ISSUE TITLE
'curl' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#3934]
Not sure if this is related to https://github.com/nodejs/build/issues/3929, but looking at the two most recent [node-daily-v20.x-staging](https://ci.nodejs.org/job/node-daily-v20.x-staging) and [node-daily-v18.x-staging](https://ci.nodejs.org/job/node-daily-v18.x-staging/) runs, Windows test jobs on x86 are failing with
e.g.
https://ci.nodejs.org/job/node-test-binary-windows-js-suites/30833/RUN_SUBSET=0,nodes=win2016-COMPILED_BY-vs2019-x86/console
```
13:10:15 C:\workspace\node-test-binary-windows-js-suites>curl -LO https://raw.githubusercontent.com/nodejs/build/main/jenkins/scripts/windows/ci-run.cmd 
13:10:15 'curl' is not recognized as an internal or external command,
13:10:15 operable program or batch file.
13:10:15 
13:10:15 C:\workspace\node-test-binary-windows-js-suites>call ci-run.cmd node-test-binary-windows-js-suites 
13:10:15 'ci-run.cmd' is not recognized as an internal or external command,
13:10:15 operable program or batch file.
13:10:15 
```

cc @StefanStojanovic

**Comment by StefanStojanovic** [comment]
The issue was that Windows Server 2016 machines don't have `curl.exe` inside their `C:\Windows\System32` directory. They get it from `Git\mingw64\bin` which was removed from the path environment variable similarly to the `Git\usr\bin` after the downgrade I did last week. The machines are now updated and I'll close this issue on Friday if everything works fine.
