### ISSUE TITLE
Unique IP data in metrics?

### ISSUE THREAD

**Issue by mikeal** [nodejs/build#401]
I've been working through some of the metrics and while I do see the geographic data it seems to be reporting daily downloads from each region not the unique IP addresses. Could we get a count on that?

**Comment by mikeal** [comment]
If someone could give me access to the raw logs I could write a script to process the unique IP data.

**Comment by Fishrock123** [comment]
See https://nodejs.org/metrics/#countries?

Anything beyond that gets a bit more tricky. It becomes a bit too easy to potentially pinpoint specific users.

**Comment by Fishrock123** [comment]
i.e. per region in a country was not considered acceptable due to the above at the time.

**Comment by mikeal** [comment]
Right, I don't want the actual IP data, I want the number of unique IPs in a given time range. daily, weekly, and monthly is probably ideal.

**Comment by Fishrock123** [comment]
cc @rvagg

**Comment by rvagg** [comment]
@mikeal since this is all stripped fairly early in the processing chain it's going to have to be a special job to generate them separately, and we can't allow the logs to be public either obviously.

If you're interested, the stripping happens here: https://github.com/nodejs/build/blob/master/setup/www/tools/metrics/download-counts.sh#L36-L37

And unfortunately, collating this across ~1 file per day (not exact day boundaries and not guaranteed to be exactly 1 per day) is very awkward so this is not a simple task. It is an interesting one, however, so I've got it on my list now to tinker with some time. You'll have to be patient!

_(sorry for the delay, I remember replying to this issue when it first came up but I don't see a reply here so I obviously screwed that up!)_

**Comment by maclover7** [comment]
Seems like this is something that would require working around how the system is currently setup, going to close for now -- please feel free to reopen if this is something we still want to do.
