### ISSUE TITLE
[request] Please add alpine/musl bot to libuv too

### ISSUE THREAD

**Issue by saghul** [nodejs/build#465]
To be tested with the rest of the Linux bots.

PS: Is there a way for me to help with this instead of opening issues with you folks? (I'm ok if you want it that way too!)

**Comment by jbergstroem** [comment]
@saghul specific version or just $latest? Do they LTS?

**Comment by jbergstroem** [comment]
We'd have to put it inside of a docker instance or run virtualisation inside of a vm seeing how we're pretty short with barebones hardware.

**Comment by jbergstroem** [comment]
Actually, come to think of it, I think Joyent might offer Alpine. I'll have a look.

**Comment by saghul** [comment]
@jbergstroem no specific version. I understand there is already a bot for Node? That one should do.

**Comment by jbergstroem** [comment]
@saghul ok; I'll look at hooking the docker version up today

**Comment by saghul** [comment]
@jbergstroem excellent, thanks!

**Comment by jbergstroem** [comment]
We have a bot now running native alpine34 on joyent:
- node: https://ci.nodejs.org/job/node-test-commit-jbergstroem-alpine34/3/nodes=alpine34-x64/console
- libuv: https://ci.nodejs.org/view/libuv/job/libuv-test-commit-linux/nodes=alpine34-x64/

@rvagg reckon we should do this route instead of the container thing? (ref #437) If so, I'll create a PR with playbook.

**Comment by phillipj** [comment]
Newbie question; what's a bot in this context?

**Comment by jbergstroem** [comment]
@phillipj apologies. A vm/jenkins slave.

**Comment by saghul** [comment]
Closing, @jbergstroem already fixed it! 🎉
