### ISSUE TITLE
Build WG Meeting 2016-10-11

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#512]
### When

October 11th 2016, 8pm UTC: http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Build+WG+Meeting&iso=20161011T20&p1=%3A

### Where

- Hangouts on Air, for participants: https://hangouts.google.com/call/7rw6x2cpobga5bfigxjbiubxcue
- Youtube stream, for viewers: https://www.youtube.com/watch?v=nbYrQ43cpf4
- Minutes document: https://docs.google.com/document/d/1l3mVB1f-JCG-05V68XIrxWNlgZdzlPPd26kIqLoBk_U/edit?usp=sharing

### Agenda

Extracted from `wg-agenda` [issues](https://github.com/nodejs/build/issues?q=is%3Aopen+is%3Aissue+label%3Awg-agenda) and [pull requests](https://github.com/nodejs/build/pulls?q=is%3Aopen+label%3Awg-agenda+is%3Apr) from this repo.

- Draft text for HSTS communication #484
- TAP Plugin issues on Jenkins #453
- rsync endpoint to mirror the releases #55
- Looking for issue good for first contribution #495 
- Access to AIX machines to provide coverage #470

If there are any items that you would like to discuss at the meeting, please tag new or existing issues with the `wg-agenda` label, or simply post them in a comment here.

All welcome of course, primarily @nodejs/build focused but we're happy to expand.

**Comment by rvagg** [comment]
Sorry for not dropping this earlier but I have a conflict today that's stopping me attending. Some updates from me tho:

* Still working on OSX resources, delays are from the company that is _nearly_ ready to commit, I also have a backup macmini nearly ready for my garage (just cause I have a spare one not in action atm!)
* New nodejs.org server nearly ready, really needs to be done this week but I've had delays on my end due to new commitments this week
* Back up to 14 Pi1's so we have 12 in the test cluster, a complete set finally
* Supported platforms list was accepted, I just need to tweak the PR for it to land, we need to adjust it for landing on v4 as well

**Comment by mhdawson** [comment]
PR for minutes: https://github.com/nodejs/build/pull/517

**Comment by mhdawson** [comment]
Minutes landed closing
