### ISSUE TITLE
Improve value proposition for infrastructure donors

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#539]
We're still struggling with the "what do I get in return?" question from potential infrastructure providers who don't have an existing stake in Node.js (like IBM, Microsoft, etc.). What we really need is a prospectus that outlines what we can offer, and perhaps what we can't offer. It's important that we retain our independence from donor companies and figure out what the reasonable boundaries are whereby we get mutual value without compromising our values or the integrity of the project.

This is relevant right now because we are talking to a new potential infra provider who doesn't have an existing interest in Node.js and don't have a good summary of the value they get from contributing and what we do have isn't overly compelling.

Here's my high-level proposal for what we can / should do for our providers:

 - [ ] Clarify the provider tiers on our [README](https://github.com/nodejs/build) by introducing an additional tier to represent the sub-$1k/month donors, so we have something that's roughly: Tier1=>$5k/month, Tier2=>$1k/month<$5k/month, Tier3=<$1k/month. There's a huge range in our Tier2 at the moment and it makes it more difficult to get donors in that mid range if they are lumped in a crowded group. I _think_ we should end up with DigitalOcean, Rackspace and Microsoft (new) in Tier1, then Joyent, IBM/Softlayer in Tier2 and the rest in Tier3. It's important to note that we don't have precise metrics on how much in-kind $ we get from these companies, they are very rough guesses, and we shouldn't publish those tier $ amounts either. @jbergstroem how do those numbers sound about right? How would you adjust?
 - [ ] Make a new page on nodejs.org, I think under https://nodejs.org/en/foundation/ somewhere, that's roughly a mirror of our REAMDE section on infra providers, where we can promote/thank them and highlight the ways they help
 - [ ] Offer to provide content and quotes on behalf of the Build WG for companies that would like some promotion of their donations, perhaps guest posts for their blogs. There's a limitation to how much we can provide here but I'm pretty happy to do some writing for this kind of thing occasionally, I don't really want a flood of requests though!
 - [ ] Publish regular "State of the Build" posts (possibly with the [WG roll-up](https://github.com/nodejs/TSC/issues/109) where we highlight batches of donors and the ways they add value to the project. It would be good to have posts that we can point to and say "your name could be here in these future posts!".
 - [ ] Highlight how [node names are used in Jenkins](http://ci.nodejs.org/computer/), which are regularly seen during active development of Node by collaborators and contributors alike.

@nodejs/build thoughts?

**Comment by piccoloaiutante** [comment]
On 3rd point how about public tweet from foundation thanking for donors support every X amount of time? Is it something feasible or meaningful?

Overall the rest of you proposition make sense to me.

**Comment by jbergstroem** [comment]
- Create three tiers: Lets. I agree with your assessment on group criteria as well as picks.

- New page: Should it live under the foundation though? Being a build group provider doesn't necessarily mean being part of the Node.js foundation.

- Guest blogging/content: I'd be happy to write some stuff as well, we have a wide range of topics to cover, from infra to ci to deploy and orchestration. Not sure how we'd define frequency or "obligations" .

- Regular posts: I think this is a great idea and would like to adopt it for all working groups [that have anything to add]. [The FreeBSD Quarterly reports](https://www.freebsd.org/news/status/status.html) is a good example of how they increase visibility in work done. Since we do a lof of deployments/changes to infra, the quarterly report would also serve to increase visibility of our sponsors.

- Node names: Absolutely. I have an idea about a page where we summarize build status since job history isn't permanent in Jenkins. We can make sponsors more visible there too.

**Comment by mhdawson** [comment]
Internally it would be nice to understand the tiers, even if we don't publish them.  I would like to be in the position to be able to explain why we fall into one tier versus another.

**Comment by Trott** [comment]
@rvagg Is this something that should still happen? Or should this be closed (because we've chosen a different path or whatever)?

**Comment by mhdawson** [comment]
@Trott we have some of the pieces in place (regular tweets - one should be coming out this week), but we still have work to do on many of the others.

**Comment by Trott** [comment]
I don't think this is active these day and can probably be closed. By all means, re-open if I'm wrong.
