### ISSUE TITLE
https://nodejs.org/metrics/ is/was borken 

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/build#550]
https://nodejs.org/metrics/

cc @nodejs/build, @rvagg 

If it no longer is it would good to know what happened. :D

**Comment by jbergstroem** [comment]
what does "broken" mean? 404?

**Comment by targos** [comment]
Looking at https://nodejs.org/metrics/summaries/total.csv
It seems that there is an issue collecting the metrics. There is no data between 2016-10-13 and today apart from one point on 2016-11-01.

**Comment by rvagg** [comment]
logrotate wasn't working, fixed in https://github.com/nodejs/build/pull/552, the effect of this is that the unrotated access.log file was getting too big to process effectively—there were a few processes running on the server trying to complete it to no avail.

I've fixed it all up now and split up the big file manually into one per day and it's now processing and should look kind of normal again soon.
