### ISSUE TITLE
Official flatpak (aka xdg-app) runtime?

### ISSUE THREAD

**Issue by ChALkeR** [nodejs/build#580]
_Note: everything written below is speculation, I might be terribly mistaken here, so this needs re-checking._

[Flatpak](http://flatpak.org/) 0.8 stable [is out](https://github.com/flatpak/flatpak/releases/tag/0.8.0), and it looks like flatpak is gaining adoption.

In short: Flatpak (aka xdg-app) aims to bring sandboxed bundled apps to Linux desktop ecosystem. Those bundles are created by the app authors and independent from distributions. They have a concept of «runtime» — shared platform that powers some (potentially large) set of applications.
It's currently available in Debian Testing, Fedora, Arch, and openSUSE.

https://www.npmjs.com/package/flatpak-bundler seems to pack nodejs apps assuming that a system-wide installation of Node.js is available, but I need to look closer at that.

As it looks to me, the correct place for Node.js in the flatpak model is the shared runtime for applications.

Assuming Node.js-based flatpak apps will gain popularity, there are several ways how things might turn out:

1. We run an «official» (perhaps an experimental / in-progress / preview, but official) flatpak repo with Node.js packaged as a runtime.
2. Someone else runs a flatpak repo with Node.js packaged as runtime. Or several people/groups do that, and apps start depending on those. We wouldn't have any control over the updates availability and/or other things there.
3. People start packaging specific Node.js patch versions _inside_ the packages. Bad for security, large archives. I find this unlikely for smaller apps, but possible for larger apps.
4. People would assume that Node.js is already installed in the system. I find this unlikely, this doesn't fit into the whole idea.
5. I'm overreacting and nothing significant will happen in the near future with flatpak + Node.js combination.

_The same for Electron — they probably could want a runtime for the exact same reasons._

---
Refs:
 * http://flatpak.org/
 * https://github.com/flatpak/flatpak
 * https://github.com/flatpak/flatpak/wiki
 * https://wiki.gnome.org/Projects/SandboxedApps
 * https://community.kde.org/Flatpak
 * https://blogs.gnome.org/alexl/2016/12/22/a-stable-base-for-flatpak-0-8/
 * https://en.wikipedia.org/wiki/Flatpak
 * https://www.linux.com/news/flatpak-containerized-approach-developing-linux-applications
 * http://0pointer.net/blog/revisiting-how-we-put-together-linux-systems.html (old concept post)
 * https://vizzzion.org/blog/2017/02/plasma-meeting-web-browsers-and-app-bundles/
 * https://kamikazow.wordpress.com/2017/02/09/adoption-of-flatpak-vs-snap/
 * https://blogs.gnome.org/hughsie/2016/07/05/flatpak-and-gnome-software/
 * http://www.jgrulich.cz/2017/02/14/kde-discover-flatpak-backend/
 * http://www.jgrulich.cz/2017/05/29/gnome-integration-for-qt-based-applications-in-flatpak/
 * http://phoronix.com/scan.php?page=news_item&px=Fedora-27-NSS-Install-i686
 * https://fedoraproject.org/wiki/Workstation/Flatpaks
 * http://phoronix.com/scan.php?page=news_item&px=SteamOS-2121-Flatpak
 * http://blog.manuq.com.ar/posts/building-electron-apps-offline-for-flathub/

**Comment by ChALkeR** [comment]
Note: I opened this issue primarily for the very top-level preliminary discussion now, to decide what to do with it (and whether we should do anything).

If this will seem interesting, I could look up what exact steps would we need to take to setup a repo. I don't expect that to be hard, though, as I suppose that we could use existing binaries for that, just with additional metadata and repackaged.

**Comment by mscdex** [comment]
This is the first time I've ever heard of 'flatpak'.

**Comment by ChALkeR** [comment]
@mscdex I might indeed be overreacting, in this case we should just freeze this (aka do nothing) until some point in the future and see what comes out of it.

**Comment by ChALkeR** [comment]
@mscdex I added some refs.

**Comment by gibfahn** [comment]
I remember a big buzz about FlatPak (Redhat/Fedora backed) and [Snappy](http://snapcraft.io/) (Ubuntu backed) about six months ago, but I haven't heard much since.

If we're going to look at supporting one of these is there a reason to choose FlatPak over Snaps (or an existing package format like AppImage)? I have no strong opinion about which is better, but I don't think we want to be doing all of them. I was hoping one of these would win out in terms of adoption, and everyone could just standardise on that.

**Comment by probonopd** [comment]
[AppImage](http://appimage.org) has the advantage that if you put together its ingredients carefully (e.g., compile on a reasonably old build system), then the resulting AppImage will run on most desktop distributions out-of-the box, without the need for runtimes or anything else apart from what comes with the distributions by default. There is a [growing number](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects using AppImage as their native upstream-provided download format for Linux.

**Comment by ChALkeR** [comment]
@gibfahn @probonopd This issue is not about packaging Node.js as an Flatpak/Snappy/AppImage/whatever application — that is not very important imo.

This is about providing Node.js as a flatpak _runtime_, so that other flatpak packages might depend on Node.js without bundling it — so security updates will reach users faster, the archives would be smaller, etc.

Afaik, Snappy doesn't have the concept of runtimes, so that is out of scope.
I just took a look at AppImage — and it looks like it also doesn't have the concept of runtimes.

_Please, don't discuss packaging Node.js as an Flatpak/Snappy/AppImage/whatever application in this issue — open a separate one for that, if needed._

**Comment by gibfahn** [comment]
Oh I see, my bad for misreading the issue. So this is something more along the lines of a shared library (I guess technically it's probably a package of shared libraries and binaries) that multiple applications can require?

Looking at the other options, it sounds like Snappy is going for file level deduplication rather than having a "runtime" equivalent so we wouldn't have to support multiple competing formats (yet).

So can flatpak runtimes depend on other runtimes, or do you just have a single level hierarchy? It looks like you only get OS->Runtime->App (not OS->Runtime->Runtime->App), so if Electron wanted their own runtime they wouldn't be able to build off a Node.js one.

It sounds like something we should investigate, there's no rush to support or commit to actually maintaining something if flatpak doesn't take off. 

---

Looking at the provided [Flatpak runtimes](http://flatpak.org/runtimes.html), and the [examples in the wiki](https://github.com/flatpak/flatpak/wiki/Examples) (which includes Slack and Electron apps) it looks like the runtimes that exist so far are really low-level things (like Qt or Gnome), and you can only have one. It'd be good to find out whether a Node.js runtime is the right thing for us to be doing.

**Comment by tieguy** [comment]
It is an [officially disfavored analogy](http://flatpak.org/faq.html#Is_Flatpak_a_container_technology_), but it might be helpful to think of providing a flatpak runtime as similar to providing a Docker/OCI image - a layer that app developers can build on. (I don't know if you can stack layers like you can with Docker, though.)

(I stumbled across this issue because I was poking around at what it would take to package [Wordpress Calypso](https://github.com/Automattic/wp-calypso) in Flatpak, and a nodejs runtime would be helpful for that.)

(Disclaimer: I'm not an expert by any stretch, just a Linux desktop user who is frustrated that I'm unzipping tarballs to get Calypso in 2017, and figured that might be an interesting way to dip my toe in the flatpak waters.)

**Comment by ChALkeR** [comment]
Basic information on flatpak runtimes: http://flatpak.org/runtimes.html

More info on creating a runtime:
> [18:10] ebassi > So, the GNOME runtime is this one: https://git.gnome.org//browse/gnome-sdk-images/
> [18:10] ebassi > It's just a flatpak-builder manifest
> [18:11] ebassi > https://git.gnome.org/browse/gnome-sdk-images/tree/org.gnome.Sdk.json.in built using: https://git.gnome.org/browse/gnome-sdk-images/tree/Makefile
> [18:11] ebassi > Then you follow the same steps for hosting it that you'd follow for applications: https://blogs.gnome.org/alexl/2017/02/10/maintaining-a-flatpak-repository/

I will try to take a closer look at that, but I'm not sure when would that happen =).

**Comment by egee-irl** [comment]
Its worth pointing out that Snapcraft (the building engine behind Snaps) already has a [plugin](https://snapcraft.io/docs/reference/plugins/nodejs) for NodeJS. There's even one for [Gulp](https://snapcraft.io/docs/reference/plugins/gulp).

There's even a [tutorial](https://tutorials.ubuntu.com/tutorial/build-a-nodejs-service?utm_source=snapcraft.io&utm_medium=buildsnapsindex&utm_campaign=tutorials#0) on the Snapcraft website for setting up a NodeJS service as a Snap.

Not sure if it's worth building a NodeJS runtime for Flatpak.

**Comment by ChALkeR** [comment]
@egee-irl That is completely unrelated to the issue here. As already said above, snap (afaik) does not have the concept of runtimes, and the minor things like plugins that simplify builds are unimprotant as they (and should) be managed outside of Node.js (i.e., in/by snapcraft itself).

On the contrary, flatpak runtime is (ideally) supposed to be managed by the software/platform authors themselves, i.e. by Node.js. This is why I opened this issue.

Once again, this is not a thread for flatpak-vs-snap-vs-appimage-vs-whatever, this issue is solely about providing a flatpak runtime.

**Comment by ChALkeR** [comment]
Also relevant and deserves a separate mention: http://blog.manuq.com.ar/posts/building-electron-apps-offline-for-flathub/

**Comment by maclover7** [comment]
ping -- does this need to remain open?

**Comment by ChALkeR** [comment]
@maclover7 I believe so, yes. Just didn't have time to look at this closer and actually do things.

**Comment by Yhozen** [comment]
Maybe the GNOME runtime  is just enough

**Comment by sam-github** [comment]
@aberba (or anyone), perhaps this could be added first to https://github.com/nodejs/unofficial-builds.  That may have a lower barrier to entry, and once the maintenance burden is understood, and the use counts known, and there are champions willing to support it, it could transition to an officially supported platform.

**Comment by aberba** [comment]
Node.Js flatpak is very much needed. Linux packaging is moving to snaps and flatpaks

**Comment by rexhent** [comment]
> Node.Js flatpak is very much needed. Linux packaging is moving to snaps and flatpaks

This is especially so now, with the rise of immutable distributions like Fedora Silverblue and Kinoite.

**Comment by faetalize** [comment]
There's no followup on this? I vote that this issue be reopened. 
I'd like to live in a world where I can just go on the Gnome Store, install both VSCode and node.js from flathub, and start coding right away. So I'd be interested in working on it. Where do I look first?

**Comment by woj-tek** [comment]
Why it was closed? Flatpak support would be great and would ease deploying on various systems without headache with dependnecies...
