### ISSUE TITLE
Build missing sunos packages / The case of the wrong sha's

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#586]
These need to be built and promoted

- [x] v4.6.2 @MylesBorins
- [x] v4.7.0 @MylesBorins
- [ ] v4.7.1 @MylesBorins
- [x] v6.9.2 @MylesBorins
- [ ] v6.9.3 @MylesBorins
- [ ] v7.0.0 @jasnell
- [ ] v7.1.0 @evanlucas
- [ ] v7.2.0 @fishrock123
- [ ] v7.2.1 @fishrock123
- [ ] v7.3.0 @cjihrig
- [ ] v7.4.0 @evanlucas

**Comment by MylesBorins** [comment]
discussed with @rvagg, he is going to attempt to recover the promoted releases from backup.

**Comment by rvagg** [comment]
OK, I could only find valid backups for v4.6.2 v4.7.0 and v6.9.2 in /backup/static/dist/nodejs/release on the backup server. @jbergstroem is this because the backup script hasn't run since the newest two were out, today/yesterday? Is there an incremental for dist or only this? Is it just because I caught it before the backup ran again that I happened to catch the old versions of these files (mtimes on them put them earlier than today and SHASUMS indicates they are the original—compared to blog—I haven't shasumed them myself). Is there anywhere else that we might find original copies of v4.7.1 and v6.9.3 other than in ci-release.nodejs.org jobs as artifacts?

What I've done with v4.6.2 v4.7.0 and v6.9.2 is the following:
* Copied the entire dist/release directories for these versions into `/home/staging/nodejs/release/` on the staging/web server
* Copied the sunos-x64 binaries from the new builds into the same staging directories
* Removed the SHASUMS files
* Ran `for i in $(ls); do touch ${i}.done; done` to make the `.done` flag files that tell the promote script that they are ready to be promoted.
* Changed ownership back to staging.staging

So, @MylesBorins, they are in staging now for you to re-promote. If you run `tools/release.sh` and promote v4.6.2 v4.7.0 and v6.9.2, all of the files that are in staging will be moved over to dist and you'll get to make and sign a new SHASUMS file which will have the original shasums plus the new sunos-x64 shasums and be signed by you. You should probably then update the blog posts with the new SHASUMS content which has the sunos-x64 files.

For the other builds, we have two ways to _add_ just the sunos-x64 binaries:
1. Run the builds on ci-release and _cancel_ everything but the sunos-x64 builders. Then you should get just the files you want in staging and when you promote those it'll just be additive.
2. Run the builds as normal on ci-release but then on the server manually remove everything _but_ sunos-x64 in staging. I don't believe anyone but me has ever fiddled around in staging before but technically everyone on the release crew can do it as you have ssh access as staging@direct.nodejs.org and the files are located in `/home/staging/nodejs/release/vX.Y.Z/`. It's probably too intimidating though so I'm happy to step in and do this bit for you when the time comes.

And fwiw, the original releasers don't need to trigger the builds on ci-release, they only need to promote so they can sign. Any one of us who has ci-release access can trigger them at any time and they'll just wait in staging for the appropriate person, so no need for complex people-coordination to make this happen.

**Comment by rvagg** [comment]
If we can't recover the original v4.7.1 and v6.9.3 then my vote would be to simply update the blog posts with the new SHASUMS rather than mess around with pulling them out individually from Jenkins. The problem's we're having are simply about discrepancies which we can fix with brute force on the blog rather than attempting to roll back.

**Comment by jbergstroem** [comment]
> @rvagg said:
> is this because the backup script hasn't run since the newest two were out, today/yesterday? Is there an incremental for dist or only this?

Unfortunately (in this case), we don't increment these: https://github.com/nodejs/build/blob/master/backup/backup_scripts/dist.sh

> @rvagg said:
> If we can't recover the original v4.7.1 and v6.9.3 then my vote would be to simply update the blog posts with the new SHASUMS rather than mess around with pulling them out individually from Jenkins. The problem's we're having are simply about discrepancies which we can fix with brute force on the blog rather than attempting to roll back.

This is a big no-no for me. The blog posts are not the only place where these checksums are stored. Every package manager that's been updated have probably stored their own sum. The only way forward are version bumps. Each artifact at release needs to be considered pristine.

I think this also should sink into the workflow we do with releases. I'm not quite sure why these changed between the runs but one way of handling this could be making files read only on the dist server?

**Comment by jbergstroem** [comment]
Case in point:
```irc
[08:25:23]  <damongant>	we've got a little security/release issue over in #node.js if a dev could take a look
[08:25:48]  <damongant>	checksums for 6.9.2 changed
[08:26:03]  <damongant>	and broke some builds
[08:26:16]  <evanlucas>	damongant changed for what binaries?
[08:26:31]  <damongant>	evanlucas, source package, contents are the same tho
[08:26:46]  <damongant>	timestamp on the tar.xz is different
[08:27:22]  <damongant>	https://aur.archlinux.org/packages/nodejs-lts-boron/ see the first comment, the sha256 I packaged against is still in the 6.9.2 announcement though
```

Doing another minor is probably the simplest way for most parties?

**Comment by gibfahn** [comment]
>Doing another minor is probably the simplest way for most parties?

@jbergstroem do you mean a  `v4.7.2` and `v6.9.4` (patch)?

**Comment by jbergstroem** [comment]
@gibfahn yeah.

**Comment by gibfahn** [comment]
Makes sense to me (but I don't have to do the release 😉 ). If we're going to do it the sooner the better though right?

**Comment by MylesBorins** [comment]
So I just attempted to promote the release and found that the permissions are set incorrectly and I cannot promote the builds. They are currently set to 755 rather than 775, and as such the build cannot be promoted

**Comment by MylesBorins** [comment]
Fixed the ones we had backups of. v4.7.1 and v6.9.3 still have the wrong shas

**Comment by MylesBorins** [comment]
I've proposed new releases v4.7.2 and v6.9.4 that are simply semver patch bumps to remove ambiguits with the release

https://github.com/nodejs/node/pull/10639
https://github.com/nodejs/node/pull/10640

Please chime in those issues on thoughts about the special releases

**Comment by rvagg** [comment]
> This is a big no-no for me. The blog posts are not the only place where these checksums are stored. Every package manager that's been updated have probably stored their own sum. The only way forward are version bumps. Each artifact at release needs to be considered pristine.

point taken, good call on doing brand new releases to clear things up @MylesBorins

**Comment by gibfahn** [comment]
+1 to updating the v4.7.1 and v6.9.3 blog posts to point people to the later version

**Comment by MylesBorins** [comment]
Closing, reopen if we should revisit
