### ISSUE TITLE
Add CI to run nodereport tests

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#594]
We need nodereport CI runs to validate changes going into:  https://github.com/nodejs/nodereport

This issue is to track progress of adding the job.

**Comment by mhdawson** [comment]
Ok initial job in place, passed on platforms configured in the job that I cloned from citgm

Next step is to add additional platforms not in the citgm job including smartos and windows.

Not sure about arm.  @rvagg @jbergstroem do you see any issues with this running regularly on the arm machines ? I know they are more resource contained.

**Comment by mhdawson** [comment]
Ok finally got windows working with a small tweak.

Smartos is broken but its because the nightlies are not currently building.

**Comment by joaocgreis** [comment]
I saw the failure on `win2012r2`, looks like npm is not properly sandboxed. A good way is to set the variable `NPM_CONFIG_USERCONFIG` before calling any npm commands, as the citgm-smoker job does (for Windows, there was no trouble on Unix yet but probably only because of luck). `NPM_CONFIG_CACHE` should also point to a clean or stable location. Furthermore, the `win2012r2` label has machines with VCBT where `npm config set msvs_version 2015` is needed, I think it should be ok to do for all. Let me know if you have further trouble with Windows!

**Comment by richardlau** [comment]
@gibfahn / @mhdawson Would it be possible to stop the jobs trying to run on AIX and s390x when running against Node v4 since there are no Node.js binaries for those platforms? 

e.g. https://ci.nodejs.org/view/post-mortem/job/nodereport-continuous-integration/93/MACHINE=aix61-ppc64/console

**Comment by gibfahn** [comment]
@richardlau Yes, I'll put a check in.

**Comment by mhdawson** [comment]
Believe this is done
