### ISSUE TITLE
Include shared library file in `binary/binary.tar.[xz,gz] in Win and arm tests

### ISSUE THREAD

**Issue by shigeki** [nodejs/build#596]
https://github.com/nodejs/node/pull/10865 has a test to use shared library files of `node_test_engine` built with gyp. 

Currently the tests on Windows and arm were failed because the shared library files were lost in CI environment. 
They can be solved by including `Release\node_test_engine.dll` in Windows tests and `out/Release/libnode_test_engine.so` in arm tests in `binary/binary.tar.gz` and `binary/binary.tar.xz` .  Could someone help to do it?

**Comment by shigeki** [comment]
Does anyone take care of this?  It's no problem to move all files in `out/Release`.

**Comment by joaocgreis** [comment]
Sorry @shigeki , I set up those jobs but was away for some weeks so I only noticed this now. I included those files in the binary package. Here is a test run: https://ci.nodejs.org/view/All/job/node-test-commit-windows-fanned/6870/ . For the `arm-fanned` job I added the code but did not test because the job is disabled (https://github.com/nodejs/build/issues/611). Please reopen if there's any problem!

**Comment by shigeki** [comment]
@joaocgreis No, problems. Many thanks for doing it. I'm going to submit a new ci job from now.  I appreciate your work.
