### ISSUE TITLE
test-osuosl-aix61-ppc64_be-2 out of /tmp space

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#600]
Jobs failing when run on test-osuosl-aix61-ppc64_be-2

**Comment by mhdawson** [comment]
Cleaned up /tmp so should be ok now.

I know that we had prior issues with citgm filling up tmp will talk to @gibfahn to see if we think this was a left over of that or something else.

**Comment by gibfahn** [comment]
If it's the same problem we had last time (#560) then the problem is caused by citgm. I thought that'd been fixed, but perhaps it hasn't yet. The way to tell is that most of the space is used by the folders listed in https://github.com/nodejs/build/issues/560#issuecomment-272867766.

We'll try to fix it in citgm anyway, because it's a good idea to have the temp directory in the workspace, but it might be worth increasing /tmp anyway.
