### ISSUE TITLE
jenkins build-slaves: init scripts

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#62]
@rvagg brought up that some (most?) buildslaves lacks init scripts for starting jenkins after a reboot. Lets add these to ansible.

**Comment by rmg** [comment]
If I recall correctly, the reason was that they need a tty. We may need to take that into account when creating the init scripts.

**Comment by rvagg** [comment]
yes, the tty was the blocker, _but_ this was pre-1.0.0 and things may have changed since then and even if they haven't perhaps we should make them change--failures were to do with width & height of the tty being `0` (or close to), but they are already like that for the dockerised tests and they don't fail on that any more

**Comment by jbergstroem** [comment]
Which tests were failing without a TTY?

**Comment by rvagg** [comment]
I think this may have actually been more of a libuv problem than an io.js problem, testing the width and height of the tty was one problem I recall

**Comment by jbergstroem** [comment]
Should we perhaps start adding init scripts then?

**Comment by rvagg** [comment]
we should do that .. I really need a solution for the raspberry pi machines at a minimum because they are so flaky and I'm regularly having to restart the slaves on them manually.

probably need the full gamut of init, upstart and systemd to cover what we're running

**Comment by jbergstroem** [comment]
There's enough examples of jenkins launched from init, upstart and systemd for us to get something working. I don't think I have access to any of the stock linux boxes but can play around on local vm's and do PR's.

**Comment by rvagg** [comment]
FYI I've just put `monit` on all the raspberry pi servers because I'm sick of restarting `java` on them, not worth putting in the ansible setup yet because it'd be nice to have init scripts take care of most of it but this is pretty much a replacement because it'll also work if they are rebooted.

/etc/monit/conf.d/jenkins:

```
check process jenkins
  matching slave.jar
  start program = "/bin/su iojs -c 'cd /home/iojs && /home/iojs/start.sh'"
  stop program = "/bin/su iojs -c 'pkill jenkins'"
```

**Comment by jbergstroem** [comment]
We can just replace start stop with the init equivalent when due.

**Comment by rvagg** [comment]
I just hacked together an upstart script for the armv8 slave that's running ubuntu 14.04 because the slave was dead and instead of just restating it I figured I should do it properly.

This machine isn't ansibilised (yet).

```
start on runlevel [2345]
stop on runlevel [!2345]

respawn
respawn limit 4 240

setuid iojs

env USER=iojs
env SHELL=/bin/bash
env HOME=/home/iojs
env PATH=/usr/lib/ccache:/usr/bin:/bin
env NODE_COMMON_PIPE=/home/iojs/test.pipe
env OSTYPE=linux-gnu
env ARCH=arm64
env DESTCPU=arm64

exec /usr/bin/java \
          -jar /home/iojs/slave.jar \
          -jnlpUrl https://jenkins-iojs.nodesource.com/computer/iojs-linaro-armv8-ubuntu1404/slave-agent.jnlp \
          -secret secretz
```

**Comment by jbergstroem** [comment]
We still lack support in some ubuntu flavours, but I still think we should close this and (if needed) open something more specific.
