### ISSUE TITLE
Add a --without-ssl node-test-commit job

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#643]
See https://github.com/nodejs/node/pull/11734, it would be useful to have some testing to catch the non-default build cases (there are probably more than just `--without-ssl`).

**Comment by richardlau** [comment]
Related #419 (`--without-intl`)

**Comment by sam-github** [comment]
Related https://github.com/nodejs/node/pull/11747

**Comment by gibfahn** [comment]
@jbergstroem @mhdawson could one of you clone one of the build jobs (node-test-commit-linux I guess) so I can try to get this set up?

**Comment by mhdawson** [comment]
I assume you will cut it down to run on a single linux variant only, as we don't want to double the load and the one would probably be enough to catch compile problems. 

Cloned one for you to work on here:  https://ci.nodejs.org/view/All/job/node-test-commit-linux-gibson/

**Comment by rvagg** [comment]
This came up the other day but I don't recall where. @mhdawson & @danbev, where was that, IRC?

Anyway, I tried one out, the config is all done and waiting to be enabled (by ticking the label "" to the list of node labels in the job) but it has a snag, perhaps the first of many? https://ci.nodejs.org/job/node-test-commit-linux-containered/3916/nodes=ubuntu1604_sharedlibs_withoutssl_x64/console (you'll have to scroll up a bit, above the addons)

`make test-ci` involves npm which tries to do an update check but fails because that loads crypto

```
09:36:53 Makefile:649: recipe for target 'tools/doc/node_modules/js-yaml/package.json' failed
09:36:53 make[2]: *** [tools/doc/node_modules/js-yaml/package.json] Error 1
09:36:53 Makefile:608: recipe for target 'doc-only' failed
09:36:53 make[1]: *** [doc-only] Error 2
```

Before it can be turned on, we're going to need to skip this step for this type of build.

**Comment by maclover7** [comment]
This is a thing now: https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu1604_sharedlibs_withoutintl_x64/

**Comment by danbev** [comment]
@maclover7 Awesome, thanks for that!
