### ISSUE TITLE
Build WG meeting 28 March 2017 - 4PM EST

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#660]
### When

Mar 28, 2017 4 PM EST 

### Where
- Hangouts on Air, for participants:  https://hangouts.google.com/hangouts/_/ytl/KOIfKbVSfs8CMc3OB3XsoxoKlDtgpIGkbsfAvJbRIe8=?eid=100598160817214911030&hl=en_US&authuser=0
- Youtube stream, for viewers:  https://www.youtube.com/watch?v=znJWeDabfOw
- events page, https://www.youtube.com/my_live_events?filter=scheduled
- Minutes document: https://docs.google.com/document/d/1j_wYeNgRxywx7GvJSbRDUWkkNeGCzdog4OMO3IKu6KY/edit?usp=sharing

### Agenda

Extracted from `wg-agenda` [issues](https://github.com/nodejs/build/issues?q=is%3Aopen+is%3Aissue+label%3Awg-agenda) and [pull requests](https://github.com/nodejs/build/pulls?q=is%3Aopen+label%3Awg-agenda+is%3Apr) from this repo.

* Move nodejs/readable-stream CI from Travis to Jenkins [657](https://github.com/nodejs/build/issues/657)
* Add Kunal Pathak to Build WG [649](https://github.com/nodejs/build/issues/649)
* file and directory names for downloads [515](https://github.com/nodejs/build/issues/515)
* Draft text for HSTS communication [484](https://github.com/nodejs/build/issues/484)
* TAP Plugin issues on Jenkins [453](https://github.com/nodejs/build/issues/453)

All welcome of course, primarily @nodejs/build focused but we're happy to expand.

**Comment by rvagg** [comment]
Question @ the Board for @nodejs/build: what is the level of concern re bus-factor for people and redundancy for build resources required for releases. The question is specifically around the ARM cluster and the planned outage we had there (I clarified that releases were not impacted), but from our perspective I think macOS redundancy is much more of a problem right now and the people bus-factor might be something else we should be putting our attention on.

**Comment by jbergstroem** [comment]
I'd put macOS redundancy and perhaps my ability to a degree as well. I definitely haven't been as responsive and/or active this quarter as last quarter.

**Comment by rvagg** [comment]
@mhdawson I don't think the 3pm one is right, that's 6am for me but I haven't ended DST yet, that'll happen next week and this slot will move to 5am, it's never been that early for me, it's always been 7am during DST and 6am during the rest of the year. I suspect that calendar entry was set to a US TZ and got shifted when the US hit DST when it should have been tied to UTC. Either way, can we do this at 4pm Eastern? Otherwise I'm won't make it.

**Comment by williamkapke** [comment]
I added this to the calendar with EST timezone. I usually always add them as UTC but this one was - specifically stated at EST. I should have clarified. Happy to update to UTC - just LMK!

![image](https://cloud.githubusercontent.com/assets/739813/24388573/897cf88e-1330-11e7-933d-901658741f57.png)

I'm confused at what time it's really happening now- the title of this issue says 4PM EST, the OP says 3PM EST.

**Comment by piccoloaiutante** [comment]
I should be able to make it.

**Comment by mhdawson** [comment]
Ok, based on the input from @rvagg lets agrees its 4pm EST.

**Comment by gibfahn** [comment]
@williamkapke is that calendar linked from nodejs/node?

**Comment by richardlau** [comment]
@gibfahn There's a link at the bottom of the TSC meeting minutes, e.g. https://github.com/nodejs/TSC/blob/master/meetings/2017-03-09.md

**Comment by williamkapke** [comment]
@mhdawson I've updated it to use 8PM GMT:
![image](https://cloud.githubusercontent.com/assets/739813/24415575/befca0f2-1396-11e7-8a31-d9860e2c8775.png)

- http://www.wolframalpha.com/input/?i=8pm+UTC,+Mar+23,+2017+in+local+time
- https://www.timeanddate.com/worldclock/fixedtime.html?msg=Build%20WG%20Meeting&iso=20170328T20

**Comment by jbergstroem** [comment]
Sorry for my late notice but I won't be able to join. My efforts since last time:
- jenkins master security updates, twice
- play around with the tap2junit parser -- it will bail on citgm stuff; needs to be refactored
- fix disk issues on joyent freebsd workers which seems to have changed how disk is mounted which led to disk issues.
- housekeeping on a few workers

..as for my input:
- I'd like to bring up MacOS workers for discussion. We had an interesting opportunity which led into [this](https://github.com/nodejs/build/issues/539) and back to sleep. After we've sorted that we can revisit the opportunity and increase both redundancy and os versions tested.
- Bus factor: I like Michaels idea of primary/backup for positions. Which would these positions be though? My ambition is that everybody in the build group would help out with the level of access they have -- meaning all of our members should feel free to look at restarting/debugging individual workers. As for the higher tiers; we need to start by defining these positions.
- Adding Kunal: SGTM 👍 
- I believe we were to remove the agenda label from a few of the raised topics as a result of previous meeting. Not sure that happened.

**Comment by mhdawson** [comment]
Link for participants: https://hangouts.google.com/hangouts/_/ytl/KOIfKbVSfs8CMc3OB3XsoxoKlDtgpIGkbsfAvJbRIe8=?eid=100598160817214911030&hl=en_US&authuser=0

**Comment by williamkapke** [comment]
I asked a question in IRC

**Comment by gibfahn** [comment]
Minutes here: https://github.com/nodejs/build/issues/660

**Comment by gibfahn** [comment]
Minutes landed, closing.
