### ISSUE TITLE
Build WG meeting 18 April 2017 at 4 EST

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#683]
Putting in this placeholder as  a reminder.  Will fill in details on Tuesday (Friday/Monday are a holiday for me) if nobody beats me to it.

### When

Apr 18, 2017 4 PM EST - [time in your timezone](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Build+WG+Meeting&iso=20170418T20&p1=1440&ah=1)

### Where
- Hangouts on Air, for participants:  https://hangouts.google.com/hangouts/_/ytl/vPmERoYEfy59XZzr6SjnYXIlmOVcWq1pDnbXXjz2714=?eid=100598160817214911030&hl=en_US
- Youtube stream, for viewers:  http://youtu.be/gnE1dBTNWTw
- events page, https://www.youtube.com/my_live_events?filter=scheduled
- Minutes document: https://docs.google.com/document/d/1RZ9Yo9mUl64O3LNZY8U-DeAEth3zNTgHgvnHF2j8Cpc/edit
- Previous meeting: https://github.com/nodejs/build/issues/660

### Agenda

Extracted from `wg-agenda` [issues](https://github.com/nodejs/build/issues?q=is%3Aopen+is%3Aissue+label%3Awg-agenda) and [pull requests](https://github.com/nodejs/build/pulls?q=is%3Aopen+label%3Awg-agenda+is%3Apr) from this repo.

* Request to join the jenkins-admins team (gibfahn) #667
* adding nodejs-foundation user to npm modules managed by build team https://github.com/nodejs/TSC/issues/211#issuecomment-294880235
* Transfer Jenkins OAuth Application to nodejs https://github.com/nodejs/build/issues/687

All welcome of course, primarily @nodejs/build focused but we're happy to expand.

**Comment by mhdawson** [comment]
@nodejs/build

**Comment by rvagg** [comment]
Unlikely to make it this week sorry. Status:

* Restored a couple of Pi's, pi2-2 and pi2-10 (don't have their real names at hand). Wiped and reinstalled but I'm worried about their storage, they may be faulty so we'd best keep an eye on them. 
* Pinged miniNodes and got the 3rd Odroid C2 back online
* Did the CF log download thing, PR in this repo. Still haven't done a full validation that the data is exactly how we want it but that's 1/2 done - first pass is to turn it into nginx log format and pass it through our metrics scripts to see if they line up.
* Pending TODO from Johan to test the LB work he's done, on the surface it looks OK but I haven't probed deeply enough to give a :+1: but if others are available to help validate then please let him know!
* Reached out to Voxer to see if we can at least get status info on our relationship with them.
* Still needing to make proper progress with the other macOS line of enquiry we have open, will report back soon on that. 
* Got hooked up with packet.net thanks to ARM introducing me to them - they are a SoftBank investment like ARM so have a strategic interest in server-side ARM so part of their offering is bare metal ARM64 cloud resources based on the latest server chips and it's very impressive. Myself, Johan and Michael have access to start tinkering and figuring out how best to use those resources because they're also offering general cloud resources to help us diversify which is great!

**Comment by jbergstroem** [comment]
While at it; perhaps establish a standard where we use a certain emoji to indicate availability? +1/-1 or something. It would not just show if we can be there; but also if you abstain or just don't reply (general build wg activity).

**Comment by piccoloaiutante** [comment]
@jbergstroem lets go 👍 and 👎 for showing who is going to attend or not..

**Comment by jbergstroem** [comment]
@piccoloaiutante yeah; lets make a note about it in the meeting and add it to the 'template' for next meeting.

**Comment by piccoloaiutante** [comment]
has it already started?

**Comment by joaocgreis** [comment]
@piccoloaiutante no, we're waiting for the link from @mhdawson

**Comment by mhdawson** [comment]
just about to start the hangout, 2 mins

**Comment by mhdawson** [comment]
link: https://hangouts.google.com/hangouts/_/ytl/vPmERoYEfy59XZzr6SjnYXIlmOVcWq1pDnbXXjz2714=?eid=100598160817214911030&hl=en_US&authuser=0

**Comment by kfarnung** [comment]
I'm getting 403 forbidden for the hangouts link.

**Comment by gibfahn** [comment]
@kfarnung odd, it's working for me/us: https://hangouts.google.com/hangouts/_/ytl/vPmERoYEfy59XZzr6SjnYXIlmOVcWq1pDnbXXjz2714=?eid=100598160817214911030&hl=en_US

**Comment by joaocgreis** [comment]
@kfarnung try removing everything after `?` or the `=` before, worked for me once

**Comment by kfarnung** [comment]
Thanks @joaocgreis, not sure what was going on, but opening incognito worked.
