### ISSUE TITLE
Clean up Jenkins configs

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#696]
I was looking at https://github.com/nodejs/build/issues/685#issuecomment-296765873, and I noticed that the combination filter for [node-test-commit-linux](https://ci.nodejs.org/job/node-test-commit-linux) is full of a load of stuff that is no longer required.

```groovy
NODES_SUBSET=="all_nodes" || NODES_SUBSET=="io.js" || (NODES_SUBSET=="0.12" && 
["centos5-32","centos5-64","centos6-64","centos7-64","debian8-64","debian8-x86", 
"ubuntu1204-64","ubuntu1404-32","ubuntu1404-64","ubuntu1504-64"].contains(nodes)) || 
(NODES_SUBSET=="0.10" && ["centos5-32","centos5-64","centos6-64","centos7-64","debian8-64",
"ubuntu1204-64","ubuntu1404-32","ubuntu1404-64","ubuntu1504-64"].contains(nodes))
```

As I understand it, we currently build everything on every platform, so we could remove the combination filter (and `NODES_SUBSET`) entirely. 

---

The other thing that might be helpful is to use `Label expression` rather than `slaves`, as it allows you to copy and paste the labels in rather than having to scroll through that tiny view and click on things. Otherwise it's exactly the same:

![image](https://cloud.githubusercontent.com/assets/15943089/25353035/dfadb08a-2925-11e7-9a53-591db00b13eb.png)

I'm quite keen not to unilaterally change things, so does anyone have any feedback?

**Comment by joaocgreis** [comment]
Combination filter: Happy to welcome a simplification for this! There are at least 3 mechanisms for selecting what configurations run for what versions:
- `NODES_SUBSET`: This is used to support testing versions 0.10 and 0.12 (and iojs at some point). Can we already delete that? It will no longer be possible to test 0.10 and 0.12 (at least without knowing what configurations can be ignored). I suspect testing doc only changes also uses this.
- `NODE_MAJOR_VERSION`: I introduced this one to compile with VS2013 only for <=v6.x, I believe it is the cleanest way to achieve this. It is used by the Windows jobs, please do not delete it. Others could be converted to this mechanism.
- An `if` in the beginning of the Jenkins script: (used at least by node-test-commit-linux to exclude clang) I don't like this one because it will show a configuration as run and green when it is actually not supported and fails.

Label expression: I'm ok if you want to change.

**Comment by gibfahn** [comment]
This should probably still be done, but I'm goingt to be optimistic and hope that https://github.com/nodejs/build/issues/838 will handle it.
