### ISSUE TITLE
add `VS_VERSION=vs2015,label=win2008r2` option to `node-stress-single-test`

### ISSUE THREAD

**Issue by refack** [nodejs/build#722]
Most often flaky test fail on `VS_VERSION=vs2015,label=win2008r2` but I don't know who to run a `win2008r2` with `VS_VERSION=vs2015`
e.g. 
https://ci.nodejs.org/job/node-test-binary-windows/8471/
https://ci.nodejs.org/job/node-test-binary-windows/8362/
https://ci.nodejs.org/job/node-test-binary-windows/8402/

**Comment by gibfahn** [comment]
Easiest way to add this would probably be a choice parameter for `VS_VERSION`, with the same choices as the `test-binary` job (`vs2013 vs2015 vcbt2015 vs2015-x86`). It'd only be used if a windows build was chosen from the dropdown.

Happy to add this if there are no objections (cc/ @joaocgreis @Trott )

**Comment by Trott** [comment]
> Happy to add this if there are no objections (cc/ @joaocgreis @Trott )

I'm a frequent user of the stress tests but not knowledgable about the configuration etc. @joaocgreis is the authority AFAIK.

**Comment by gibfahn** [comment]
>I'm a frequent user of the stress tests but not knowledgable about the configuration etc. 

Yeah, I was looking for user feedback from you and Jenkins feedback from João.

**Comment by joaocgreis** [comment]
All our Windows 2008 machines have VS2013 installed (and should be only VS2013 - having only one version is good armor against errors in config scripts). We need to have VS2013 in the Windows 2008 machines to cover building addons tests with VS2013 as part of `node-test-binary-windows`.

But since we dropped VS2013 to build node, the stress-tests job is useless for Windows 2008. I believe the best way forward is to have a fanned stress-tests job (like we already have for pi1) that mirrors the configuration of the test-commit job. I actually have most of it already in place, I'll clean it up and let you know.

**Comment by maclover7** [comment]
ping, does this need to stay open?

**Comment by joaocgreis** [comment]
Yes, to be able to use the stress-tests job with recent node versions (that compile only with vs2017) and any windows version, we'd need cross compiling on that job. Unfortunately this was not as straightforward as I initially hoped. Actually, this job is a good candidate for pipeline conversion.

**Comment by sam-github** [comment]
Closing as stale, but if anyone wants to take this up feel free to reopen.
