### ISSUE TITLE
Add /home/iojs/cores to smartos ansible scripts

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#738]
IIUIC we aren't currently creating the `/home/iojs/cores` directory on our smartos boxes, which means that coredumps aren't saved when something goes wrong. We should create this directory in our [ansible scripts](https://github.com/nodejs/build/tree/master/ansible).

I _think_ this only needs to be done on smartos test machines.

@jbergstroem correct me/this if I'm wrong.

Refs: https://github.com/nodejs/node/issues/13227#issuecomment-304234954

cc/ @misterdjules

**Comment by misterdjules** [comment]
Thank you!

**Comment by jbergstroem** [comment]
@gibfahn sounds about right! PR welcome.

**Comment by joaocgreis** [comment]
The `cores` directory is filling up the drives now. We have several smartos machines offline in CI because of this. I just cleaned up the `cores` directory in `test-joyent-smartos15-x64-1` to unblock CI, there was no worker for `smartos15`.

What about adding something like `find /home/iojs/cores/ -type f -mtime +3 -delete` to crontab to keep only 3 days of cores? (I don't know if this is an appropriate value, but given that this does not depend on the number or size of files, it makes sense to be conservative.)

**Comment by jbergstroem** [comment]
> @joaocgreis said:
> What about adding something like §find /home/iojs/cores/ -type f -mtime +3 -delete§ to crontab to keep only 3 days of cores? 

I like this; perhaps up it to a week or so though.

**Comment by misterdjules** [comment]
@joaocgreis 

> What about adding something like find /home/iojs/cores/ -type f -mtime +3 -delete to crontab to keep only 3 days of cores?

Can we bump that to 7 days? I'm thinking 3 days might be a bit short between the time a test failure happens and someone is able to get the corresponding core from one of the hosts.

**Comment by joaocgreis** [comment]
7 days sounds good, I'll add it.

**Comment by refack** [comment]
Why can't we have this for all machines?
Ref: https://github.com/nodejs/node/issues/14014

**Comment by juggernaut451** [comment]
@refack @joaocgreis @maclover7 @misterdjules  is this still open?

**Comment by sam-github** [comment]
Closing as stale, but if anyone wants to take this up feel free to reopen.
