### ISSUE TITLE
Redirect /dist/latest/docs/api/ to /dist/latest-v.X.X/docs/api/

### ISSUE THREAD

**Issue by fhemberger** [nodejs/build#763]
I was looking at the analytics data for the website (https://github.com/nodejs/nodejs.org/issues/1268) and noticed, that `/dist/latest/docs/api/` is a entry on it's own. IMHO we should redirect `/dist/latest/docs/api/` to whatever the latest current version is (e.g. `/dist/latest-v8.x/docs/api/`).

Thoughts?

**Comment by Trott** [comment]
Hard to say. If someone bookmarks, do they want the specific version they're looking at or do they want the bookmark to always go to the latest version? I'm inclined to think the latter, but I don't really know.

**Comment by Trott** [comment]
I'm going to close due to long period of inactivity. Feel free to re-open if this is something that should be further discussed. Maybe ask that it get put on the Build WG agenda to make sure it doesn't get lost like it seems to perhaps have been the first time. Anyway, I'm not closing because this is a bad idea or anything. Just closing things that have been inactive for more than a year or so.
