### ISSUE TITLE
WARNING: Jenkins update to 2.60.1 requires Java 8

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#775]
### Needs doing:

- [x] Create a job to run a `java -version` (and probably a `which java`/`where java`) on each machine, so we can see where we're going to have issues. If the job failed on Java <8 that would be ideal
- [ ] Upgrade ansible scripts for machines which need it.
- [ ] Apply scripts to machines and get us ready to upgrade
- [ ] Upgrade and make sure things still work (some machines may not be using the Java in the path for Jenkins connection)

---

Note for @nodejs/build @nodejs/jenkins-admins considering clicking the shiny red button to update Jenkins

![image](https://user-images.githubusercontent.com/15943089/27628669-ab8204ce-5be7-11e7-8534-13bde397990d.png)

In the [changelog for 2.60.1](https://jenkins.io/changelog-stable/) it notes that it requires Java 8 to be installed on all the hosts.

>2.60.1 is the first Jenkins LTS release that requires Java 8 to run. If you're using the Maven Project type, please note that it needs to use a JDK capable of running Jenkins, i.e. JDK 8 or up. If you configure an older JDK in a Maven Project, Jenkins will attempt to find a newer JDK and use that automatically. If your SSH Slaves fail to start and you have the plugin install the JRE to run them, make sure to update SSH Slaves Plugin to at least version 1.17 (1.20 recommended).

I'm pretty sure we don't have Java 8 on all our hosts, so updating will stop those hosts being able to connect.

**Comment by gibfahn** [comment]
I guess the plan would be to confirm that all our machines are running Java 8 and then update.

**Comment by jbergstroem** [comment]
```console
$ ssh ci java -version              
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by gibfahn** [comment]
@jbergstroem sure, but what about the individual hosts? For example I'm pretty sure AIX is using Java 7 (see [here](https://github.com/nodejs/build/blob/master/setup/aix61/manualBootstrap.md#gettext-java-make)).

**Comment by jbergstroem** [comment]
@gibfahn I didn't get that even agents now require java 8. What kind of crazy is this :(

**Comment by jbergstroem** [comment]
So, anyone with any ideas on how we move forward here? We are out of LTS meaning any security bugs (expect them) will hit us pretty hard.

**Comment by bnoordhuis** [comment]
There is a Java 8 JDK for AIX ([link](https://developer.ibm.com/javasdk/downloads/sdk8/)), same for FreeBSD.  The only problem might be SmartOS (which frankly I couldn't care less about.)

**Comment by geek** [comment]
SmartOS has Java 8 support https://gist.github.com/dekobon/305883fb6d776b0c9fc1

**Comment by jbergstroem** [comment]
There's a few older systems like centos5 which doesn't pack it either. If this is only a matter of adding more package source repos then it might not be as bad then.

**Comment by gibfahn** [comment]
Discussed in the meeting (minutes: https://github.com/nodejs/build/pull/845), consensus was that we need to deal with this. I'll put some concrete steps in the first comment.

**Comment by joaocgreis** [comment]
Here is a first version of the job: https://ci.nodejs.org/view/All/job/check-java-version/2/ feel free to edit as needed. I left Windows out because all Windows machines already have Java 8.

**Comment by rvagg** [comment]
I improvified it: cross-platform bash execution, use the parent-of-parent to figure out how `java` is executed (not using `which java` which may be incorrect). Changing the `grep` of the version line to be OK with OpenJDK and other types of JRE.

https://ci.nodejs.org/view/All/job/check-java-version/13/ is the latest run. A quick visual inspection suggests that discounting the Pi's, we're more than 1/2 way there.

**Comment by gibfahn** [comment]
Did someone delete the job?

>use the parent-of-parent to figure out how `java` is executed (not using `which java` which may be incorrect).

I was going to suggest we make `grandparent java != which java` an error, unless we're aware of some specific exceptions it'd be nice if the default Java (in the path) was always the one used to run Jenkins.

**Comment by rvagg** [comment]
@gibfahn log in to ci.nodejs.org before clicking the link above, I believe it's been made private, which is probably a good idea.

**Comment by gibfahn** [comment]
Okay, updated it to be unstable (yellow) if Java is at least 8 but Jenkins doesn't use the one in the path.

**Comment by gibfahn** [comment]
So I was looking at this and I realised that it doesn't get the full java path in a lot of cases, because it's printing the `comm` part of the `ps` field, which is usually just the `basename` of the command (so it just returns `java`).

I changed it from:

```bash
JAVA_CMD=$(ps -p $HUDSON_PID -o comm=)
```

to

```bash
JAVA_CMD=$(ps -p $HUDSON_PID -o args= | awk '{print $1}')
```

**Comment by gibfahn** [comment]
Updated the job to handle windows (although how good that windows handling is is questionable, @refack @joaocgreis feel free to double-check/correct).

https://ci.nodejs.org/view/All/job/check-java-version/37/

This should be pretty much accurate.

**Comment by refack** [comment]
https://ci.nodejs.org/view/All/job/check-java-version/37/label=test-rackspace-win2012r2-x64-9/console
Looks sane ✔️

**Comment by joaocgreis** [comment]
Looks good. Two notes:
- I recommend having `set -e` on all jobs (`set -x` is already there). When it makes a script fail we usually want it to.
- We explicitly don't want to run Jenkins as a server on Windows. There were issues with it in the past, though I suspect they might have been fixed by the recent stdio changes.

**Comment by gibfahn** [comment]
>I recommend having set -e on all jobs (set -x is already there). When it makes a script fail we usually want it to.

Jenkins runs with `-ex` by default doesn't it? Seems to looking at how the script gets called in the console output:

```
[check-java-version] $ /bin/sh -xe /tmp/hudson1653446783271619934.sh
```

**Comment by gibfahn** [comment]
>We explicitly don't want to run Jenkins as a server on Windows. There were issues with it in the past, though I suspect they might have been fixed by the recent stdio changes.

Okay, good to know. What issues were those? We converted to running as a service and haven't had any issues with it (unless we didn't realise they were related).

Does the `jenkins.bat` file get run automatically run on reboot? I've actually found the service to be a bit of a pain, it has to be run as an administrator, and it has to be restarted if you change passwords.

**Comment by joaocgreis** [comment]
> Jenkins runs with `-ex` by default doesn't it?

True. I tend to forget that because I always add the `#!/bin/bash -ex` line to make the script run bash and not dash. The current script looks good as is.

> Okay, good to know. What issues were those? We converted to running as a service and haven't had any issues with it (unless we didn't realise they were related).

I didn't investigate it at the time, just converted the job to not use a service. I remember something because input/output was not available, thus I suspect it was fixed by https://github.com/nodejs/node/pull/11863 . Good to know it works as a service now, did you somehow try to verify if all tests are still running as expected? We have many tests that skip, some we want them to skip on CI (Windows unsupported, things like that), but I suspect some may start skipping because of changes like that, when they should really run. This makes CI very brittle in my opinion, but is the balance we have to make users able to easily test locally, and I don't have a good idea for fixing it.

The CI machines use [autologon](https://github.com/nodejs/build/blob/69aeda3a434f16a6c2b3cbd9f8074f7faad6ebf7/setup/windows/resources/Enable-Autologon.ps1) and [run `jenkins.bat` on startup](https://github.com/nodejs/build/blob/69aeda3a434f16a6c2b3cbd9f8074f7faad6ebf7/setup/windows/resources/Jenkins-Shortcuts.ps1#L4). It doesn't work perfectly every time, sometimes autologon fails and Jenkins only starts when we manually login to the machine, but has been good enough.

**Comment by gibfahn** [comment]
>True. I tend to forget that because I always add the #!/bin/bash -ex line to make the script run bash and not dash. 

Fair enough, I actually removed the shebang because it doesn't work with Git Bash.

>Good to know it works as a service now, did you somehow try to verify if all tests are still running as expected?

Internally (IBM) we use it as a service, and we do full CI runs, without ignoring flaky tests. Haven't seen any issues with that. I should check whether things are being skipped though, that's a good point!

**Comment by refack** [comment]
Can we stop calling it `Git Bash`, it's `MSYS Bash`. Git for Windows is just the package that deploys it...

**Comment by gibfahn** [comment]
>Can we stop calling it Git Bash, it's MSYS Bash. Git for Windows is just the package that deploys it...

<img width="658" alt="image" src="https://user-images.githubusercontent.com/15943089/30138752-f07d8ccc-9361-11e7-9a26-44f46dece57e.png">

https://git-for-windows.github.io/

It's the version of bash that comes with Git for Windows. As they changed the name from Msysgit to Git for Windows (see [StackOverflow](https://stackoverflow.com/a/784743/2799191)), no-one knows what `MSYS Bash` is. I prefer Git Bash, everyone knows what that means.

**Comment by refack** [comment]
Fine. But it's still a misnomer.
<sub>P.S. They only changed the name of the Git package from MSYSGit to Git for Windows. It's still MSYS Bash 👴 </sub>

**Comment by gibfahn** [comment]
@gdams did the upgrades for our internal machines for this, so he'd probably be well placed to make the same changes in ci.nodejs.org.

**Comment by gdams** [comment]
yeah I'm happy to take a look at this!

**Comment by rvagg** [comment]
@gdams anything to report on this? Looks like we're going to have to move faster on this now.

**Comment by rvagg** [comment]
I've manually updated the benchmark server so now we just have these left:

* test-marist-zos13-s390x-1
* test-marist-zos13-s390x-2
* test-osuosl-aix61-ppc64_be-1
* test-osuosl-aix61-ppc64_be-2
* test-osuosl-ubuntu14-ppc64_be-1
* test-osuosl-ubuntu14-ppc64_be-2
* test-osuosl-ubuntu14-ppc64_le-1
* test-osuosl-ubuntu14-ppc64_le-2

**Comment by mhdawson** [comment]
I've updated the two le test machines.  To speed things up I did not use ansible, but these were the steps that we can move into the ansible scripts:

```
su - iojs
wget https://github.com/AdoptOpenJDK/openjdk8-releases/releases/download/jdk8u144-b01/OpenJDK8_ppc64le_Linux_jdk8u144-b01.tar.gz
gunzip OpenJDK8_ppc64le_Linux_jdk8u144-b01.tar.gz
tar -xvf OpenJDK8_ppc64le_Linux_jdk8u144-b01.tar
ln -s jdk8u144-b01/jre/bin jdk
```

And update these 2 lines in the /etc/init/jenkins.conf file

```
env PATH="$HOME/jdk:/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

exec /home/iojs/jdk/java -Xmx256m -jar "$HOME/slave.jar" \
```

I've not included the full file as there is some sensitive info in there.  I was not necessarily happy about having to provide the full path to `/home/iojs/jdk/java` but it was the only one of the options that I tried.  We can revisit as we update the ansible files.

**Comment by mhdawson** [comment]
In terms of updating the release machine if you give me access I can do that as well.

Now looking at the be linux machines.

**Comment by mhdawson** [comment]
I checked these 2

```
test-marist-zos13-s390x-1
test-marist-zos13-s390x-2
```

They already use java8  as this is in the script that starts the agent:

/usr/lpp/java/J8.0_64/bin/java -Dfile.encoding=ISO8859_1 -Xmx128m \

**Comment by mhdawson** [comment]
ok the test machines for both PPC flavors should be good now.  I think that just leaves

```
test-osuosl-aix61-ppc64_be-1
test-osuosl-aix61-ppc64_be-2
```
(and the release machines )

**Comment by rvagg** [comment]
Sorry @mhdawson, I didn't realise you hadn't been added to build/release already! I've done that now and you should be able to grab the nodejs_build_release key from in secrets.

@mhdawson @gdams would it be OK if we go ahead with the Jenkins upgrade and just pull those AIX PPC machines from the test pool for now and add them back in when they're done?

**Comment by mhdawson** [comment]
@rvagg I assume we are going to start with the test ci since that one is more broadly accessible right ? If we at least still have AIX in the release CI it will make sure we don't miss any releases, although I'm hoping we'll get the machines updated by tomorrow anyway.  So long way of saying I think its reasonable to go ahead with the Jenkins upgrade and pull AIX until we get them updated

**Comment by rvagg** [comment]
Yep, and in the past we've treated test ci as a staging for changes to release ci since it's more critical anyway, we can break test ci and it's annoying to contributors but if we break release ci cause critical problems for users. So we'll see what the fall-out is for an upgrade of test ci first! I'll go ahead and get it done now and pull out AIX from node-test-commit if they don't reconnect (which is what we expect will happen I think?).

**Comment by mhdawson** [comment]
I went ahead and put Java 8 on release-osuosl-ubuntu1404-ppc64_be-1 and release-osuosl-ubuntu1404-ppc64_le-1 but I'll wait on switching over /etc/init/jenkins.conf to using it until we've soaked the change a bit more on the test machines.

**Comment by rvagg** [comment]
Upgraded ci.nodejs.org, still waiting for the Pi's to all reconnect but they normally take a while anyway so I'll be patient. test-osuosl-aix61-ppc64_be-1 and test-osuosl-aix61-ppc64_be-2 did not come back, as expected I suppose.

**Comment by rvagg** [comment]
Thanks everyone for contributing to this so far btw, it's been a tough job so far.

**Comment by rvagg** [comment]
@nodejs/jenkins-admins FYI I've had to untick "Build if SCM changes" in the Advanced section of the MultiJob sub-jobs in node-test-commit, node-test-commit-arm-fanned and node-test-commit-windows-fanned, I guess this is new, or the default to ticked is new or something, because it's causing problems with the fanned jobs but also it's just plain annoying when testing if something works. I'm not seeing a good case for having it on in our infra.

**Comment by rvagg** [comment]
Looking good: https://ci.nodejs.org/job/node-test-commit/13093/

still got the arm-fanned ESM addon tests failing, @refack is having a play with trying to fix that. It's a @nodejs/build thing rather than a core thing so if there are more of us that can lend him a hand then he'd probably appreciate it.

**Comment by gdams** [comment]
okay I have brought both the AIX machine back online using a temporary version of IBM Java 8 located in `/home/iojs/jdk8/`

**Comment by mhdawson** [comment]
There seems be a problem running the test  job, investigating.

**Comment by mhdawson** [comment]
Looks like it might be the way the agent was started.  Don't think /etc/rc.d/rc2.d/S20jenkins start was used as these were not edited on the 2 AIX machines.

Edited and restarted agent and testing now, seems to be getting further.

**Comment by mhdawson** [comment]
Ok, tests jobs on both machines passed so I think we are back to being good.

**Comment by gibfahn** [comment]
>Looks like it might be the way the agent was started. Don't think /etc/rc.d/rc2.d/S20jenkins start was used as these were not edited on the 2 AIX machines.

We really should document this somewhere.

**Comment by refack** [comment]
Cross-ref https://github.com/nodejs/build/issues/916

**Comment by rvagg** [comment]
Going to close this, there's some ansible work that's left undone from https://github.com/nodejs/build/issues/775#issuecomment-333114062 and the IBM machines but mostly they relate to older distros that we're going to be phasing out soon(ish) and shouldn't need to ansible provision again.
