### ISSUE TITLE
Give bajtos access to run node-test-pull-request on CI

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#830]
Request from @Trott in https://github.com/nodejs/node/pull/13870#issuecomment-321605001

>Also: @nodejs/build Can we get @bajtos some access to the CI infrastructure so they can troubleshoot this a little more thoroughly?

**Comment by gibfahn** [comment]
+1 to giving Miroslav access, he works at IBM, @rsam, @mhdawson and I can vouch for him.

**Comment by sam-github** [comment]
+1, @bnoordhuis worked with Miroslav as well if you need more CTC members who know him.

**Comment by rvagg** [comment]
Fine by me. @bajtos how much access do you need? Since we're not well set up (yet) to revoke the keys that we share it's usually preferable to give out per-machine access. How many machines are we looking? If you can provide a list then one of us could manage providing access and later revocation. Also, you'll have to specify a pubkey, you have a bunch in https://github.com/bajtos.keys

**Comment by rvagg** [comment]
ah, just saw on IRC that this is just about the ability to just interact with Jenkins as @bajtos is not a collaborator. That's even easier, I've manually added him to the Jenkins security matrix, this can be revoked at any time via https://ci.nodejs.org/configureSecurity/ by a jenkins-admins user.

@bajtos you can go to https://ci.nodejs.org/ and trigger node-test-pull-request or any of the sub-jobs. You should only need to provide the pull request in node-test-pull-request and tick the "certify safe" box, or provide the commit and fork details in one of the node-test-commit(-*) jobs if you want to run them individually. Give a shout out on IRC if you need help, #node-dev is probably easiest since it has more active people and all the collaborators have access already.

**Comment by bajtos** [comment]
Hello, thank you very much for your help! The ability to trigger a new CI build is all I need for now. I have had some success with reproducing the failing tests locally using a VM, I'll try this route some more to see how far I can get, and also to save CI resources.

**Comment by bajtos** [comment]
I had successfully triggered a new CI job: https://ci.nodejs.org/job/node-test-pull-request/9667

Let's close this issue as done. I'll reopen it in case I'll need a direct access to build machines.

Thank you again for your help 🙇

**Comment by gibfahn** [comment]
I've removed @bajtos from the security matrix.

I think this is now done, @rvagg could you double-check?

**Comment by bajtos** [comment]
@gibfahn oh, could you please keep in in the security matrix? My work on #13870 is not done yet.

Sorry if my last comment made the impression that I don't need to trigger CI builds anymore.

**Comment by bajtos** [comment]
For posterity, @gibfahn has restored my permissions, I can trigger new CI builds again 👍

**Comment by gibfahn** [comment]
Sorry @bajtos, I misread your previous comment.

So we should keep this issue open while you need access, because that way the open issue reminds us to revoke the access afterwards.

**Comment by gibfahn** [comment]
@bajtos am I right in thinking this is no longer needed?

**Comment by bajtos** [comment]
Yes, I no longer need access to Node.js's CI.

**Comment by gibfahn** [comment]
Thanks, revoked.
