### ISSUE TITLE
Expired TLS certificate for ci.nodejs.org

### ISSUE THREAD

**Issue by aqrln** [nodejs/build#847]
![image](https://user-images.githubusercontent.com/4923335/29593511-751c4d98-87b3-11e7-8e53-6fcbd926b94f.png)

![image](https://user-images.githubusercontent.com/4923335/29593534-912590ee-87b3-11e7-805b-634d2fc748c6.png)

**Comment by aqrln** [comment]
Sites hosted on other Node.js domains that I tried loaded successfully with a new wildcard certificate expiring on November 21, 2019, so it is only an issue with the Jenkins server which still has an outdated certificate.

**Comment by gibfahn** [comment]
>You cannot visit ci.nodejs.org right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.

Yeah, this is an urgent issue.

**Comment by gibfahn** [comment]
Probably related to https://github.com/nodejs/build/issues/812

**Comment by rvagg** [comment]
Sorry, this didn't come up in my mentions list so I'm a bit late to the party! I think because you added the mentions in an edit @gibfahn? Edits don't go out as emails so I don't have a mention in the email I have for this so got to it later than my more urgent queue of mentions. Best to do mentions in a new comment in future to be sure.

Done now, on both ci.nodejs.org and ci-release.nodejs.org. FYI these certs and keys are in secrets/build/infra/, encrypted for build/infra eyes only of course.

**Comment by mhdawson** [comment]
Can we close the issue ?

**Comment by aqrln** [comment]
@mhdawson yes, absolutely. I forgot about it, sorry.

@rvagg thanks for resolving the issue!
