### ISSUE TITLE
make: the '-j' option requires a positive integer argument

### ISSUE THREAD

**Issue by silverwind** [nodejs/build#857]
Noticed on this run:

https://ci.nodejs.org/job/node-test-commit-arm/11808/nodes=ubuntu1604-arm64_odroid_c2/console

I'm not sure why it fails on that target but maybe `make -j $(nproc)` is a better alternative on Linux.

**Comment by refack** [comment]
Cross-ref: https://github.com/nodejs/build/pull/841#issuecomment-325977049

**Comment by gibfahn** [comment]
Yeah that seems like an issue with the machine and the test. We should probably default to 2/4 (2 on the arm machines seems more reasonable).

Changed the test from `$JOBS` to `${JOBS:-2}`. I note there's also a comment from @jbergstroem saying that he changed it from `$JOBS` to `2`, so that seems like a reasonable default.

**Comment by gibfahn** [comment]
Also @nodejs/build is `$JOBS` normally defined in the machine config? I was going to add it as an environment variable, but I couldn't see it in any of the others so wasn't sure that was correct.

**Comment by joaocgreis** [comment]
It's in the start.sh script, that way it can be defined independently for each host.
- [`ansible/host_vars/README.md`](https://github.com/nodejs/build/blob/0707dc27d88eb3ee43cb761736d341b211d149e0/ansible/host_vars/README.md)
- Example for systemd: [`ansible/roles/jenkins-worker/templates/systemd.service.j2#L17`](https://github.com/nodejs/build/blob/0707dc27d88eb3ee43cb761736d341b211d149e0/ansible/roles/jenkins-worker/templates/systemd.service.j2#L17)

The default shouldn't hurt.

**Comment by gibfahn** [comment]
I guess we need to work out why `JOBS` wasn't set on the machines.

**Comment by gibfahn** [comment]
So it turns out `$JOBS` wasn't undefined, it was actually set to `0`.

You can see by running this in the script console (e.g. [here](https://ci.nodejs.org/computer/test-mininodes-ubuntu1604-arm64_odroid_c2-2/script))

```groovy
println System.getenv("JOBS")

// Returns: 0
```

I've added this to the job, but the real fix would be to make sure that JOBS is never set to 0 in the start.sh script.

```bash
[ "$JOBS" = 0 ] && export JOBS=2
```
