### ISSUE TITLE
Consistent compile and test failures on win-vs2017

### ISSUE THREAD

**Issue by jasnell** [nodejs/build#859]
See: https://ci.nodejs.org/job/node-compile-windows/11437/label=win-vs2017/console

Getting this consistently across multiple CI runs only on this box. It's causing CI to be consistently red.

**Comment by joaocgreis** [comment]
A lock file was left behind by git, probably because of a job that was aborted while git was running (all evidence points to https://ci.nodejs.org/job/node-compile-windows/11399/).

- `test-rackspace-win2012r2-x64-10` was cleaned by @refack (Ref https://github.com/nodejs/build/issues/858)
- I just cleaned `test-rackspace-win2012r2-x64-5` 

I believe that's all, please reopen if I missed something.
