### ISSUE TITLE
Build WG Meeting Sep 12 @ 10 PM  UTC

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#875]
### When

Sep 12, 2017 10 PM UTC - [time in your timezone](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Build+WG+Meeting&iso=20170912T22&p1=1440&ah=1)

### Where
- [Hangouts on Air, for participants](https://hangouts.google.com/hangouts/_/ytl/AcMmruOezHj1vtB6EdFoQ4SvUMyS5otpKJAIVcqjiqc=?eid=100598160817214911030)
- [Youtube stream, for viewers](https://www.youtube.com/watch?v=oflJCk6hne0)
- [Events page](https://www.youtube.com/my_live_events?filter=scheduled)
- [Minutes document](https://docs.google.com/document/d/1M2OzNlN-FKYuZW4AgKORhnR0g7eniHApsAxQ6Ujb8cg/edit?usp=sharing)
- [Previous meeting](https://github.com/nodejs/build/issues/837)

### Agenda

Extracted from `wg-agenda` [issues](https://github.com/nodejs/build/issues?q=is%3Aopen+is%3Aissue+label%3Awg-agenda) and [pull requests](https://github.com/nodejs/build/pulls?q=is%3Aopen+label%3Awg-agenda+is%3Apr) from this repo.

* Demo KeyBox at next WG Meeting [#806](https://github.com/nodejs/build/issues/806)
* ansible: use gcc 4.9 on CentOS 6 [#809](https://github.com/nodejs/build/pull/809)
* ansible: use gcc 4.9 on Ubuntu 14.04 [#797](https://github.com/nodejs/build/pull/797)
* Store resources for Ansible on jenkins ci master [#871](https://github.com/nodejs/build/issues/871)

All welcome of course, primarily @nodejs/build focused but we're happy to expand.

Please 👍 if you can make the meeting, and 👎 if you cannot.

**Comment by joaocgreis** [comment]
I won't be able to make it to this one.

I added https://github.com/nodejs/build/pull/809 and https://github.com/nodejs/build/pull/797 to the agenda, and they should be discussed even without me (I added because I can't take them further). I helped with the Ansible changes without realizing that we may not be able to land it because of compatibility (@seishun I'm sorry for this and thanks for all the hard work you've done on those PRs). If I understand correctly, the changes proposed will break 32-bit build on Linux. I don't think this is something we can do for current versions, but don't know if we can for upcoming versions or at all. This needs someone with more Linux experience to weight in.

**Comment by seishun** [comment]
@mhdawson Is it 6AM or 6PM?

@joaocgreis As far as I can tell, https://github.com/nodejs/build/pull/797 doesn't break anything. https://github.com/nodejs/build/pull/809 is "breaking" in the sense that it's not (easily?) possible to install a supported version of gcc on 32-bit CentOS 6, which means it would probably need to be dropped from CI. According to @rvagg (https://github.com/nodejs/build/pull/797#issuecomment-316963881), public releases are built on CentOS 6, so 32-bit releases would need to be built on a different machine or dropped altogether.

If these changes cannot land, then I'd like to see an alternative suggestion. Leaving it as-is isn't really an option since the CI machines in question (and many others that I haven't looked into yet) currently use unsupported compiler versions. (see https://github.com/nodejs/build/issues/762)

**Comment by gdams** [comment]
@seishun it's at 6PM

**Comment by piccoloaiutante** [comment]
I won't be albe to make it. I haven't done anything in the past three weeks since I've been mostly on vacation.

**Comment by Trott** [comment]
Super minor nit, but this will be at 6PM EDT, not EST, right? If so, I guess the title should be edited to change that... (perhaps even better, just update it to be UTC?)

**Comment by mhdawson** [comment]
link for participants https://hangouts.google.com/hangouts/_/ytl/AcMmruOezHj1vtB6EdFoQ4SvUMyS5otpKJAIVcqjiqc=?eid=100598160817214911030

**Comment by rvagg** [comment]
Thanks so much for the Keybox demo @gdams, that's actually pretty exciting! @jbergstroem you should review the video for this.

**Comment by rvagg** [comment]
oh, and @joaocgreis there's some discussion about Windows & 32-bit binaries in there that'll end up in an issue but you may want to listen to the discussion if you have time

**Comment by skavanagh** [comment]
@gdams  - so I somehow stumbled across this post.. 

An alternative is to set things up so users can login and set their own keys to the systems under the profiles they have been assigned (and you can then disable those keys anytime). That way you aren't adding the public keys for them.

https://github.com/skavanagh/KeyBox/issues/138#issuecomment-220196009 

This way everyone handles their own keys to discourage sharing / reuse. And if you have keybox generate the key for the users, you can require them to set a good passphrase for the private (at least initially, I guess they could always remove it).

What's nice about setting it up this way.. is it makes it easy to rotate keys, since (after the key has been disabled) the user can just login to keybox and issue new ones for themselves.

Hope this helps!
