### ISSUE TITLE
Need an AIX machine

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/build#891]
I am testing the possibility of delivering on our promise to compile N-API modules once, and then never again. To do that on versions of node that have not delivered N-API, we need to build N-API as a standalone libaray, distribute the binary, and then use `dlopen()` with `RTLD_GLOBAL` to make its symbols available to the N-API module that would use them.

@mcollina and I have gotten this to work on Linux and OSX, and I would like to get it to work on AIX as well. To that end, I would like (preferably shell) access to a community AIX machine.

**Comment by gibfahn** [comment]
+1 to giving @gabrielschulhof access to the AIX machines.

I'll put his key on a machine and send him instructions once someone else +1s.

**Comment by refack** [comment]
+1

**Comment by gibfahn** [comment]
@gabrielschulhof please send me your public key (`gibfahn` on Twitter, or `gibfahn@gmail.com, whatever's easier). I'll send you instructions.

**Comment by gabrielschulhof** [comment]
@gibfahn I have sent you my public key.

**Comment by gibfahn** [comment]
@gabrielschulhof I've given you access to `root@test-osuosl-aix61-ppc64_be-1`, you can find the IP here:

https://github.com/nodejs/build/blob/d7fc4a7ce3597d8f3db134872363d0a0dade6cdb/ansible/inventory.yml#L127

A couple of things to remember (some specific to this machine):
- Work as `iojs` not `root` (`su iojs` as soon as you log in, everyone forgets this)
- The default shell is `ksh` rather than `bash` (so do `bash` after the `su iojs`)
- I created you a homedir at `/home/gabrielschulhof`, keep stuff in there where possible, and delete when you're done.
- Feel free to copy workspaces from Jenkins (jenkins workspace is at `/home/iojs/build/workspace`) but don't work in those directories or you'll mess up jobs.
- This machine is quite resource constrained, sorry about that!
- If you don't have a keepalive setting in your `~/.ssh/config` you'll get kicked off quite quickly, I recommend putting this at the top:

```
Host *
   ServerAliveInterval 120
```

**Comment by gibfahn** [comment]
Let us know when you're done with the machine, or if you need any help.

**Comment by gabrielschulhof** [comment]
Thank you! I'll let you know.

**Comment by mhdawson** [comment]
belated +1

**Comment by mhdawson** [comment]
@gibfahn just for reference, I've most often create a new user for people when I've given access like this.  I create the user and the ssh key.  Then when they are done delete the user and remove their directory.  Its and easy way to know what to clean up.

**Comment by refack** [comment]
@gabrielschulhof was the issue resolved?

**Comment by gabrielschulhof** [comment]
Yes, thanks, sorry, closing :)

**Comment by refack** [comment]
> Yes, thanks, sorry, closing 

Removed key.

**Comment by gabrielschulhof** [comment]
@refack @gibfahn I actually didn't know that closing this issue would result in the removal of my key from the machine. Could you please put it back? Now that https://github.com/nodejs/node-addon-api/pull/103 is starting to work for Linux and OSX, I would like to also make it work on AIX.

**Comment by gibfahn** [comment]
I'll add you back in.

**Comment by gabrielschulhof** [comment]
@gibfahn Thanks!

**Comment by gibfahn** [comment]
@gabrielschulhof okay, I've created you a user on the machine as Michael suggested, you can get to it with: `ssh gabriel@test-osuosl-aix61-ppc64_be-1` or `ssh gabriel@140.211.9.101`.

For future reference, I did:

```bash
useradd -m -s /bin/bash -g staff gabriel
```

**Comment by gdams** [comment]
@gabrielschulhof do you still need access or can we now remove your user?

**Comment by gabrielschulhof** [comment]
No, I do not. Please remove my access! Thank you for your help!

**Comment by gdams** [comment]
removed user from test-osuosl-aix61-ppc64_be-1

For future reference, I did:
```bash
userdel gabriel && rm -rf /home/gabriel
```
