### ISSUE TITLE
Arm v7 builds are reported as arm v6

### ISSUE THREAD

**Issue by Loghorn** [nodejs/build#897]
I downloaded the latest node version (8.6.0) for arm v7 and I noticed that `process.config.variables.arm_version` is `6` instead of `7`:

  process.vonfig.variables
  { arm_float_abi: 'hard',
    arm_fpu: 'vfp',
    arm_thumb: 0,
    arm_version: '6',
    asan: 0,
    ...

I tested a few old node version and node 4.0.0 correctly reported:

  process.config.variables
  { arm_float_abi: 'hard',
    arm_fpu: 'vfpv3',
    arm_thumb: 0,
    arm_version: '7',
    asan: 0,
    ...

Starting with node 5.0.0 it changed to `6` (I've not checked all the 4.x versions).

If you need it, `node --v8-options | head -1` returns `target arm v6 vfp2 hard`

**Comment by refack** [comment]
Cross-ref https://github.com/nodejs/nodejs.org/issues/1382
It seems like the ARM6 binaries were misnamed so they probably overwrote the ARM7 ones.

**Comment by joaocgreis** [comment]
This looks like a duplicate of https://github.com/nodejs/build/issues/829 .

This is not related to https://github.com/nodejs/nodejs.org/issues/1382, that issue is because there were no ARMv6 machines available to build the release.

**Comment by rvagg** [comment]
Yeah, still on my plate, had to compile a custom gcc for our armv7 machines to get binaries on them. They are currently using gcc 4.8 from the raspbian repositories (they are not raspberry pi machines either) and that's an armv6 compiler. Current status is that I have a 4.9 compiled on a spare server on Scaleway but haven't had anywhere to store it for future provisioning, since we now have the static served directory on ci.nodejs.org that problem is solved so it's just a matter of putting the pieces together.
This is a job someone else in build/test could do I suppose, I'd just have to give you a rundown on what I've done so far and what still needs to be done.
