### ISSUE TITLE
Now: No sub-jobs

### ISSUE THREAD

**Issue by refack** [nodejs/build#916]
Probably as a result of updating to Jenkins 2.73.2 (done around 2017-10-13 01:00 UTC - https://github.com/nodejs/build/issues/775#issuecomment-336310114)

Reported by @Trott on IRC - http://logs.libuv.org/node-build/2017-10-13#05:15:21.326

Resolved by @joaocgreis around 2017-10-13 17:00 UTC http://logs.libuv.org/node-build/2017-10-13#14:18:41.955

**Comment by joaocgreis** [comment]
This happened because the Jenkins update fixed https://github.com/nodejs/build/issues/265 (note this has been around for so long because subsequent plugin versions also had issues, let's hope this one really fixes it).

So, we now have to disable all the checkboxes that say "Build only if SCM changes", under advanced, in multi-job jobs. This is still an issue on many jobs in Jenkins. @nodejs/build I plan to go over and fix it as soon as I can, meanwhile please do it for any jobs you notice failing.

**Comment by joaocgreis** [comment]
All switches flipped. Should be done.
