### ISSUE TITLE
Access to restart builds on Travis triggered by nodejs-github-bot

### ISSUE THREAD

**Issue by SimenB** [nodejs/build#944]
We (@nodejs/docker) have some issues with builds timing out on travis. It would be helpful to restart just one of the node 4, 6 or 8 builds whenever they timeout. Normally this would be as simple as clicking rebuild in the travis interface, but that is not available. My guess is that it's not there as the build wasn't triggered by github (so github permissions doesn't automatically apply), but by `nodejs-github-bot`.

I'm also not sure at all if this is the correct repo to open up this issue in. Please direct me to the correct place if it's not!

Link to travis: https://travis-ci.org/nodejs/docker-node

**Comment by gibfahn** [comment]
cc/ @nodejs/github-bot

**Comment by phillipj** [comment]
I'll skip the long story of why we've got a far from ideal Travis integration setup, the main point is that we don't allow any third GitHub applications private access to the nodejs organisation.

As far as I remember, it is in fact a github.com telling Travis to trigger a build, but Travis is not allowed to post updates back to github.com/nodejs/*. That's why we've made the github-bot poll Travis continuously for updates on the build started for a particular PR. That polling kicks off either when the PR has just been created or changed (the `synchronize` GitHub webhook event).

Refs the related bot code: https://github.com/nodejs/github-bot/blob/master/scripts/display-travis-status.js

**Comment by LaurentGoderre** [comment]
Why don't you create an artifacts repo that the bot was write access? We have done this for years now and it has been great!

**Comment by maclover7** [comment]
Unfortunately this is not something that is immediately actionable, and is related to our handling of third party apps in the nodejs GitHub org.

It looks like the org management policy has been updated to allow apps under certain circumstances -- the details are available at https://github.com/nodejs/admin/blob/master/GITHUB_ORG_MANGEMENT_POLICY.md#use-of-bots-and-services.

Closing for now, since not immediately actionable by the Build WG.
