### ISSUE TITLE
incident: write ssh key fails on all PI3s

### ISSUE THREAD

**Issue by refack** [nodejs/build#975]
First reported by @Trott on [IRC](http://logs.libuv.org/node-build/2017-11-04#17:19:25.651)

* did a quick test whether clearing the WS helps. 🔴 
* did a [noop save of the job ](https://ci.nodejs.org/job/node-test-binary-arm/jobConfigHistory/showDiffFiles?timestamp1=2017-08-19_20-42-57&timestamp2=2017-11-04_15-20-25) 🔴 
* temp resolution - removed [pi3 label from "Configuration Matrix"](https://ci.nodejs.org/job/node-test-binary-arm/jobConfigHistory/showDiffFiles?timestamp1=2017-11-04_15-20-25&timestamp2=2017-11-04_18-28-23) ⚠️ 

![image](https://user-images.githubusercontent.com/96947/32410020-0bc8f732-c18e-11e7-8d9c-c5c5203491cb.png)

/CC @rvagg @joaocgreis

**Comment by Trott** [comment]
> First reported by @Trott on IRC

By the way, I usually report in IRC because it often gets a faster response than opening an issue in the Build repo. And the Build repo has a terrifying ~200 open issues. But if I really ought to be opening issues instead or in addition, I'm happy to do that and save you a step. Just say the word.

(But if just copy/pasting into IRC like I usually do is perfectly fine, I'm gonna keep doing that!  :-D )

**Comment by refack** [comment]
> But if I really ought to be opening issues instead or in addition, I'm happy to do that and save you a step. Just say the word.

The current workflow work for _me_. First IRC notification is much lower volume for me so they get my attention quickers. Second some incidents are trivial to solve, and maybe not even worth a logged issue, so I for now I log an issue only if I did something new/interesting, or I had to resort to a temporary solution it the incidents needs followup.

I'll initiate a discussion within the group about this.

**Comment by rvagg** [comment]
opening an issue here pings IRC and I read the queue there, we can also add it to the project here so it's properly in the queue so I think opening incident issues is probably the most optimal thing to do

**Comment by rvagg** [comment]
Took a bit to figure this one out, nfs can be really hard to debug and get right. It's caused by the "improvements" I'd made in #974, I'm pretty sure it's timing problems for mounting nfs. I've got it sorted now and it's happy over multiple reboots. See https://ci.nodejs.org/job/node-test-binary-arm/11516/

<img width="542" alt="screenshot 2017-11-05 19 41 26" src="https://user-images.githubusercontent.com/495647/32413234-56d545b8-c261-11e7-9ebb-9121d6d02425.png">
