### ISSUE TITLE
Ava failing on all machines in citgm

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#979]
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1065/

Having a hard time wrapping by head around what's breaking here. Passes locally both in repo + citgm... assuming there is something in our infra here. Will investigate after this round of releases

**Comment by rvagg** [comment]
failing on ppc cause flow-cli needs a binary that's not available

failing elsewhere because ... I have no idea. I'm on the debian8 machine trying to replicate it but I can't get a non-zero exit status. If someone wants to look, try test-digitalocean-debian8-x64-1, do `export PATH=/home/iojs/build/workspace/citgm-smoker/nodes/debian8-64/smoker/bin/:$PATH`, then `cd ava-0.23.0` and `npm test`. Redirect it to a file to get the tap output, e.g. `npm test >& /tmp/out`.

Of course this is not necessarily using the same version of the node & npm build that is failing in 1065. But I can't even see what the problem might be in https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1065/nodes=debian8-64/testReport/junit/(root)/citgm/ava_v0_23_0/

**Comment by MylesBorins** [comment]
@rvagg I did a bit more review and it appears that the ubuntu machines that are passing are not exiting the test suite early... really hard to wrap my head around why / what is happening. Only can repro using the citgm job

**Comment by rvagg** [comment]
@MylesBorins one major difference is the lack of proper stdio. If you redirect stdout and stderr you get close to the way it's running `... >& /tmp/out`, even pushing it to the background with `&` might help by getting rid of stdin. That's the first thing to try and assess.

**Comment by MylesBorins** [comment]
With some more research it would appear this might be triggering a race condition bug in npm 3.x

I am marking ava flaky in node < 8 and will track this problem over on the citgm repo

https://github.com/nodejs/citgm/pull/509
