### ISSUE TITLE
Find Jenkins worker IPs?

### ISSUE THREAD

**Issue by phillipj** [nodejs/build#980]
Any hints finding all Jenkins worker IPs?

Asking because we want to start whitelist the Jenkins hosts allowed to post inline PR status updates via the github-bot. The bot already has whitelisting implemented, but the list of IPs is currently not being set when starting the bot.

Refs https://github.com/nodejs/github-bot/pull/142

**Comment by rvagg** [comment]
@maclover7 were we able to restrict this to just the jenkins-workspace hosts? Otherwise it's going to be annoying whenever we add and remove IP addresses from the list. This happens every other week.

The IP addresses are here: https://github.com/nodejs/build/blob/master/ansible/inventory.yml, see the two jenkins-workspace hosts near the bottom, hopefully we can restrict it to just those. Otherwise you're going to have to add everything under the `test` section except for the `requireio` hosts which will come from the single ip address that resolves from `vagg-arm.nodejs.org`.

**Comment by maclover7** [comment]
> were we able to restrict this to just the jenkins-workspace hosts?

Yeah, the only machines running `post-build-status-update` and working with the bot should be jenkins-workspace machines as defined [here](https://github.com/nodejs/build/blob/master/jenkins/pipelines/post-build-status-update.jenkinsfile#L10).

**Comment by phillipj** [comment]
Thanks! Opened https://github.com/nodejs/build/pull/985 to provide those two current IPs to the bot.
