### ISSUE TITLE
Problems updating CI status for jobs that git rebase

### ISSUE THREAD

**Issue by maclover7** [nodejs/build#983]
Take a look at [this node-test-commit-arm-fanned](https://ci.nodejs.org/job/node-test-commit-arm-fanned/12356/) build and its corresponding [post-build-status-update](https://ci.nodejs.org/job/post-build-status-update/3289/) build. If you pull up the parameters for the post-build-status-update, you can see that `COMMIT` is `${GIT_COMMIT}`, due to the git-rebase job that was run with arm-fanned, clearing the environment variable automatically set by Jenkins.

Biggest problem is that this is causing the wrong CI status to be sent to be GitHub. Related problem (I myself don't have context on this, part of why I'm opening the issue) is why we would need to run git-rebase on certain node-test-commit sub jobs, but not on others :(

cc @MylesBorins, I think this may have been part of what was causing the issue for you in https://github.com/nodejs/node/pull/16848
cc @refack @gibfahn

**Comment by joaocgreis** [comment]
According to https://wiki.jenkins.io/display/JENKINS/Git+Plugin , it's the git plugin that sets `GIT_COMMIT`. The `*-fanned` jobs don't use the git plugin because they don't need to (running it would make them slower). This is why that variable does not exist, not because `git-rebase` clears it.

The `git-rebase` job is needed to rabase (which is done by a build step in other jobs) and push the commit to test to the temp repo. This rebase step could be part of the compile jobs, but it would make them more complex than they already are, so I'd prefer not to go that way. What we can do to make this work is add a git checkout in the fanned jobs and accept the delay.

**Comment by gibfahn** [comment]
Couldn't the node-test-commit job just pass `GIT_COMMIT` down to the subjobs?

**Comment by joaocgreis** [comment]
I've added the parameter `GIT_COMMIT` to both fanned jobs, and logic in `node-test-commit` to pass it down. Seems to be working as expected, please reopen if not.
